%% Author: Igor compiler
%% Compiler version: igorc 2.1.4
%% DO NOT EDIT THIS FILE - it is machine generated

-record(enum_pair, {
    key :: binary(),
    value :: igor_types:int()
}).

-record(type_spec, {
    raw_spec = <<"">> :: binary(),
    data_type = special :: clickhouse_protocol:data_type(),
    nullable = false :: boolean(),
    enum_items :: [clickhouse_protocol:enum_pair()] | 'undefined',
    decimal_precision :: igor_types:int() | 'undefined',
    decimal_scale :: igor_types:int() | 'undefined',
    fixed_string_length :: igor_types:int() | 'undefined',
    array_item_type :: clickhouse_protocol:type_spec() | 'undefined',
    tuple_item_types :: [clickhouse_protocol:type_spec()] | 'undefined'
}).

-record(column_def, {
    name :: binary(),
    type :: clickhouse_protocol:type_spec()
}).

-record(query_statistics, {
    elapsed :: float(),
    rows_read :: igor_types:long(),
    bytes_read :: igor_types:long()
}).

-record(query_result, {
    meta :: [clickhouse_protocol:column_def()],
    data :: [igor_json:json()],
    rows :: igor_types:long(),
    rows_before_limit_at_least :: igor_types:long() | 'undefined',
    statistics :: clickhouse_protocol:query_statistics()
}).

