// Author: Igor compiler
// Compiler version: igorc 2.1.4
// DO NOT EDIT THIS FILE - it is machine generated

import * as Igor from './igor';
import * as DataProtocol from './data-protocol';
import * as CommonProtocol from './common-protocol';

export enum CardCategory {
    Config = 1,
    Metric = 2,
    Map = 3,
    QueryParam = 4,
    Query = 5,
    Event = 6,
    EventGroup = 7,
    PatchNote = 8,
    Widget = 9,
}

export namespace CardCategory {
    export function toJson(value: CardCategory): Igor.Json.JsonValue {
        return toJsonKey(value);
    }

    export function fromJson(json: Igor.Json.JsonValue): CardCategory {
        return fromJsonKey(json);
    }

    export function toJsonKey(value: CardCategory): Igor.Json.JsonValue {
        switch (value) {
            case CardCategory.Config: return 'config';
            case CardCategory.Metric: return 'metric';
            case CardCategory.Map: return 'map';
            case CardCategory.QueryParam: return 'query_param';
            case CardCategory.Query: return 'query';
            case CardCategory.Event: return 'event';
            case CardCategory.EventGroup: return 'event_group';
            case CardCategory.PatchNote: return 'patch_note';
            case CardCategory.Widget: return 'widget';
            default: throw new Error(`Invalid CardCategory value: ${value}`);
        }
    }

    export function fromJsonKey(json: Igor.Json.JsonValue): CardCategory {
        switch (json) {
            case 'config': return CardCategory.Config;
            case 'metric': return CardCategory.Metric;
            case 'map': return CardCategory.Map;
            case 'query_param': return CardCategory.QueryParam;
            case 'query': return CardCategory.Query;
            case 'event': return CardCategory.Event;
            case 'event_group': return CardCategory.EventGroup;
            case 'patch_note': return CardCategory.PatchNote;
            case 'widget': return CardCategory.Widget;
            default: throw new Error(`Invalid CardCategory value: ${json}`);
        }
    }
}

export abstract class Card {
    category!: CardCategory;
    id!: string;

    static fromJson(json: Igor.Json.JsonValue): Card {
        const jsonObject = json as Igor.Json.JsonObject;
        const category = CardCategory.fromJson(jsonObject['category']);
        switch(category) {
            case CardCategory.Config:
                return CardConfig.fromJson(json);
            case CardCategory.Metric:
                return CardMetric.fromJson(json);
            case CardCategory.Map:
                return CardMap.fromJson(json);
            case CardCategory.QueryParam:
                return CardQueryParam.fromJson(json);
            case CardCategory.Query:
                return CardQuery.fromJson(json);
            case CardCategory.Event:
                return CardEvent.fromJson(json);
            case CardCategory.EventGroup:
                return CardEventGroup.fromJson(json);
            case CardCategory.PatchNote:
                return CardPatchNote.fromJson(json);
            case CardCategory.Widget:
                return CardWidget.fromJson(json);
            default:
                throw new Error(`Invalid CardCategory value: ${category}`);
        }
    }

    static toJson(value: Card): Igor.Json.JsonValue {
        return value.toJson();
    }

    abstract toJson(): Igor.Json.JsonValue;
}

export enum ClickhouseServer {
    /** https://clickhouse.yourcompany.com:8443/ */
    Default = 1,
}

export namespace ClickhouseServer {
    export function toJson(value: ClickhouseServer): Igor.Json.JsonValue {
        return toJsonKey(value);
    }

    export function fromJson(json: Igor.Json.JsonValue): ClickhouseServer {
        return fromJsonKey(json);
    }

    export function toJsonKey(value: ClickhouseServer): Igor.Json.JsonValue {
        switch (value) {
            case ClickhouseServer.Default: return 'default';
            default: throw new Error(`Invalid ClickhouseServer value: ${value}`);
        }
    }

    export function fromJsonKey(json: Igor.Json.JsonValue): ClickhouseServer {
        switch (json) {
            case 'default': return ClickhouseServer.Default;
            default: throw new Error(`Invalid ClickhouseServer value: ${json}`);
        }
    }
}

export class CardConfig extends Card {
    category: CardCategory = CardCategory.Config;
    id!: string;
    projectName!: string;
    databases!: Array<string>;
    clickhouseServer: ClickhouseServer = ClickhouseServer.Default;
    dashboardWidgets: Array<string> = [];
    metrics: Array<string> = [];
    maps: Array<string> = [];
    parameters: Array<string> = [];
    queries: Array<string> = [];
    eventSuperFields!: Array<string>;
    eventGroups: Array<string> = [];
    patchNotes: Array<string> = [];

    static fromJson(json: Igor.Json.JsonValue): CardConfig {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new CardConfig();
        obj.id = jsonObject['_id'] as string;
        obj.projectName = jsonObject['project_name'] as string;
        obj.databases = Igor.Json.List(Igor.Json.String).fromJson(jsonObject['databases']);
        obj.clickhouseServer = ('clickhouse_server' in jsonObject && jsonObject['clickhouse_server'] != null) ? ClickhouseServer.fromJson(jsonObject['clickhouse_server']) : ClickhouseServer.Default;
        obj.dashboardWidgets = ('dashboard_widgets' in jsonObject && jsonObject['dashboard_widgets'] != null) ? Igor.Json.List(Igor.Json.String).fromJson(jsonObject['dashboard_widgets']) : [];
        obj.metrics = ('metrics' in jsonObject && jsonObject['metrics'] != null) ? Igor.Json.List(Igor.Json.String).fromJson(jsonObject['metrics']) : [];
        obj.maps = ('maps' in jsonObject && jsonObject['maps'] != null) ? Igor.Json.List(Igor.Json.String).fromJson(jsonObject['maps']) : [];
        obj.parameters = ('parameters' in jsonObject && jsonObject['parameters'] != null) ? Igor.Json.List(Igor.Json.String).fromJson(jsonObject['parameters']) : [];
        obj.queries = ('queries' in jsonObject && jsonObject['queries'] != null) ? Igor.Json.List(Igor.Json.String).fromJson(jsonObject['queries']) : [];
        obj.eventSuperFields = Igor.Json.List(Igor.Json.String).fromJson(jsonObject['event_super_fields']);
        obj.eventGroups = ('event_groups' in jsonObject && jsonObject['event_groups'] != null) ? Igor.Json.List(Igor.Json.String).fromJson(jsonObject['event_groups']) : [];
        obj.patchNotes = ('patch_notes' in jsonObject && jsonObject['patch_notes'] != null) ? Igor.Json.List(Igor.Json.String).fromJson(jsonObject['patch_notes']) : [];
        return obj;
    }

    static toJson(value: CardConfig): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['category'] = CardCategory.toJson(value.category);
        result['_id'] = value.id;
        result['project_name'] = value.projectName;
        result['databases'] = Igor.Json.List(Igor.Json.String).toJson(value.databases);
        result['clickhouse_server'] = ClickhouseServer.toJson(value.clickhouseServer);
        result['dashboard_widgets'] = Igor.Json.List(Igor.Json.String).toJson(value.dashboardWidgets);
        result['metrics'] = Igor.Json.List(Igor.Json.String).toJson(value.metrics);
        result['maps'] = Igor.Json.List(Igor.Json.String).toJson(value.maps);
        result['parameters'] = Igor.Json.List(Igor.Json.String).toJson(value.parameters);
        result['queries'] = Igor.Json.List(Igor.Json.String).toJson(value.queries);
        result['event_super_fields'] = Igor.Json.List(Igor.Json.String).toJson(value.eventSuperFields);
        result['event_groups'] = Igor.Json.List(Igor.Json.String).toJson(value.eventGroups);
        result['patch_notes'] = Igor.Json.List(Igor.Json.String).toJson(value.patchNotes);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return CardConfig.toJson(this);
    }
}

export class CardMetric extends Card {
    category: CardCategory = CardCategory.Metric;
    id!: string;
    name!: string;

    static fromJson(json: Igor.Json.JsonValue): CardMetric {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new CardMetric();
        obj.id = jsonObject['_id'] as string;
        obj.name = jsonObject['name'] as string;
        return obj;
    }

    static toJson(value: CardMetric): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['category'] = CardCategory.toJson(value.category);
        result['_id'] = value.id;
        result['name'] = value.name;
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return CardMetric.toJson(this);
    }
}

export class CardMap extends Card {
    category: CardCategory = CardCategory.Map;
    id!: string;
    name!: string;
    key!: string;
    url!: string;
    minX!: number;
    minY!: number;
    maxX!: number;
    maxY!: number;

    static fromJson(json: Igor.Json.JsonValue): CardMap {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new CardMap();
        obj.id = jsonObject['_id'] as string;
        obj.name = jsonObject['name'] as string;
        obj.key = jsonObject['key'] as string;
        obj.url = jsonObject['url'] as string;
        obj.minX = jsonObject['min_x'] as number;
        obj.minY = jsonObject['min_y'] as number;
        obj.maxX = jsonObject['max_x'] as number;
        obj.maxY = jsonObject['max_y'] as number;
        return obj;
    }

    static toJson(value: CardMap): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['category'] = CardCategory.toJson(value.category);
        result['_id'] = value.id;
        result['name'] = value.name;
        result['key'] = value.key;
        result['url'] = value.url;
        result['min_x'] = value.minX;
        result['min_y'] = value.minY;
        result['max_x'] = value.maxX;
        result['max_y'] = value.maxY;
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return CardMap.toJson(this);
    }
}

export class CardQueryParam extends Card implements DataProtocol.IKeyName {
    category: CardCategory = CardCategory.QueryParam;
    id!: string;
    name!: string;
    key!: string;
    type!: DataProtocol.QueryParamType;
    inputSql?: string | null = null;
    valueType?: DataProtocol.PrimitiveType | null = null;
    values?: Array<DataProtocol.StringPoint> | null = null;
    dependsOn?: Array<string> | null = null;

    static fromJson(json: Igor.Json.JsonValue): CardQueryParam {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new CardQueryParam();
        obj.id = jsonObject['_id'] as string;
        obj.name = jsonObject['name'] as string;
        obj.key = jsonObject['key'] as string;
        obj.type = DataProtocol.QueryParamType.fromJson(jsonObject['type']);
        obj.inputSql = ('input_sql' in jsonObject && jsonObject['input_sql'] != null) ? jsonObject['input_sql'] as string : null;
        obj.valueType = ('value_type' in jsonObject && jsonObject['value_type'] != null) ? DataProtocol.PrimitiveType.fromJson(jsonObject['value_type']) : null;
        obj.values = ('values' in jsonObject && jsonObject['values'] != null) ? Igor.Json.List(DataProtocol.StringPoint).fromJson(jsonObject['values']) : null;
        obj.dependsOn = ('depends_on' in jsonObject && jsonObject['depends_on'] != null) ? Igor.Json.List(Igor.Json.String).fromJson(jsonObject['depends_on']) : null;
        return obj;
    }

    static toJson(value: CardQueryParam): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['category'] = CardCategory.toJson(value.category);
        result['_id'] = value.id;
        result['name'] = value.name;
        result['key'] = value.key;
        result['type'] = DataProtocol.QueryParamType.toJson(value.type);
        if (value.inputSql != null) result['input_sql'] = value.inputSql;
        if (value.valueType != null) result['value_type'] = DataProtocol.PrimitiveType.toJson(value.valueType);
        if (value.values != null) result['values'] = Igor.Json.List(DataProtocol.StringPoint).toJson(value.values);
        if (value.dependsOn != null) result['depends_on'] = Igor.Json.List(Igor.Json.String).toJson(value.dependsOn);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return CardQueryParam.toJson(this);
    }
}

export class CardQuery extends Card implements DataProtocol.IKeyName {
    category: CardCategory = CardCategory.Query;
    id!: string;
    name!: string;
    key!: string;
    description!: string;
    metrics: Array<string> = [];
    params: Array<string> = [];
    requiredParams: Array<string> = [];
    nodes: Array<DataProtocol.QueryNode> = [];

    static fromJson(json: Igor.Json.JsonValue): CardQuery {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new CardQuery();
        obj.id = jsonObject['_id'] as string;
        obj.name = jsonObject['name'] as string;
        obj.key = jsonObject['key'] as string;
        obj.description = jsonObject['description'] as string;
        obj.metrics = ('metrics' in jsonObject && jsonObject['metrics'] != null) ? Igor.Json.List(Igor.Json.String).fromJson(jsonObject['metrics']) : [];
        obj.params = ('params' in jsonObject && jsonObject['params'] != null) ? Igor.Json.List(Igor.Json.String).fromJson(jsonObject['params']) : [];
        obj.requiredParams = ('required_params' in jsonObject && jsonObject['required_params'] != null) ? Igor.Json.List(Igor.Json.String).fromJson(jsonObject['required_params']) : [];
        obj.nodes = ('nodes' in jsonObject && jsonObject['nodes'] != null) ? Igor.Json.List(DataProtocol.QueryNode).fromJson(jsonObject['nodes']) : [];
        return obj;
    }

    static toJson(value: CardQuery): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['category'] = CardCategory.toJson(value.category);
        result['_id'] = value.id;
        result['name'] = value.name;
        result['key'] = value.key;
        result['description'] = value.description;
        result['metrics'] = Igor.Json.List(Igor.Json.String).toJson(value.metrics);
        result['params'] = Igor.Json.List(Igor.Json.String).toJson(value.params);
        result['required_params'] = Igor.Json.List(Igor.Json.String).toJson(value.requiredParams);
        result['nodes'] = Igor.Json.List(DataProtocol.QueryNode).toJson(value.nodes);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return CardQuery.toJson(this);
    }
}

export class CardEvent extends Card {
    category: CardCategory = CardCategory.Event;
    id!: string;
    name!: string;
    description!: string;
    addedAt!: Date;
    isImplemented!: boolean;
    isTested!: boolean;
    isActivated?: boolean | null = null;
    fields: Array<string> = [];

    static fromJson(json: Igor.Json.JsonValue): CardEvent {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new CardEvent();
        obj.id = jsonObject['_id'] as string;
        obj.name = jsonObject['name'] as string;
        obj.description = jsonObject['description'] as string;
        obj.addedAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['added_at']);
        obj.isImplemented = jsonObject['is_implemented'] as boolean;
        obj.isTested = jsonObject['is_tested'] as boolean;
        obj.isActivated = ('is_activated' in jsonObject && jsonObject['is_activated'] != null) ? jsonObject['is_activated'] as boolean : null;
        obj.fields = ('fields' in jsonObject && jsonObject['fields'] != null) ? Igor.Json.List(Igor.Json.String).fromJson(jsonObject['fields']) : [];
        return obj;
    }

    static toJson(value: CardEvent): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['category'] = CardCategory.toJson(value.category);
        result['_id'] = value.id;
        result['name'] = value.name;
        result['description'] = value.description;
        result['added_at'] = Igor.Json.DateTimeSerializer.toJson(value.addedAt);
        result['is_implemented'] = value.isImplemented;
        result['is_tested'] = value.isTested;
        if (value.isActivated != null) result['is_activated'] = value.isActivated;
        result['fields'] = Igor.Json.List(Igor.Json.String).toJson(value.fields);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return CardEvent.toJson(this);
    }
}

export class CardEventGroup extends Card {
    category: CardCategory = CardCategory.EventGroup;
    id!: string;
    name!: string;
    description!: string;
    events: Array<string> = [];

    static fromJson(json: Igor.Json.JsonValue): CardEventGroup {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new CardEventGroup();
        obj.id = jsonObject['_id'] as string;
        obj.name = jsonObject['name'] as string;
        obj.description = jsonObject['description'] as string;
        obj.events = ('events' in jsonObject && jsonObject['events'] != null) ? Igor.Json.List(Igor.Json.String).fromJson(jsonObject['events']) : [];
        return obj;
    }

    static toJson(value: CardEventGroup): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['category'] = CardCategory.toJson(value.category);
        result['_id'] = value.id;
        result['name'] = value.name;
        result['description'] = value.description;
        result['events'] = Igor.Json.List(Igor.Json.String).toJson(value.events);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return CardEventGroup.toJson(this);
    }
}

export class CardPatchNote extends Card {
    category: CardCategory = CardCategory.PatchNote;
    id!: string;
    title!: string;
    description!: string;
    addedAt!: Date;
    analyticsVersion?: number | null = null;
    buildRevision?: number | null = null;

    static fromJson(json: Igor.Json.JsonValue): CardPatchNote {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new CardPatchNote();
        obj.id = jsonObject['_id'] as string;
        obj.title = jsonObject['title'] as string;
        obj.description = jsonObject['description'] as string;
        obj.addedAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['added_at']);
        obj.analyticsVersion = ('analytics_version' in jsonObject && jsonObject['analytics_version'] != null) ? jsonObject['analytics_version'] as number : null;
        obj.buildRevision = ('build_revision' in jsonObject && jsonObject['build_revision'] != null) ? jsonObject['build_revision'] as number : null;
        return obj;
    }

    static toJson(value: CardPatchNote): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['category'] = CardCategory.toJson(value.category);
        result['_id'] = value.id;
        result['title'] = value.title;
        result['description'] = value.description;
        result['added_at'] = Igor.Json.DateTimeSerializer.toJson(value.addedAt);
        if (value.analyticsVersion != null) result['analytics_version'] = value.analyticsVersion;
        if (value.buildRevision != null) result['build_revision'] = value.buildRevision;
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return CardPatchNote.toJson(this);
    }
}

export class CardWidget extends Card {
    category: CardCategory = CardCategory.Widget;
    id!: string;
    key!: string;
    widthCols: number = 3;
    params: Array<string> = [];
    query!: DataProtocol.QueryNode;

    static fromJson(json: Igor.Json.JsonValue): CardWidget {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new CardWidget();
        obj.id = jsonObject['_id'] as string;
        obj.key = jsonObject['key'] as string;
        obj.widthCols = ('width_cols' in jsonObject && jsonObject['width_cols'] != null) ? jsonObject['width_cols'] as number : 3;
        obj.params = ('params' in jsonObject && jsonObject['params'] != null) ? Igor.Json.List(Igor.Json.String).fromJson(jsonObject['params']) : [];
        obj.query = DataProtocol.QueryNode.fromJson(jsonObject['query']);
        return obj;
    }

    static toJson(value: CardWidget): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['category'] = CardCategory.toJson(value.category);
        result['_id'] = value.id;
        result['key'] = value.key;
        result['width_cols'] = value.widthCols;
        result['params'] = Igor.Json.List(Igor.Json.String).toJson(value.params);
        result['query'] = value.query.toJson();
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return CardWidget.toJson(this);
    }
}
