// Author: Igor compiler
// Compiler version: igorc 2.1.4
// DO NOT EDIT THIS FILE - it is machine generated

import * as Igor from './igor';

export class Empty {
    static fromJson(json: Igor.Json.JsonValue): Empty {
        const obj = new Empty();
        return obj;
    }

    static toJson(value: Empty): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return Empty.toJson(this);
    }
}
