// Author: Igor compiler
// Compiler version: igorc 2.1.4
// DO NOT EDIT THIS FILE - it is machine generated

import * as Igor from './igor';
import * as CommonProtocol from './common-protocol';
import * as DataProtocol from './data-protocol';
import * as CardProtocol from './card-protocol';

export enum AccessRole {
    /** Consumer */
    Consumer = 1,
    /** Maintainer */
    Maintainer = 2,
    /** Administrator */
    Admin = 3,
}

export namespace AccessRole {
    export function toJson(value: AccessRole): Igor.Json.JsonValue {
        return toJsonKey(value);
    }

    export function fromJson(json: Igor.Json.JsonValue): AccessRole {
        return fromJsonKey(json);
    }

    export function toJsonKey(value: AccessRole): Igor.Json.JsonValue {
        switch (value) {
            case AccessRole.Consumer: return 'consumer';
            case AccessRole.Maintainer: return 'maintainer';
            case AccessRole.Admin: return 'admin';
            default: throw new Error(`Invalid AccessRole value: ${value}`);
        }
    }

    export function fromJsonKey(json: Igor.Json.JsonValue): AccessRole {
        switch (json) {
            case 'consumer': return AccessRole.Consumer;
            case 'maintainer': return AccessRole.Maintainer;
            case 'admin': return AccessRole.Admin;
            default: throw new Error(`Invalid AccessRole value: ${json}`);
        }
    }

    export function getDescription(value: AccessRole): string {
        switch (value) {
            case AccessRole.Consumer: return 'Consumer';
            case AccessRole.Maintainer: return 'Maintainer';
            case AccessRole.Admin: return 'Administrator';
            default: return '';
        }
    }
}

export interface IResult {
    result: boolean;
}

export class GenericResponse implements IResult {
    result!: boolean;

    static fromJson(json: Igor.Json.JsonValue): GenericResponse {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new GenericResponse();
        obj.result = jsonObject['result'] as boolean;
        return obj;
    }

    static toJson(value: GenericResponse): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['result'] = value.result;
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return GenericResponse.toJson(this);
    }
}

export class PersonnelStatusResponse {
    loggedIn!: boolean;
    userId?: number | null = null;
    email?: string | null = null;
    username?: string | null = null;

    static fromJson(json: Igor.Json.JsonValue): PersonnelStatusResponse {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new PersonnelStatusResponse();
        obj.loggedIn = jsonObject['logged_in'] as boolean;
        obj.userId = ('user_id' in jsonObject && jsonObject['user_id'] != null) ? jsonObject['user_id'] as number : null;
        obj.email = ('email' in jsonObject && jsonObject['email'] != null) ? jsonObject['email'] as string : null;
        obj.username = ('username' in jsonObject && jsonObject['username'] != null) ? jsonObject['username'] as string : null;
        return obj;
    }

    static toJson(value: PersonnelStatusResponse): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['logged_in'] = value.loggedIn;
        if (value.userId != null) result['user_id'] = value.userId;
        if (value.email != null) result['email'] = value.email;
        if (value.username != null) result['username'] = value.username;
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return PersonnelStatusResponse.toJson(this);
    }
}

export class PersonnelLoginRequest {
    username!: string;
    password!: string;

    static fromJson(json: Igor.Json.JsonValue): PersonnelLoginRequest {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new PersonnelLoginRequest();
        obj.username = jsonObject['username'] as string;
        obj.password = jsonObject['password'] as string;
        return obj;
    }

    static toJson(value: PersonnelLoginRequest): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['username'] = value.username;
        result['password'] = value.password;
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return PersonnelLoginRequest.toJson(this);
    }
}

export enum PersonnelLoginError {
    Failure = 1,
    AlreadyLoggedIn = 2,
    AccountNotExists = 3,
    AccountIsBlocked = 4,
    AccountIsDeleted = 5,
    InvalidPassword = 6,
}

export namespace PersonnelLoginError {
    export function toJson(value: PersonnelLoginError): Igor.Json.JsonValue {
        return toJsonKey(value);
    }

    export function fromJson(json: Igor.Json.JsonValue): PersonnelLoginError {
        return fromJsonKey(json);
    }

    export function toJsonKey(value: PersonnelLoginError): Igor.Json.JsonValue {
        switch (value) {
            case PersonnelLoginError.Failure: return 'failure';
            case PersonnelLoginError.AlreadyLoggedIn: return 'already_logged_in';
            case PersonnelLoginError.AccountNotExists: return 'account_not_exists';
            case PersonnelLoginError.AccountIsBlocked: return 'account_is_blocked';
            case PersonnelLoginError.AccountIsDeleted: return 'account_is_deleted';
            case PersonnelLoginError.InvalidPassword: return 'invalid_password';
            default: throw new Error(`Invalid PersonnelLoginError value: ${value}`);
        }
    }

    export function fromJsonKey(json: Igor.Json.JsonValue): PersonnelLoginError {
        switch (json) {
            case 'failure': return PersonnelLoginError.Failure;
            case 'already_logged_in': return PersonnelLoginError.AlreadyLoggedIn;
            case 'account_not_exists': return PersonnelLoginError.AccountNotExists;
            case 'account_is_blocked': return PersonnelLoginError.AccountIsBlocked;
            case 'account_is_deleted': return PersonnelLoginError.AccountIsDeleted;
            case 'invalid_password': return PersonnelLoginError.InvalidPassword;
            default: throw new Error(`Invalid PersonnelLoginError value: ${json}`);
        }
    }

    export function getDescription(value: PersonnelLoginError): string {
        switch (value) {
            case PersonnelLoginError.Failure: return '';
            case PersonnelLoginError.AlreadyLoggedIn: return '';
            case PersonnelLoginError.AccountNotExists: return '';
            case PersonnelLoginError.AccountIsBlocked: return '';
            case PersonnelLoginError.AccountIsDeleted: return '';
            case PersonnelLoginError.InvalidPassword: return '';
            default: return '';
        }
    }
}

export class PersonnelLoginResponse implements IResult {
    result!: boolean;
    error?: PersonnelLoginError | null = null;
    sessionId?: string | null = null;
    userId?: number | null = null;
    email?: string | null = null;
    username?: string | null = null;

    static fromJson(json: Igor.Json.JsonValue): PersonnelLoginResponse {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new PersonnelLoginResponse();
        obj.result = jsonObject['result'] as boolean;
        obj.error = ('error' in jsonObject && jsonObject['error'] != null) ? PersonnelLoginError.fromJson(jsonObject['error']) : null;
        obj.sessionId = ('session_id' in jsonObject && jsonObject['session_id'] != null) ? jsonObject['session_id'] as string : null;
        obj.userId = ('user_id' in jsonObject && jsonObject['user_id'] != null) ? jsonObject['user_id'] as number : null;
        obj.email = ('email' in jsonObject && jsonObject['email'] != null) ? jsonObject['email'] as string : null;
        obj.username = ('username' in jsonObject && jsonObject['username'] != null) ? jsonObject['username'] as string : null;
        return obj;
    }

    static toJson(value: PersonnelLoginResponse): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['result'] = value.result;
        if (value.error != null) result['error'] = PersonnelLoginError.toJson(value.error);
        if (value.sessionId != null) result['session_id'] = value.sessionId;
        if (value.userId != null) result['user_id'] = value.userId;
        if (value.email != null) result['email'] = value.email;
        if (value.username != null) result['username'] = value.username;
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return PersonnelLoginResponse.toJson(this);
    }
}

export class PersonnelAccount {
    id!: number;
    rev!: number;
    username!: string;
    name?: string | null = null;
    email?: string | null = null;
    phone?: string | null = null;
    isBlocked!: boolean;
    isDeleted!: boolean;
    isSuperadmin!: boolean;
    createdAt!: Date;
    updatedAt!: Date;

    static fromJson(json: Igor.Json.JsonValue): PersonnelAccount {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new PersonnelAccount();
        obj.id = jsonObject['id'] as number;
        obj.rev = jsonObject['rev'] as number;
        obj.username = jsonObject['username'] as string;
        obj.name = ('name' in jsonObject && jsonObject['name'] != null) ? jsonObject['name'] as string : null;
        obj.email = ('email' in jsonObject && jsonObject['email'] != null) ? jsonObject['email'] as string : null;
        obj.phone = ('phone' in jsonObject && jsonObject['phone'] != null) ? jsonObject['phone'] as string : null;
        obj.isBlocked = jsonObject['is_blocked'] as boolean;
        obj.isDeleted = jsonObject['is_deleted'] as boolean;
        obj.isSuperadmin = jsonObject['is_superadmin'] as boolean;
        obj.createdAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['created_at']);
        obj.updatedAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['updated_at']);
        return obj;
    }

    static toJson(value: PersonnelAccount): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['id'] = value.id;
        result['rev'] = value.rev;
        result['username'] = value.username;
        if (value.name != null) result['name'] = value.name;
        if (value.email != null) result['email'] = value.email;
        if (value.phone != null) result['phone'] = value.phone;
        result['is_blocked'] = value.isBlocked;
        result['is_deleted'] = value.isDeleted;
        result['is_superadmin'] = value.isSuperadmin;
        result['created_at'] = Igor.Json.DateTimeSerializer.toJson(value.createdAt);
        result['updated_at'] = Igor.Json.DateTimeSerializer.toJson(value.updatedAt);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return PersonnelAccount.toJson(this);
    }
}

export enum PersonnelAccountOrderBy {
    Id = 1,
    Username = 2,
    Email = 3,
    IsBlocked = 4,
    IsDeleted = 5,
    CreatedAt = 6,
    UpdatedAt = 7,
}

export namespace PersonnelAccountOrderBy {
    export function toJson(value: PersonnelAccountOrderBy): Igor.Json.JsonValue {
        return toJsonKey(value);
    }

    export function fromJson(json: Igor.Json.JsonValue): PersonnelAccountOrderBy {
        return fromJsonKey(json);
    }

    export function toJsonKey(value: PersonnelAccountOrderBy): Igor.Json.JsonValue {
        switch (value) {
            case PersonnelAccountOrderBy.Id: return 'id';
            case PersonnelAccountOrderBy.Username: return 'username';
            case PersonnelAccountOrderBy.Email: return 'email';
            case PersonnelAccountOrderBy.IsBlocked: return 'is_blocked';
            case PersonnelAccountOrderBy.IsDeleted: return 'is_deleted';
            case PersonnelAccountOrderBy.CreatedAt: return 'created_at';
            case PersonnelAccountOrderBy.UpdatedAt: return 'updated_at';
            default: throw new Error(`Invalid PersonnelAccountOrderBy value: ${value}`);
        }
    }

    export function fromJsonKey(json: Igor.Json.JsonValue): PersonnelAccountOrderBy {
        switch (json) {
            case 'id': return PersonnelAccountOrderBy.Id;
            case 'username': return PersonnelAccountOrderBy.Username;
            case 'email': return PersonnelAccountOrderBy.Email;
            case 'is_blocked': return PersonnelAccountOrderBy.IsBlocked;
            case 'is_deleted': return PersonnelAccountOrderBy.IsDeleted;
            case 'created_at': return PersonnelAccountOrderBy.CreatedAt;
            case 'updated_at': return PersonnelAccountOrderBy.UpdatedAt;
            default: throw new Error(`Invalid PersonnelAccountOrderBy value: ${json}`);
        }
    }

    export function getDescription(value: PersonnelAccountOrderBy): string {
        switch (value) {
            case PersonnelAccountOrderBy.Id: return '';
            case PersonnelAccountOrderBy.Username: return '';
            case PersonnelAccountOrderBy.Email: return '';
            case PersonnelAccountOrderBy.IsBlocked: return '';
            case PersonnelAccountOrderBy.IsDeleted: return '';
            case PersonnelAccountOrderBy.CreatedAt: return '';
            case PersonnelAccountOrderBy.UpdatedAt: return '';
            default: return '';
        }
    }
}

export class PersonnelAccountProfile {
    id!: number;
    rev!: number;
    username!: string;
    name?: string | null = null;
    email?: string | null = null;
    phone?: string | null = null;
    isBlocked!: boolean;
    isDeleted!: boolean;
    isProjectManager!: boolean;
    isSuperadmin!: boolean;
    createdAt!: Date;
    updatedAt!: Date;

    static fromJson(json: Igor.Json.JsonValue): PersonnelAccountProfile {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new PersonnelAccountProfile();
        obj.id = jsonObject['id'] as number;
        obj.rev = jsonObject['rev'] as number;
        obj.username = jsonObject['username'] as string;
        obj.name = ('name' in jsonObject && jsonObject['name'] != null) ? jsonObject['name'] as string : null;
        obj.email = ('email' in jsonObject && jsonObject['email'] != null) ? jsonObject['email'] as string : null;
        obj.phone = ('phone' in jsonObject && jsonObject['phone'] != null) ? jsonObject['phone'] as string : null;
        obj.isBlocked = jsonObject['is_blocked'] as boolean;
        obj.isDeleted = jsonObject['is_deleted'] as boolean;
        obj.isProjectManager = jsonObject['is_project_manager'] as boolean;
        obj.isSuperadmin = jsonObject['is_superadmin'] as boolean;
        obj.createdAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['created_at']);
        obj.updatedAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['updated_at']);
        return obj;
    }

    static toJson(value: PersonnelAccountProfile): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['id'] = value.id;
        result['rev'] = value.rev;
        result['username'] = value.username;
        if (value.name != null) result['name'] = value.name;
        if (value.email != null) result['email'] = value.email;
        if (value.phone != null) result['phone'] = value.phone;
        result['is_blocked'] = value.isBlocked;
        result['is_deleted'] = value.isDeleted;
        result['is_project_manager'] = value.isProjectManager;
        result['is_superadmin'] = value.isSuperadmin;
        result['created_at'] = Igor.Json.DateTimeSerializer.toJson(value.createdAt);
        result['updated_at'] = Igor.Json.DateTimeSerializer.toJson(value.updatedAt);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return PersonnelAccountProfile.toJson(this);
    }
}

export class PersonnelGroup {
    id!: number;
    rev!: number;
    name!: string;
    description?: string | null = null;
    isDeleted!: boolean;
    members!: Array<string>;
    memberCount!: number;
    isSuperadmin!: boolean;
    createdAt!: Date;
    updatedAt!: Date;

    static fromJson(json: Igor.Json.JsonValue): PersonnelGroup {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new PersonnelGroup();
        obj.id = jsonObject['id'] as number;
        obj.rev = jsonObject['rev'] as number;
        obj.name = jsonObject['name'] as string;
        obj.description = ('description' in jsonObject && jsonObject['description'] != null) ? jsonObject['description'] as string : null;
        obj.isDeleted = jsonObject['is_deleted'] as boolean;
        obj.members = Igor.Json.List(Igor.Json.String).fromJson(jsonObject['members']);
        obj.memberCount = jsonObject['member_count'] as number;
        obj.isSuperadmin = jsonObject['is_superadmin'] as boolean;
        obj.createdAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['created_at']);
        obj.updatedAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['updated_at']);
        return obj;
    }

    static toJson(value: PersonnelGroup): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['id'] = value.id;
        result['rev'] = value.rev;
        result['name'] = value.name;
        if (value.description != null) result['description'] = value.description;
        result['is_deleted'] = value.isDeleted;
        result['members'] = Igor.Json.List(Igor.Json.String).toJson(value.members);
        result['member_count'] = value.memberCount;
        result['is_superadmin'] = value.isSuperadmin;
        result['created_at'] = Igor.Json.DateTimeSerializer.toJson(value.createdAt);
        result['updated_at'] = Igor.Json.DateTimeSerializer.toJson(value.updatedAt);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return PersonnelGroup.toJson(this);
    }
}

export enum PersonnelGroupOrderBy {
    Id = 1,
    Name = 2,
    IsDeleted = 3,
    MemberCount = 4,
    CreatedAt = 5,
    UpdatedAt = 6,
}

export namespace PersonnelGroupOrderBy {
    export function toJson(value: PersonnelGroupOrderBy): Igor.Json.JsonValue {
        return toJsonKey(value);
    }

    export function fromJson(json: Igor.Json.JsonValue): PersonnelGroupOrderBy {
        return fromJsonKey(json);
    }

    export function toJsonKey(value: PersonnelGroupOrderBy): Igor.Json.JsonValue {
        switch (value) {
            case PersonnelGroupOrderBy.Id: return 'id';
            case PersonnelGroupOrderBy.Name: return 'name';
            case PersonnelGroupOrderBy.IsDeleted: return 'is_deleted';
            case PersonnelGroupOrderBy.MemberCount: return 'member_count';
            case PersonnelGroupOrderBy.CreatedAt: return 'created_at';
            case PersonnelGroupOrderBy.UpdatedAt: return 'updated_at';
            default: throw new Error(`Invalid PersonnelGroupOrderBy value: ${value}`);
        }
    }

    export function fromJsonKey(json: Igor.Json.JsonValue): PersonnelGroupOrderBy {
        switch (json) {
            case 'id': return PersonnelGroupOrderBy.Id;
            case 'name': return PersonnelGroupOrderBy.Name;
            case 'is_deleted': return PersonnelGroupOrderBy.IsDeleted;
            case 'member_count': return PersonnelGroupOrderBy.MemberCount;
            case 'created_at': return PersonnelGroupOrderBy.CreatedAt;
            case 'updated_at': return PersonnelGroupOrderBy.UpdatedAt;
            default: throw new Error(`Invalid PersonnelGroupOrderBy value: ${json}`);
        }
    }

    export function getDescription(value: PersonnelGroupOrderBy): string {
        switch (value) {
            case PersonnelGroupOrderBy.Id: return '';
            case PersonnelGroupOrderBy.Name: return '';
            case PersonnelGroupOrderBy.IsDeleted: return '';
            case PersonnelGroupOrderBy.MemberCount: return '';
            case PersonnelGroupOrderBy.CreatedAt: return '';
            case PersonnelGroupOrderBy.UpdatedAt: return '';
            default: return '';
        }
    }
}

export class PersonnelAccountRole {
    personnelId!: number;
    username!: string;
    projectId!: string;
    projectTitle!: string;
    projectDbs!: Igor.Json.JsonValue;
    groupRoles?: Igor.Json.JsonValue | null = null;
    userRole?: AccessRole | null = null;
    isGlobal?: boolean | null = null;
    dbs?: Array<string> | null = null;

    static fromJson(json: Igor.Json.JsonValue): PersonnelAccountRole {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new PersonnelAccountRole();
        obj.personnelId = jsonObject['personnel_id'] as number;
        obj.username = jsonObject['username'] as string;
        obj.projectId = jsonObject['project_id'] as string;
        obj.projectTitle = jsonObject['project_title'] as string;
        obj.projectDbs = jsonObject['project_dbs'];
        obj.groupRoles = ('group_roles' in jsonObject && jsonObject['group_roles'] != null) ? jsonObject['group_roles'] : null;
        obj.userRole = ('user_role' in jsonObject && jsonObject['user_role'] != null) ? AccessRole.fromJson(jsonObject['user_role']) : null;
        obj.isGlobal = ('is_global' in jsonObject && jsonObject['is_global'] != null) ? jsonObject['is_global'] as boolean : null;
        obj.dbs = ('dbs' in jsonObject && jsonObject['dbs'] != null) ? Igor.Json.List(Igor.Json.String).fromJson(jsonObject['dbs']) : null;
        return obj;
    }

    static toJson(value: PersonnelAccountRole): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['personnel_id'] = value.personnelId;
        result['username'] = value.username;
        result['project_id'] = value.projectId;
        result['project_title'] = value.projectTitle;
        result['project_dbs'] = value.projectDbs;
        if (value.groupRoles != null) result['group_roles'] = value.groupRoles;
        if (value.userRole != null) result['user_role'] = AccessRole.toJson(value.userRole);
        if (value.isGlobal != null) result['is_global'] = value.isGlobal;
        if (value.dbs != null) result['dbs'] = Igor.Json.List(Igor.Json.String).toJson(value.dbs);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return PersonnelAccountRole.toJson(this);
    }
}

export enum PersonnelAccountRoleOrderBy {
    PersonnelId = 1,
    Username = 2,
    ProjectId = 3,
    ProjectTitle = 4,
    UserRole = 5,
}

export namespace PersonnelAccountRoleOrderBy {
    export function toJson(value: PersonnelAccountRoleOrderBy): Igor.Json.JsonValue {
        return toJsonKey(value);
    }

    export function fromJson(json: Igor.Json.JsonValue): PersonnelAccountRoleOrderBy {
        return fromJsonKey(json);
    }

    export function toJsonKey(value: PersonnelAccountRoleOrderBy): Igor.Json.JsonValue {
        switch (value) {
            case PersonnelAccountRoleOrderBy.PersonnelId: return 'personnel_id';
            case PersonnelAccountRoleOrderBy.Username: return 'username';
            case PersonnelAccountRoleOrderBy.ProjectId: return 'project_id';
            case PersonnelAccountRoleOrderBy.ProjectTitle: return 'project_title';
            case PersonnelAccountRoleOrderBy.UserRole: return 'user_role';
            default: throw new Error(`Invalid PersonnelAccountRoleOrderBy value: ${value}`);
        }
    }

    export function fromJsonKey(json: Igor.Json.JsonValue): PersonnelAccountRoleOrderBy {
        switch (json) {
            case 'personnel_id': return PersonnelAccountRoleOrderBy.PersonnelId;
            case 'username': return PersonnelAccountRoleOrderBy.Username;
            case 'project_id': return PersonnelAccountRoleOrderBy.ProjectId;
            case 'project_title': return PersonnelAccountRoleOrderBy.ProjectTitle;
            case 'user_role': return PersonnelAccountRoleOrderBy.UserRole;
            default: throw new Error(`Invalid PersonnelAccountRoleOrderBy value: ${json}`);
        }
    }

    export function getDescription(value: PersonnelAccountRoleOrderBy): string {
        switch (value) {
            case PersonnelAccountRoleOrderBy.PersonnelId: return '';
            case PersonnelAccountRoleOrderBy.Username: return '';
            case PersonnelAccountRoleOrderBy.ProjectId: return '';
            case PersonnelAccountRoleOrderBy.ProjectTitle: return '';
            case PersonnelAccountRoleOrderBy.UserRole: return '';
            default: return '';
        }
    }
}

export class PersonnelGroupRole {
    groupId!: number;
    groupName!: string;
    projectId!: string;
    projectTitle!: string;
    projectDbs!: Igor.Json.JsonValue;
    groupRole?: AccessRole | null = null;
    isGlobal?: boolean | null = null;
    dbs?: Array<string> | null = null;

    static fromJson(json: Igor.Json.JsonValue): PersonnelGroupRole {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new PersonnelGroupRole();
        obj.groupId = jsonObject['group_id'] as number;
        obj.groupName = jsonObject['group_name'] as string;
        obj.projectId = jsonObject['project_id'] as string;
        obj.projectTitle = jsonObject['project_title'] as string;
        obj.projectDbs = jsonObject['project_dbs'];
        obj.groupRole = ('group_role' in jsonObject && jsonObject['group_role'] != null) ? AccessRole.fromJson(jsonObject['group_role']) : null;
        obj.isGlobal = ('is_global' in jsonObject && jsonObject['is_global'] != null) ? jsonObject['is_global'] as boolean : null;
        obj.dbs = ('dbs' in jsonObject && jsonObject['dbs'] != null) ? Igor.Json.List(Igor.Json.String).fromJson(jsonObject['dbs']) : null;
        return obj;
    }

    static toJson(value: PersonnelGroupRole): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['group_id'] = value.groupId;
        result['group_name'] = value.groupName;
        result['project_id'] = value.projectId;
        result['project_title'] = value.projectTitle;
        result['project_dbs'] = value.projectDbs;
        if (value.groupRole != null) result['group_role'] = AccessRole.toJson(value.groupRole);
        if (value.isGlobal != null) result['is_global'] = value.isGlobal;
        if (value.dbs != null) result['dbs'] = Igor.Json.List(Igor.Json.String).toJson(value.dbs);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return PersonnelGroupRole.toJson(this);
    }
}

export enum PersonnelGroupRoleOrderBy {
    GroupId = 1,
    GroupName = 2,
    ProjectId = 3,
    ProjectTitle = 4,
    GroupRole = 5,
}

export namespace PersonnelGroupRoleOrderBy {
    export function toJson(value: PersonnelGroupRoleOrderBy): Igor.Json.JsonValue {
        return toJsonKey(value);
    }

    export function fromJson(json: Igor.Json.JsonValue): PersonnelGroupRoleOrderBy {
        return fromJsonKey(json);
    }

    export function toJsonKey(value: PersonnelGroupRoleOrderBy): Igor.Json.JsonValue {
        switch (value) {
            case PersonnelGroupRoleOrderBy.GroupId: return 'group_id';
            case PersonnelGroupRoleOrderBy.GroupName: return 'group_name';
            case PersonnelGroupRoleOrderBy.ProjectId: return 'project_id';
            case PersonnelGroupRoleOrderBy.ProjectTitle: return 'project_title';
            case PersonnelGroupRoleOrderBy.GroupRole: return 'group_role';
            default: throw new Error(`Invalid PersonnelGroupRoleOrderBy value: ${value}`);
        }
    }

    export function fromJsonKey(json: Igor.Json.JsonValue): PersonnelGroupRoleOrderBy {
        switch (json) {
            case 'group_id': return PersonnelGroupRoleOrderBy.GroupId;
            case 'group_name': return PersonnelGroupRoleOrderBy.GroupName;
            case 'project_id': return PersonnelGroupRoleOrderBy.ProjectId;
            case 'project_title': return PersonnelGroupRoleOrderBy.ProjectTitle;
            case 'group_role': return PersonnelGroupRoleOrderBy.GroupRole;
            default: throw new Error(`Invalid PersonnelGroupRoleOrderBy value: ${json}`);
        }
    }

    export function getDescription(value: PersonnelGroupRoleOrderBy): string {
        switch (value) {
            case PersonnelGroupRoleOrderBy.GroupId: return '';
            case PersonnelGroupRoleOrderBy.GroupName: return '';
            case PersonnelGroupRoleOrderBy.ProjectId: return '';
            case PersonnelGroupRoleOrderBy.ProjectTitle: return '';
            case PersonnelGroupRoleOrderBy.GroupRole: return '';
            default: return '';
        }
    }
}

export class AccessRoleUpdateRequest {
    role!: AccessRole;
    isGlobal?: boolean | null = null;
    dbs?: Array<string> | null = null;

    static fromJson(json: Igor.Json.JsonValue): AccessRoleUpdateRequest {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new AccessRoleUpdateRequest();
        obj.role = AccessRole.fromJson(jsonObject['role']);
        obj.isGlobal = ('is_global' in jsonObject && jsonObject['is_global'] != null) ? jsonObject['is_global'] as boolean : null;
        obj.dbs = ('dbs' in jsonObject && jsonObject['dbs'] != null) ? Igor.Json.List(Igor.Json.String).fromJson(jsonObject['dbs']) : null;
        return obj;
    }

    static toJson(value: AccessRoleUpdateRequest): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['role'] = AccessRole.toJson(value.role);
        if (value.isGlobal != null) result['is_global'] = value.isGlobal;
        if (value.dbs != null) result['dbs'] = Igor.Json.List(Igor.Json.String).toJson(value.dbs);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return AccessRoleUpdateRequest.toJson(this);
    }
}

export class Settings {
    personnelSessionDuration!: number;

    static fromJson(json: Igor.Json.JsonValue): Settings {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new Settings();
        obj.personnelSessionDuration = jsonObject['personnel_session_duration'] as number;
        return obj;
    }

    static toJson(value: Settings): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['personnel_session_duration'] = value.personnelSessionDuration;
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return Settings.toJson(this);
    }
}

export class SettingsUpdateRequest {
    personnelSessionDuration?: number | null = null;

    static fromJson(json: Igor.Json.JsonValue): SettingsUpdateRequest {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new SettingsUpdateRequest();
        obj.personnelSessionDuration = ('personnel_session_duration' in jsonObject && jsonObject['personnel_session_duration'] != null) ? jsonObject['personnel_session_duration'] as number : null;
        return obj;
    }

    static toJson(value: SettingsUpdateRequest): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        if (value.personnelSessionDuration != null) result['personnel_session_duration'] = value.personnelSessionDuration;
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return SettingsUpdateRequest.toJson(this);
    }
}

export class AnalyticsQueryNodeResult {
    result!: Array<DataProtocol.Series | null>;

    static fromJson(json: Igor.Json.JsonValue): AnalyticsQueryNodeResult {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new AnalyticsQueryNodeResult();
        obj.result = Igor.Json.List(Igor.Json.Optional(DataProtocol.Series)).fromJson(jsonObject['result']);
        return obj;
    }

    static toJson(value: AnalyticsQueryNodeResult): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['result'] = Igor.Json.List(Igor.Json.Optional(DataProtocol.Series)).toJson(value.result);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return AnalyticsQueryNodeResult.toJson(this);
    }
}

export class AnalyticsQueryResult {
    query!: string;
    result!: Array<AnalyticsQueryNodeResult>;

    static fromJson(json: Igor.Json.JsonValue): AnalyticsQueryResult {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new AnalyticsQueryResult();
        obj.query = jsonObject['query'] as string;
        obj.result = Igor.Json.List(AnalyticsQueryNodeResult).fromJson(jsonObject['result']);
        return obj;
    }

    static toJson(value: AnalyticsQueryResult): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['query'] = value.query;
        result['result'] = Igor.Json.List(AnalyticsQueryNodeResult).toJson(value.result);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return AnalyticsQueryResult.toJson(this);
    }
}

export class WidgetQueryResult {
    query!: string;
    result!: AnalyticsQueryNodeResult;

    static fromJson(json: Igor.Json.JsonValue): WidgetQueryResult {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new WidgetQueryResult();
        obj.query = jsonObject['query'] as string;
        obj.result = AnalyticsQueryNodeResult.fromJson(jsonObject['result']);
        return obj;
    }

    static toJson(value: WidgetQueryResult): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['query'] = value.query;
        result['result'] = value.result.toJson();
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return WidgetQueryResult.toJson(this);
    }
}

export class ProjectConfig {
    id!: string;
    name!: string;
    databases!: Array<string>;

    static fromJson(json: Igor.Json.JsonValue): ProjectConfig {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new ProjectConfig();
        obj.id = jsonObject['id'] as string;
        obj.name = jsonObject['name'] as string;
        obj.databases = Igor.Json.List(Igor.Json.String).fromJson(jsonObject['databases']);
        return obj;
    }

    static toJson(value: ProjectConfig): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['id'] = value.id;
        result['name'] = value.name;
        result['databases'] = Igor.Json.List(Igor.Json.String).toJson(value.databases);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return ProjectConfig.toJson(this);
    }
}

export class DashboardData {
    params!: Array<CardProtocol.CardQueryParam>;
    widgets!: Array<CardProtocol.CardWidget>;

    static fromJson(json: Igor.Json.JsonValue): DashboardData {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new DashboardData();
        obj.params = Igor.Json.List(CardProtocol.CardQueryParam).fromJson(jsonObject['params']);
        obj.widgets = Igor.Json.List(CardProtocol.CardWidget).fromJson(jsonObject['widgets']);
        return obj;
    }

    static toJson(value: DashboardData): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['params'] = Igor.Json.List(CardProtocol.CardQueryParam).toJson(value.params);
        result['widgets'] = Igor.Json.List(CardProtocol.CardWidget).toJson(value.widgets);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return DashboardData.toJson(this);
    }
}

export class AnalyticsData {
    metrics!: Array<CardProtocol.CardMetric>;
    maps!: Array<CardProtocol.CardMap>;
    params!: Array<CardProtocol.CardQueryParam>;
    queries!: Array<CardProtocol.CardQuery>;

    static fromJson(json: Igor.Json.JsonValue): AnalyticsData {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new AnalyticsData();
        obj.metrics = Igor.Json.List(CardProtocol.CardMetric).fromJson(jsonObject['metrics']);
        obj.maps = Igor.Json.List(CardProtocol.CardMap).fromJson(jsonObject['maps']);
        obj.params = Igor.Json.List(CardProtocol.CardQueryParam).fromJson(jsonObject['params']);
        obj.queries = Igor.Json.List(CardProtocol.CardQuery).fromJson(jsonObject['queries']);
        return obj;
    }

    static toJson(value: AnalyticsData): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['metrics'] = Igor.Json.List(CardProtocol.CardMetric).toJson(value.metrics);
        result['maps'] = Igor.Json.List(CardProtocol.CardMap).toJson(value.maps);
        result['params'] = Igor.Json.List(CardProtocol.CardQueryParam).toJson(value.params);
        result['queries'] = Igor.Json.List(CardProtocol.CardQuery).toJson(value.queries);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return AnalyticsData.toJson(this);
    }
}

export class EventData {
    superFields!: Array<string>;
    events!: Array<CardProtocol.CardEvent>;
    groups!: Array<CardProtocol.CardEventGroup>;

    static fromJson(json: Igor.Json.JsonValue): EventData {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new EventData();
        obj.superFields = Igor.Json.List(Igor.Json.String).fromJson(jsonObject['super_fields']);
        obj.events = Igor.Json.List(CardProtocol.CardEvent).fromJson(jsonObject['events']);
        obj.groups = Igor.Json.List(CardProtocol.CardEventGroup).fromJson(jsonObject['groups']);
        return obj;
    }

    static toJson(value: EventData): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['super_fields'] = Igor.Json.List(Igor.Json.String).toJson(value.superFields);
        result['events'] = Igor.Json.List(CardProtocol.CardEvent).toJson(value.events);
        result['groups'] = Igor.Json.List(CardProtocol.CardEventGroup).toJson(value.groups);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return EventData.toJson(this);
    }
}
