// Author: Igor compiler
// Compiler version: igorc 2.1.4
// DO NOT EDIT THIS FILE - it is machine generated

import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse, HttpHeaders } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import * as Igor from './igor';
import * as WebProtocol from './web-protocol';
import * as CommonProtocol from './common-protocol';

@Injectable({
    providedIn: 'root',
})
export class PalladiumAuthService {
    public baseUrl = '';

    constructor(private http: HttpClient) { }

    public getPersonnelStatus(): Observable<WebProtocol.PersonnelStatusResponse> {
        return this.http
            .get(`${this.baseUrl}/api/auth/personnel/status`)
            .pipe(
                map(response => WebProtocol.PersonnelStatusResponse.fromJson(response as Igor.Json.JsonValue))
            );
    }

    public loginPersonnel(request: WebProtocol.PersonnelLoginRequest): Observable<WebProtocol.PersonnelLoginResponse> {
        const options = { headers: new HttpHeaders({'Content-Type': 'application/json' }) };

        return this.http
            .post(`${this.baseUrl}/api/auth/personnel/login`, request.toJson(), options)
            .pipe(
                map(response => WebProtocol.PersonnelLoginResponse.fromJson(response as Igor.Json.JsonValue))
            );
    }

    public logoutPersonnel(request: CommonProtocol.Empty): Observable<WebProtocol.GenericResponse> {
        const options = { headers: new HttpHeaders({'Content-Type': 'application/json' }) };

        return this.http
            .put(`${this.baseUrl}/api/auth/personnel/logout`, request.toJson(), options)
            .pipe(
                map(response => WebProtocol.GenericResponse.fromJson(response as Igor.Json.JsonValue))
            );
    }

    public getMyPersonnelProfile(): Observable<WebProtocol.PersonnelAccountProfile> {
        return this.http
            .get(`${this.baseUrl}/api/auth/personnel/profile`)
            .pipe(
                map(response => WebProtocol.PersonnelAccountProfile.fromJson(response as Igor.Json.JsonValue))
            );
    }
}
