%% @author Igor compiler
%% @doc Compiler version: igorc 2.1.4
%% DO NOT EDIT THIS FILE - it is machine generated

-module(cards).

-include("card_protocol.hrl").

-export([
    card/2,
    card_config/2,
    card_metric/2,
    card_map/2,
    card_query_param/2,
    card_query/2,
    card_event/2,
    card_event_group/2,
    card_patch_note/2,
    card_widget/2
]).

-spec card(Db, Key) -> Record when
      Db :: atom(),
      Key :: catalogue:key(),
      Record :: card_protocol:card().

card(Db, Key) ->
    catalogue:view(Db, Key, card, fun card_protocol:card_from_json/1).

-spec card_config(Db, Key) -> Record when
      Db :: atom(),
      Key :: catalogue:key(),
      Record :: card_protocol:card_config().

card_config(Db, Key) ->
    catalogue:view(Db, Key, card_config, fun card_protocol:card_config_from_json/1).

-spec card_metric(Db, Key) -> Record when
      Db :: atom(),
      Key :: catalogue:key(),
      Record :: card_protocol:card_metric().

card_metric(Db, Key) ->
    catalogue:view(Db, Key, card_metric, fun card_protocol:card_metric_from_json/1).

-spec card_map(Db, Key) -> Record when
      Db :: atom(),
      Key :: catalogue:key(),
      Record :: card_protocol:card_map().

card_map(Db, Key) ->
    catalogue:view(Db, Key, card_map, fun card_protocol:card_map_from_json/1).

-spec card_query_param(Db, Key) -> Record when
      Db :: atom(),
      Key :: catalogue:key(),
      Record :: card_protocol:card_query_param().

card_query_param(Db, Key) ->
    catalogue:view(Db, Key, card_query_param, fun card_protocol:card_query_param_from_json/1).

-spec card_query(Db, Key) -> Record when
      Db :: atom(),
      Key :: catalogue:key(),
      Record :: card_protocol:card_query().

card_query(Db, Key) ->
    catalogue:view(Db, Key, card_query, fun card_protocol:card_query_from_json/1).

-spec card_event(Db, Key) -> Record when
      Db :: atom(),
      Key :: catalogue:key(),
      Record :: card_protocol:card_event().

card_event(Db, Key) ->
    catalogue:view(Db, Key, card_event, fun card_protocol:card_event_from_json/1).

-spec card_event_group(Db, Key) -> Record when
      Db :: atom(),
      Key :: catalogue:key(),
      Record :: card_protocol:card_event_group().

card_event_group(Db, Key) ->
    catalogue:view(Db, Key, card_event_group, fun card_protocol:card_event_group_from_json/1).

-spec card_patch_note(Db, Key) -> Record when
      Db :: atom(),
      Key :: catalogue:key(),
      Record :: card_protocol:card_patch_note().

card_patch_note(Db, Key) ->
    catalogue:view(Db, Key, card_patch_note, fun card_protocol:card_patch_note_from_json/1).

-spec card_widget(Db, Key) -> Record when
      Db :: atom(),
      Key :: catalogue:key(),
      Record :: card_protocol:card_widget().

card_widget(Db, Key) ->
    catalogue:view(Db, Key, card_widget, fun card_protocol:card_widget_from_json/1).

