%% @author Igor compiler
%% @doc Compiler version: igorc 2.1.4
%% DO NOT EDIT THIS FILE - it is machine generated

-module(card_config).

-include("card_protocol.hrl").

-export([
    project_name/1,
    databases/1,
    clickhouse_server/1,
    dashboard_widgets/1,
    metrics/1,
    maps/1,
    parameters/1,
    queries/1,
    event_super_fields/1,
    event_groups/1,
    patch_notes/1
]).

-define(config(Db), (cards:card_config(Db, config))).

-spec project_name(Db :: atom()) -> binary().

project_name(Db) ->
    ?config(Db)#card_config.project_name.

-spec databases(Db :: atom()) -> [binary()].

databases(Db) ->
    ?config(Db)#card_config.databases.

-spec clickhouse_server(Db :: atom()) -> card_protocol:clickhouse_server().

clickhouse_server(Db) ->
    ?config(Db)#card_config.clickhouse_server.

-spec dashboard_widgets(Db :: atom()) -> [card_protocol:widget_key()].

dashboard_widgets(Db) ->
    ?config(Db)#card_config.dashboard_widgets.

-spec metrics(Db :: atom()) -> [card_protocol:metric_key()].

metrics(Db) ->
    ?config(Db)#card_config.metrics.

-spec maps(Db :: atom()) -> [card_protocol:map_key()].

maps(Db) ->
    ?config(Db)#card_config.maps.

-spec parameters(Db :: atom()) -> [card_protocol:query_param_key()].

parameters(Db) ->
    ?config(Db)#card_config.parameters.

-spec queries(Db :: atom()) -> [card_protocol:query_key()].

queries(Db) ->
    ?config(Db)#card_config.queries.

-spec event_super_fields(Db :: atom()) -> [binary()].

event_super_fields(Db) ->
    ?config(Db)#card_config.event_super_fields.

-spec event_groups(Db :: atom()) -> [card_protocol:event_group_key()].

event_groups(Db) ->
    ?config(Db)#card_config.event_groups.

-spec patch_notes(Db :: atom()) -> [card_protocol:patch_note_key()].

patch_notes(Db) ->
    ?config(Db)#card_config.patch_notes.

