%% @author Igor compiler
%% @doc Compiler version: igorc 2.1.4
%% DO NOT EDIT THIS FILE - it is machine generated

-module(card_protocol).

-include_lib("stdlib/include/assert.hrl").
-include("card_protocol.hrl").

-export([
    card_category_to_json/1,
    card_category_from_json/1,
    card_to_json/1,
    card_from_json/1,
    clickhouse_server_to_json/1,
    clickhouse_server_from_json/1,
    card_config_to_json/1,
    card_config_from_json/1,
    card_metric_to_json/1,
    card_metric_from_json/1,
    card_map_to_json/1,
    card_map_from_json/1,
    card_query_param_to_json/1,
    card_query_param_from_json/1,
    card_query_to_json/1,
    card_query_from_json/1,
    card_event_to_json/1,
    card_event_from_json/1,
    card_event_group_to_json/1,
    card_event_group_from_json/1,
    card_patch_note_to_json/1,
    card_patch_note_from_json/1,
    card_widget_to_json/1,
    card_widget_from_json/1
]).

-export_type([
    card_category/0,
    config_key/0,
    metric_key/0,
    map_key/0,
    query_param_key/0,
    query_key/0,
    event_key/0,
    event_group_key/0,
    patch_note_key/0,
    widget_key/0,
    card/0,
    clickhouse_server/0,
    card_config/0,
    card_metric/0,
    card_map/0,
    card_query_param/0,
    card_query/0,
    card_event/0,
    card_event_group/0,
    card_patch_note/0,
    card_widget/0
]).

-type card_category() :: 'config' | 'metric' | 'map' | 'query_param' | 'query' | 'event' | 'event_group' | 'patch_note' | 'widget'.
-type config_key() :: catalogue:key().
-type metric_key() :: catalogue:key().
-type map_key() :: catalogue:key().
-type query_param_key() :: catalogue:key().
-type query_key() :: catalogue:key().
-type event_key() :: catalogue:key().
-type event_group_key() :: catalogue:key().
-type patch_note_key() :: catalogue:key().
-type widget_key() :: catalogue:key().
-type card() :: card_protocol:card_config() | card_protocol:card_metric() | card_protocol:card_map() | card_protocol:card_query_param() | card_protocol:card_query() | card_protocol:card_event() | card_protocol:card_event_group() | card_protocol:card_patch_note() | card_protocol:card_widget().
-type clickhouse_server() :: 'default'.
-type card_config() :: #card_config{}.
-type card_metric() :: #card_metric{}.
-type card_map() :: #card_map{}.
-type card_query_param() :: #card_query_param{}.
-type card_query() :: #card_query{}.
-type card_event() :: #card_event{}.
-type card_event_group() :: #card_event_group{}.
-type card_patch_note() :: #card_patch_note{}.
-type card_widget() :: #card_widget{}.

-spec card_category_to_json(card_category()) -> igor_json:json_string().

card_category_to_json(config) -> <<"config">>;
card_category_to_json(metric) -> <<"metric">>;
card_category_to_json(map) -> <<"map">>;
card_category_to_json(query_param) -> <<"query_param">>;
card_category_to_json(query) -> <<"query">>;
card_category_to_json(event) -> <<"event">>;
card_category_to_json(event_group) -> <<"event_group">>;
card_category_to_json(patch_note) -> <<"patch_note">>;
card_category_to_json(widget) -> <<"widget">>.

-spec card_category_from_json(igor_json:json()) -> card_category().

card_category_from_json(<<"config">>) -> config;
card_category_from_json(<<"metric">>) -> metric;
card_category_from_json(<<"map">>) -> map;
card_category_from_json(<<"query_param">>) -> query_param;
card_category_from_json(<<"query">>) -> query;
card_category_from_json(<<"event">>) -> event;
card_category_from_json(<<"event_group">>) -> event_group;
card_category_from_json(<<"patch_note">>) -> patch_note;
card_category_from_json(<<"widget">>) -> widget.

-spec card_to_json(card()) -> igor_json:json_object().

card_to_json(Record) when is_record(Record, card_config) ->
    card_config_to_json(Record);
card_to_json(Record) when is_record(Record, card_metric) ->
    card_metric_to_json(Record);
card_to_json(Record) when is_record(Record, card_map) ->
    card_map_to_json(Record);
card_to_json(Record) when is_record(Record, card_query_param) ->
    card_query_param_to_json(Record);
card_to_json(Record) when is_record(Record, card_query) ->
    card_query_to_json(Record);
card_to_json(Record) when is_record(Record, card_event) ->
    card_event_to_json(Record);
card_to_json(Record) when is_record(Record, card_event_group) ->
    card_event_group_to_json(Record);
card_to_json(Record) when is_record(Record, card_patch_note) ->
    card_patch_note_to_json(Record);
card_to_json(Record) when is_record(Record, card_widget) ->
    card_widget_to_json(Record).

-spec card_from_json(igor_json:json_object()) -> card().

card_from_json(Json) ->
    Tag = igor_json:parse(Json, <<"category">>, {custom, fun card_protocol:card_category_from_json/1}),
    case Tag of
        config ->
            card_config_from_json(Json);
        metric ->
            card_metric_from_json(Json);
        map ->
            card_map_from_json(Json);
        query_param ->
            card_query_param_from_json(Json);
        query ->
            card_query_from_json(Json);
        event ->
            card_event_from_json(Json);
        event_group ->
            card_event_group_from_json(Json);
        patch_note ->
            card_patch_note_from_json(Json);
        widget ->
            card_widget_from_json(Json)
    end.

-spec clickhouse_server_to_json(clickhouse_server()) -> igor_json:json_string().

clickhouse_server_to_json(default) -> <<"default">>.

-spec clickhouse_server_from_json(igor_json:json()) -> clickhouse_server().

clickhouse_server_from_json(<<"default">>) -> default.

-spec card_config_to_json(card_config()) -> igor_json:json_object().

card_config_to_json(Record) ->
    #card_config{
        id = Id,
        project_name = ProjectName,
        databases = Databases,
        clickhouse_server = ClickhouseServer,
        dashboard_widgets = DashboardWidgets,
        metrics = Metrics,
        maps = Maps,
        parameters = Parameters,
        queries = Queries,
        event_super_fields = EventSuperFields,
        event_groups = EventGroups,
        patch_notes = PatchNotes
    } = Record,
    ?assert(Id =/= undefined),
    ?assert(ProjectName =/= undefined),
    ?assert(Databases =/= undefined),
    ?assert(ClickhouseServer =/= undefined),
    ?assert(DashboardWidgets =/= undefined),
    ?assert(Metrics =/= undefined),
    ?assert(Maps =/= undefined),
    ?assert(Parameters =/= undefined),
    ?assert(Queries =/= undefined),
    ?assert(EventSuperFields =/= undefined),
    ?assert(EventGroups =/= undefined),
    ?assert(PatchNotes =/= undefined),
    #{
        <<"category">> => igor_json:pack(config, {custom, fun card_protocol:card_category_to_json/1}),
        <<"_id">> => igor_json:pack(Id, atom),
        <<"project_name">> => igor_json:pack(ProjectName, string),
        <<"databases">> => igor_json:pack(Databases, {list, string}),
        <<"clickhouse_server">> => igor_json:pack(ClickhouseServer, {custom, fun card_protocol:clickhouse_server_to_json/1}),
        <<"dashboard_widgets">> => igor_json:pack(DashboardWidgets, {list, atom}),
        <<"metrics">> => igor_json:pack(Metrics, {list, atom}),
        <<"maps">> => igor_json:pack(Maps, {list, atom}),
        <<"parameters">> => igor_json:pack(Parameters, {list, atom}),
        <<"queries">> => igor_json:pack(Queries, {list, atom}),
        <<"event_super_fields">> => igor_json:pack(EventSuperFields, {list, string}),
        <<"event_groups">> => igor_json:pack(EventGroups, {list, atom}),
        <<"patch_notes">> => igor_json:pack(PatchNotes, {list, atom})
    }.

-spec card_config_from_json(igor_json:json_object()) -> card_config().

card_config_from_json(Json) ->
    Id = igor_json:parse(Json, <<"_id">>, atom),
    ProjectName = igor_json:parse(Json, <<"project_name">>, string),
    Databases = igor_json:parse(Json, <<"databases">>, {list, string}),
    ClickhouseServer = igor_json:parse(Json, <<"clickhouse_server">>, {custom, fun card_protocol:clickhouse_server_from_json/1}, default),
    DashboardWidgets = igor_json:parse(Json, <<"dashboard_widgets">>, {list, atom}, []),
    Metrics = igor_json:parse(Json, <<"metrics">>, {list, atom}, []),
    Maps = igor_json:parse(Json, <<"maps">>, {list, atom}, []),
    Parameters = igor_json:parse(Json, <<"parameters">>, {list, atom}, []),
    Queries = igor_json:parse(Json, <<"queries">>, {list, atom}, []),
    EventSuperFields = igor_json:parse(Json, <<"event_super_fields">>, {list, string}),
    EventGroups = igor_json:parse(Json, <<"event_groups">>, {list, atom}, []),
    PatchNotes = igor_json:parse(Json, <<"patch_notes">>, {list, atom}, []),
    #card_config{
        id = Id,
        project_name = ProjectName,
        databases = Databases,
        clickhouse_server = ClickhouseServer,
        dashboard_widgets = DashboardWidgets,
        metrics = Metrics,
        maps = Maps,
        parameters = Parameters,
        queries = Queries,
        event_super_fields = EventSuperFields,
        event_groups = EventGroups,
        patch_notes = PatchNotes
    }.

-spec card_metric_to_json(card_metric()) -> igor_json:json_object().

card_metric_to_json(Record) ->
    #card_metric{id = Id, name = Name} = Record,
    ?assert(Id =/= undefined),
    ?assert(Name =/= undefined),
    #{
        <<"category">> => igor_json:pack(metric, {custom, fun card_protocol:card_category_to_json/1}),
        <<"_id">> => igor_json:pack(Id, atom),
        <<"name">> => igor_json:pack(Name, string)
    }.

-spec card_metric_from_json(igor_json:json_object()) -> card_metric().

card_metric_from_json(Json) ->
    Id = igor_json:parse(Json, <<"_id">>, atom),
    Name = igor_json:parse(Json, <<"name">>, string),
    #card_metric{id = Id, name = Name}.

-spec card_map_to_json(card_map()) -> igor_json:json_object().

card_map_to_json(Record) ->
    #card_map{
        id = Id,
        name = Name,
        key = VarKey,
        url = Url,
        min_x = MinX,
        min_y = MinY,
        max_x = MaxX,
        max_y = MaxY
    } = Record,
    ?assert(Id =/= undefined),
    ?assert(Name =/= undefined),
    ?assert(VarKey =/= undefined),
    ?assert(Url =/= undefined),
    ?assert(MinX =/= undefined),
    ?assert(MinY =/= undefined),
    ?assert(MaxX =/= undefined),
    ?assert(MaxY =/= undefined),
    #{
        <<"category">> => igor_json:pack(map, {custom, fun card_protocol:card_category_to_json/1}),
        <<"_id">> => igor_json:pack(Id, atom),
        <<"name">> => igor_json:pack(Name, string),
        <<"key">> => igor_json:pack(VarKey, string),
        <<"url">> => igor_json:pack(Url, string),
        <<"min_x">> => igor_json:pack(MinX, double),
        <<"min_y">> => igor_json:pack(MinY, double),
        <<"max_x">> => igor_json:pack(MaxX, double),
        <<"max_y">> => igor_json:pack(MaxY, double)
    }.

-spec card_map_from_json(igor_json:json_object()) -> card_map().

card_map_from_json(Json) ->
    Id = igor_json:parse(Json, <<"_id">>, atom),
    Name = igor_json:parse(Json, <<"name">>, string),
    VarKey = igor_json:parse(Json, <<"key">>, string),
    Url = igor_json:parse(Json, <<"url">>, string),
    MinX = igor_json:parse(Json, <<"min_x">>, double),
    MinY = igor_json:parse(Json, <<"min_y">>, double),
    MaxX = igor_json:parse(Json, <<"max_x">>, double),
    MaxY = igor_json:parse(Json, <<"max_y">>, double),
    #card_map{
        id = Id,
        name = Name,
        key = VarKey,
        url = Url,
        min_x = MinX,
        min_y = MinY,
        max_x = MaxX,
        max_y = MaxY
    }.

-spec card_query_param_to_json(card_query_param()) -> igor_json:json_object().

card_query_param_to_json(Record) ->
    #card_query_param{
        id = Id,
        name = Name,
        key = VarKey,
        type = Type,
        input_sql = InputSql,
        value_type = ValueType,
        values = Values,
        depends_on = DependsOn
    } = Record,
    ?assert(Id =/= undefined),
    ?assert(Name =/= undefined),
    ?assert(VarKey =/= undefined),
    ?assert(Type =/= undefined),
    #{
        <<"category">> => igor_json:pack(query_param, {custom, fun card_protocol:card_category_to_json/1}),
        <<"_id">> => igor_json:pack(Id, atom),
        <<"name">> => igor_json:pack(Name, string),
        <<"key">> => igor_json:pack(VarKey, string),
        <<"type">> => igor_json:pack(Type, {custom, fun data_protocol:query_param_type_to_json/1}),
        <<"input_sql">> => igor_json:pack(InputSql, string),
        <<"value_type">> => igor_json:pack(ValueType, {custom, fun data_protocol:primitive_type_to_json/1}),
        <<"values">> => igor_json:pack(Values, {list, {custom, fun data_protocol:string_point_to_json/1}}),
        <<"depends_on">> => igor_json:pack(DependsOn, {list, atom})
    }.

-spec card_query_param_from_json(igor_json:json_object()) -> card_query_param().

card_query_param_from_json(Json) ->
    Id = igor_json:parse(Json, <<"_id">>, atom),
    Name = igor_json:parse(Json, <<"name">>, string),
    VarKey = igor_json:parse(Json, <<"key">>, string),
    Type = igor_json:parse(Json, <<"type">>, {custom, fun data_protocol:query_param_type_from_json/1}),
    InputSql = igor_json:parse(Json, <<"input_sql">>, string, undefined),
    ValueType = igor_json:parse(Json, <<"value_type">>, {custom, fun data_protocol:primitive_type_from_json/1}, undefined),
    Values = igor_json:parse(Json, <<"values">>, {list, {custom, fun data_protocol:string_point_from_json/1}}, undefined),
    DependsOn = igor_json:parse(Json, <<"depends_on">>, {list, atom}, undefined),
    #card_query_param{
        id = Id,
        name = Name,
        key = VarKey,
        type = Type,
        input_sql = InputSql,
        value_type = ValueType,
        values = Values,
        depends_on = DependsOn
    }.

-spec card_query_to_json(card_query()) -> igor_json:json_object().

card_query_to_json(Record) ->
    #card_query{
        id = Id,
        name = Name,
        key = VarKey,
        description = Description,
        metrics = Metrics,
        params = Params,
        required_params = RequiredParams,
        nodes = Nodes
    } = Record,
    ?assert(Id =/= undefined),
    ?assert(Name =/= undefined),
    ?assert(VarKey =/= undefined),
    ?assert(Description =/= undefined),
    ?assert(Metrics =/= undefined),
    ?assert(Params =/= undefined),
    ?assert(RequiredParams =/= undefined),
    ?assert(Nodes =/= undefined),
    #{
        <<"category">> => igor_json:pack(query, {custom, fun card_protocol:card_category_to_json/1}),
        <<"_id">> => igor_json:pack(Id, atom),
        <<"name">> => igor_json:pack(Name, string),
        <<"key">> => igor_json:pack(VarKey, string),
        <<"description">> => igor_json:pack(Description, string),
        <<"metrics">> => igor_json:pack(Metrics, {list, atom}),
        <<"params">> => igor_json:pack(Params, {list, atom}),
        <<"required_params">> => igor_json:pack(RequiredParams, {list, atom}),
        <<"nodes">> => igor_json:pack(Nodes, {list, {custom, fun data_protocol:query_node_to_json/1}})
    }.

-spec card_query_from_json(igor_json:json_object()) -> card_query().

card_query_from_json(Json) ->
    Id = igor_json:parse(Json, <<"_id">>, atom),
    Name = igor_json:parse(Json, <<"name">>, string),
    VarKey = igor_json:parse(Json, <<"key">>, string),
    Description = igor_json:parse(Json, <<"description">>, string),
    Metrics = igor_json:parse(Json, <<"metrics">>, {list, atom}, []),
    Params = igor_json:parse(Json, <<"params">>, {list, atom}, []),
    RequiredParams = igor_json:parse(Json, <<"required_params">>, {list, atom}, []),
    Nodes = igor_json:parse(Json, <<"nodes">>, {list, {custom, fun data_protocol:query_node_from_json/1}}, []),
    #card_query{
        id = Id,
        name = Name,
        key = VarKey,
        description = Description,
        metrics = Metrics,
        params = Params,
        required_params = RequiredParams,
        nodes = Nodes
    }.

-spec card_event_to_json(card_event()) -> igor_json:json_object().

card_event_to_json(Record) ->
    #card_event{
        id = Id,
        name = Name,
        description = Description,
        added_at = AddedAt,
        is_implemented = IsImplemented,
        is_tested = IsTested,
        is_activated = IsActivated,
        fields = Fields
    } = Record,
    ?assert(Id =/= undefined),
    ?assert(Name =/= undefined),
    ?assert(Description =/= undefined),
    ?assert(AddedAt =/= undefined),
    ?assert(IsImplemented =/= undefined),
    ?assert(IsTested =/= undefined),
    ?assert(Fields =/= undefined),
    #{
        <<"category">> => igor_json:pack(event, {custom, fun card_protocol:card_category_to_json/1}),
        <<"_id">> => igor_json:pack(Id, atom),
        <<"name">> => igor_json:pack(Name, string),
        <<"description">> => igor_json:pack(Description, string),
        <<"added_at">> => igor_json:pack(AddedAt, {custom, fun web_types:datetime_to_text/1}),
        <<"is_implemented">> => igor_json:pack(IsImplemented, boolean),
        <<"is_tested">> => igor_json:pack(IsTested, boolean),
        <<"is_activated">> => igor_json:pack(IsActivated, boolean),
        <<"fields">> => igor_json:pack(Fields, {list, string})
    }.

-spec card_event_from_json(igor_json:json_object()) -> card_event().

card_event_from_json(Json) ->
    Id = igor_json:parse(Json, <<"_id">>, atom),
    Name = igor_json:parse(Json, <<"name">>, string),
    Description = igor_json:parse(Json, <<"description">>, string),
    AddedAt = igor_json:parse(Json, <<"added_at">>, {custom, fun web_types:datetime_from_text/1}),
    IsImplemented = igor_json:parse(Json, <<"is_implemented">>, boolean),
    IsTested = igor_json:parse(Json, <<"is_tested">>, boolean),
    IsActivated = igor_json:parse(Json, <<"is_activated">>, boolean, undefined),
    Fields = igor_json:parse(Json, <<"fields">>, {list, string}, []),
    #card_event{
        id = Id,
        name = Name,
        description = Description,
        added_at = AddedAt,
        is_implemented = IsImplemented,
        is_tested = IsTested,
        is_activated = IsActivated,
        fields = Fields
    }.

-spec card_event_group_to_json(card_event_group()) -> igor_json:json_object().

card_event_group_to_json(Record) ->
    #card_event_group{
        id = Id,
        name = Name,
        description = Description,
        events = Events
    } = Record,
    ?assert(Id =/= undefined),
    ?assert(Name =/= undefined),
    ?assert(Description =/= undefined),
    ?assert(Events =/= undefined),
    #{
        <<"category">> => igor_json:pack(event_group, {custom, fun card_protocol:card_category_to_json/1}),
        <<"_id">> => igor_json:pack(Id, atom),
        <<"name">> => igor_json:pack(Name, string),
        <<"description">> => igor_json:pack(Description, string),
        <<"events">> => igor_json:pack(Events, {list, atom})
    }.

-spec card_event_group_from_json(igor_json:json_object()) -> card_event_group().

card_event_group_from_json(Json) ->
    Id = igor_json:parse(Json, <<"_id">>, atom),
    Name = igor_json:parse(Json, <<"name">>, string),
    Description = igor_json:parse(Json, <<"description">>, string),
    Events = igor_json:parse(Json, <<"events">>, {list, atom}, []),
    #card_event_group{
        id = Id,
        name = Name,
        description = Description,
        events = Events
    }.

-spec card_patch_note_to_json(card_patch_note()) -> igor_json:json_object().

card_patch_note_to_json(Record) ->
    #card_patch_note{
        id = Id,
        title = Title,
        description = Description,
        added_at = AddedAt,
        analytics_version = AnalyticsVersion,
        build_revision = BuildRevision
    } = Record,
    ?assert(Id =/= undefined),
    ?assert(Title =/= undefined),
    ?assert(Description =/= undefined),
    ?assert(AddedAt =/= undefined),
    #{
        <<"category">> => igor_json:pack(patch_note, {custom, fun card_protocol:card_category_to_json/1}),
        <<"_id">> => igor_json:pack(Id, atom),
        <<"title">> => igor_json:pack(Title, string),
        <<"description">> => igor_json:pack(Description, string),
        <<"added_at">> => igor_json:pack(AddedAt, {custom, fun web_types:datetime_to_text/1}),
        <<"analytics_version">> => igor_json:pack(AnalyticsVersion, int),
        <<"build_revision">> => igor_json:pack(BuildRevision, int)
    }.

-spec card_patch_note_from_json(igor_json:json_object()) -> card_patch_note().

card_patch_note_from_json(Json) ->
    Id = igor_json:parse(Json, <<"_id">>, atom),
    Title = igor_json:parse(Json, <<"title">>, string),
    Description = igor_json:parse(Json, <<"description">>, string),
    AddedAt = igor_json:parse(Json, <<"added_at">>, {custom, fun web_types:datetime_from_text/1}),
    AnalyticsVersion = igor_json:parse(Json, <<"analytics_version">>, int, undefined),
    BuildRevision = igor_json:parse(Json, <<"build_revision">>, int, undefined),
    #card_patch_note{
        id = Id,
        title = Title,
        description = Description,
        added_at = AddedAt,
        analytics_version = AnalyticsVersion,
        build_revision = BuildRevision
    }.

-spec card_widget_to_json(card_widget()) -> igor_json:json_object().

card_widget_to_json(Record) ->
    #card_widget{
        id = Id,
        key = VarKey,
        width_cols = WidthCols,
        params = Params,
        query = Query
    } = Record,
    ?assert(Id =/= undefined),
    ?assert(VarKey =/= undefined),
    ?assert(WidthCols =/= undefined),
    ?assert(Params =/= undefined),
    ?assert(Query =/= undefined),
    #{
        <<"category">> => igor_json:pack(widget, {custom, fun card_protocol:card_category_to_json/1}),
        <<"_id">> => igor_json:pack(Id, atom),
        <<"key">> => igor_json:pack(VarKey, string),
        <<"width_cols">> => igor_json:pack(WidthCols, int),
        <<"params">> => igor_json:pack(Params, {list, atom}),
        <<"query">> => igor_json:pack(Query, {custom, fun data_protocol:query_node_to_json/1})
    }.

-spec card_widget_from_json(igor_json:json_object()) -> card_widget().

card_widget_from_json(Json) ->
    Id = igor_json:parse(Json, <<"_id">>, atom),
    VarKey = igor_json:parse(Json, <<"key">>, string),
    WidthCols = igor_json:parse(Json, <<"width_cols">>, int, 3),
    Params = igor_json:parse(Json, <<"params">>, {list, atom}, []),
    Query = igor_json:parse(Json, <<"query">>, {custom, fun data_protocol:query_node_from_json/1}),
    #card_widget{
        id = Id,
        key = VarKey,
        width_cols = WidthCols,
        params = Params,
        query = Query
    }.

