%% @author Igor compiler
%% @doc Compiler version: igorc 2.1.4
%% DO NOT EDIT THIS FILE - it is machine generated

-module(data_protocol).

-include_lib("stdlib/include/assert.hrl").
-include("data_protocol.hrl").

-export([
    order_direction_to_string/1,
    order_direction_from_string/1,
    order_direction_to_json/1,
    order_direction_from_json/1,
    primitive_type_to_string/1,
    primitive_type_from_string/1,
    primitive_type_to_json/1,
    primitive_type_from_json/1,
    series_kind_to_string/1,
    series_kind_from_string/1,
    series_kind_to_json/1,
    series_kind_from_json/1,
    time_partition_to_string/1,
    time_partition_from_string/1,
    time_partition_to_json/1,
    time_partition_from_json/1,
    query_param_type_to_string/1,
    query_param_type_from_string/1,
    query_param_type_to_json/1,
    query_param_type_from_json/1,
    collection_to_json/2,
    collection_from_json/2,
    collection_slice_to_json/2,
    collection_slice_from_json/2,
    int_value_to_json/1,
    int_value_from_json/1,
    numeric_point_to_json/1,
    numeric_point_from_json/1,
    box_plot_point_to_json/1,
    box_plot_point_from_json/1,
    confidence_point_to_json/1,
    confidence_point_from_json/1,
    string_point_to_json/1,
    string_point_from_json/1,
    date_point_to_json/1,
    date_point_from_json/1,
    json_point_to_json/1,
    json_point_from_json/1,
    point2_d_to_json/1,
    point2_d_from_json/1,
    point3_d_to_json/1,
    point3_d_from_json/1,
    kill_point_to_json/1,
    kill_point_from_json/1,
    scatter_point_to_json/1,
    scatter_point_from_json/1,
    series_to_json/1,
    series_from_json/1,
    numeric_value_to_json/1,
    numeric_value_from_json/1,
    box_plot_series_to_json/1,
    box_plot_series_from_json/1,
    numeric_series_to_json/1,
    numeric_series_from_json/1,
    date_series_to_json/1,
    date_series_from_json/1,
    heatmap_series_to_json/1,
    heatmap_series_from_json/1,
    killmap_series_to_json/1,
    killmap_series_from_json/1,
    scatter_series_to_json/1,
    scatter_series_from_json/1,
    confidence_series_to_json/1,
    confidence_series_from_json/1,
    raw_series_to_json/1,
    raw_series_from_json/1,
    query_node_to_json/1,
    query_node_from_json/1
]).

-export_type([
    order_direction/0,
    collection/1,
    collection_slice/1,
    primitive_type/0,
    int_value/0,
    numeric_point/0,
    box_plot_point/0,
    confidence_point/0,
    string_point/0,
    date_point/0,
    json_point/0,
    point2_d/0,
    point3_d/0,
    kill_point/0,
    scatter_point/0,
    series_kind/0,
    series/0,
    numeric_value/0,
    box_plot_series/0,
    numeric_series/0,
    date_series/0,
    heatmap_series/0,
    killmap_series/0,
    scatter_series/0,
    confidence_series/0,
    raw_series/0,
    time_partition/0,
    query_param_type/0,
    query_node/0
]).

-type order_direction() :: 'asc' | 'desc'.
-type collection(_T) :: #collection{}.
-type collection_slice(_T) :: #collection_slice{}.
-type primitive_type() :: 'bool' | 'number' | 'string'.
-type int_value() :: #int_value{}.
-type numeric_point() :: #numeric_point{}.
-type box_plot_point() :: #box_plot_point{}.
-type confidence_point() :: #confidence_point{}.
-type string_point() :: #string_point{}.
-type date_point() :: #date_point{}.
-type json_point() :: #json_point{}.
-type point2_d() :: #point2_d{}.
-type point3_d() :: #point3_d{}.
-type kill_point() :: #kill_point{}.
-type scatter_point() :: #scatter_point{}.
-type series_kind() :: 'value' | 'numeric' | 'date' | 'heatmap' | 'killmap' | 'scatter' | 'confidence' | 'box_plot' | 'raw'.
-type series() :: data_protocol:numeric_value() | data_protocol:box_plot_series() | data_protocol:numeric_series() | data_protocol:date_series() | data_protocol:heatmap_series() | data_protocol:killmap_series() | data_protocol:scatter_series() | data_protocol:confidence_series() | data_protocol:raw_series().
-type numeric_value() :: #numeric_value{}.
-type box_plot_series() :: #box_plot_series{}.
-type numeric_series() :: #numeric_series{}.
-type date_series() :: #date_series{}.
-type heatmap_series() :: #heatmap_series{}.
-type killmap_series() :: #killmap_series{}.
-type scatter_series() :: #scatter_series{}.
-type confidence_series() :: #confidence_series{}.
-type raw_series() :: #raw_series{}.
-type time_partition() :: 'day' | 'week' | 'month' | 'quarter'.
-type query_param_type() :: 'boolean' | 'numeric' | 'month' | 'date' | 'date_range' | 'time_partition' | 'select'.
-type query_node() :: #query_node{}.

-spec order_direction_to_string(order_direction()) -> binary().

order_direction_to_string(asc) -> <<"asc">>;
order_direction_to_string(desc) -> <<"desc">>.

-spec order_direction_from_string(binary()) -> order_direction().

order_direction_from_string(<<"asc">>) -> asc;
order_direction_from_string(<<"desc">>) -> desc.

-spec order_direction_to_json(order_direction()) -> igor_json:json_string().

order_direction_to_json(asc) -> <<"asc">>;
order_direction_to_json(desc) -> <<"desc">>.

-spec order_direction_from_json(igor_json:json()) -> order_direction().

order_direction_from_json(<<"asc">>) -> asc;
order_direction_from_json(<<"desc">>) -> desc.

-spec primitive_type_to_string(primitive_type()) -> binary().

primitive_type_to_string(bool) -> <<"bool">>;
primitive_type_to_string(number) -> <<"number">>;
primitive_type_to_string(string) -> <<"string">>.

-spec primitive_type_from_string(binary()) -> primitive_type().

primitive_type_from_string(<<"bool">>) -> bool;
primitive_type_from_string(<<"number">>) -> number;
primitive_type_from_string(<<"string">>) -> string.

-spec primitive_type_to_json(primitive_type()) -> igor_json:json_string().

primitive_type_to_json(bool) -> <<"bool">>;
primitive_type_to_json(number) -> <<"number">>;
primitive_type_to_json(string) -> <<"string">>.

-spec primitive_type_from_json(igor_json:json()) -> primitive_type().

primitive_type_from_json(<<"bool">>) -> bool;
primitive_type_from_json(<<"number">>) -> number;
primitive_type_from_json(<<"string">>) -> string.

-spec series_kind_to_string(series_kind()) -> binary().

series_kind_to_string(value) -> <<"value">>;
series_kind_to_string(numeric) -> <<"numeric">>;
series_kind_to_string(date) -> <<"date">>;
series_kind_to_string(heatmap) -> <<"heatmap">>;
series_kind_to_string(killmap) -> <<"killmap">>;
series_kind_to_string(scatter) -> <<"scatter">>;
series_kind_to_string(confidence) -> <<"confidence">>;
series_kind_to_string(box_plot) -> <<"box_plot">>;
series_kind_to_string(raw) -> <<"raw">>.

-spec series_kind_from_string(binary()) -> series_kind().

series_kind_from_string(<<"value">>) -> value;
series_kind_from_string(<<"numeric">>) -> numeric;
series_kind_from_string(<<"date">>) -> date;
series_kind_from_string(<<"heatmap">>) -> heatmap;
series_kind_from_string(<<"killmap">>) -> killmap;
series_kind_from_string(<<"scatter">>) -> scatter;
series_kind_from_string(<<"confidence">>) -> confidence;
series_kind_from_string(<<"box_plot">>) -> box_plot;
series_kind_from_string(<<"raw">>) -> raw.

-spec series_kind_to_json(series_kind()) -> igor_json:json_string().

series_kind_to_json(value) -> <<"value">>;
series_kind_to_json(numeric) -> <<"numeric">>;
series_kind_to_json(date) -> <<"date">>;
series_kind_to_json(heatmap) -> <<"heatmap">>;
series_kind_to_json(killmap) -> <<"killmap">>;
series_kind_to_json(scatter) -> <<"scatter">>;
series_kind_to_json(confidence) -> <<"confidence">>;
series_kind_to_json(box_plot) -> <<"box_plot">>;
series_kind_to_json(raw) -> <<"raw">>.

-spec series_kind_from_json(igor_json:json()) -> series_kind().

series_kind_from_json(<<"value">>) -> value;
series_kind_from_json(<<"numeric">>) -> numeric;
series_kind_from_json(<<"date">>) -> date;
series_kind_from_json(<<"heatmap">>) -> heatmap;
series_kind_from_json(<<"killmap">>) -> killmap;
series_kind_from_json(<<"scatter">>) -> scatter;
series_kind_from_json(<<"confidence">>) -> confidence;
series_kind_from_json(<<"box_plot">>) -> box_plot;
series_kind_from_json(<<"raw">>) -> raw.

-spec time_partition_to_string(time_partition()) -> binary().

time_partition_to_string(day) -> <<"day">>;
time_partition_to_string(week) -> <<"week">>;
time_partition_to_string(month) -> <<"month">>;
time_partition_to_string(quarter) -> <<"quarter">>.

-spec time_partition_from_string(binary()) -> time_partition().

time_partition_from_string(<<"day">>) -> day;
time_partition_from_string(<<"week">>) -> week;
time_partition_from_string(<<"month">>) -> month;
time_partition_from_string(<<"quarter">>) -> quarter.

-spec time_partition_to_json(time_partition()) -> igor_json:json_string().

time_partition_to_json(day) -> <<"day">>;
time_partition_to_json(week) -> <<"week">>;
time_partition_to_json(month) -> <<"month">>;
time_partition_to_json(quarter) -> <<"quarter">>.

-spec time_partition_from_json(igor_json:json()) -> time_partition().

time_partition_from_json(<<"day">>) -> day;
time_partition_from_json(<<"week">>) -> week;
time_partition_from_json(<<"month">>) -> month;
time_partition_from_json(<<"quarter">>) -> quarter.

-spec query_param_type_to_string(query_param_type()) -> binary().

query_param_type_to_string(boolean) -> <<"boolean">>;
query_param_type_to_string(numeric) -> <<"numeric">>;
query_param_type_to_string(month) -> <<"month">>;
query_param_type_to_string(date) -> <<"date">>;
query_param_type_to_string(date_range) -> <<"date_range">>;
query_param_type_to_string(time_partition) -> <<"time_partition">>;
query_param_type_to_string(select) -> <<"select">>.

-spec query_param_type_from_string(binary()) -> query_param_type().

query_param_type_from_string(<<"boolean">>) -> boolean;
query_param_type_from_string(<<"numeric">>) -> numeric;
query_param_type_from_string(<<"month">>) -> month;
query_param_type_from_string(<<"date">>) -> date;
query_param_type_from_string(<<"date_range">>) -> date_range;
query_param_type_from_string(<<"time_partition">>) -> time_partition;
query_param_type_from_string(<<"select">>) -> select.

-spec query_param_type_to_json(query_param_type()) -> igor_json:json_string().

query_param_type_to_json(boolean) -> <<"boolean">>;
query_param_type_to_json(numeric) -> <<"numeric">>;
query_param_type_to_json(month) -> <<"month">>;
query_param_type_to_json(date) -> <<"date">>;
query_param_type_to_json(date_range) -> <<"date_range">>;
query_param_type_to_json(time_partition) -> <<"time_partition">>;
query_param_type_to_json(select) -> <<"select">>.

-spec query_param_type_from_json(igor_json:json()) -> query_param_type().

query_param_type_from_json(<<"boolean">>) -> boolean;
query_param_type_from_json(<<"numeric">>) -> numeric;
query_param_type_from_json(<<"month">>) -> month;
query_param_type_from_json(<<"date">>) -> date;
query_param_type_from_json(<<"date_range">>) -> date_range;
query_param_type_from_json(<<"time_partition">>) -> time_partition;
query_param_type_from_json(<<"select">>) -> select.

-spec collection_to_json(collection(T), igor_json:pack_type(T)) -> igor_json:json_object().

collection_to_json(Record, T) ->
    #collection{items = Items} = Record,
    ?assert(Items =/= undefined),
    #{
        <<"items">> => igor_json:pack(Items, {list, T})
    }.

-spec collection_from_json(igor_json:json_object(), igor_json:parse_type(T)) -> collection(T).

collection_from_json(Json, T) ->
    Items = igor_json:parse(Json, <<"items">>, {list, T}),
    #collection{items = Items}.

-spec collection_slice_to_json(collection_slice(T), igor_json:pack_type(T)) -> igor_json:json_object().

collection_slice_to_json(Record, T) ->
    #collection_slice{total = Total, items = Items} = Record,
    ?assert(Total =/= undefined),
    ?assert(Items =/= undefined),
    #{
        <<"total">> => igor_json:pack(Total, int),
        <<"items">> => igor_json:pack(Items, {list, T})
    }.

-spec collection_slice_from_json(igor_json:json_object(), igor_json:parse_type(T)) -> collection_slice(T).

collection_slice_from_json(Json, T) ->
    Total = igor_json:parse(Json, <<"total">>, int),
    Items = igor_json:parse(Json, <<"items">>, {list, T}),
    #collection_slice{total = Total, items = Items}.

-spec int_value_to_json(int_value()) -> igor_json:json_object().

int_value_to_json(Record) ->
    #int_value{value = VarValue} = Record,
    ?assert(VarValue =/= undefined),
    #{
        <<"value">> => igor_json:pack(VarValue, int)
    }.

-spec int_value_from_json(igor_json:json_object()) -> int_value().

int_value_from_json(Json) ->
    VarValue = igor_json:parse(Json, <<"value">>, int),
    #int_value{value = VarValue}.

-spec numeric_point_to_json(numeric_point()) -> igor_json:json_object().

numeric_point_to_json(Record) ->
    #numeric_point{label = Label, value = VarValue} = Record,
    ?assert(Label =/= undefined),
    ?assert(VarValue =/= undefined),
    #{
        <<"label">> => igor_json:pack(Label, string),
        <<"value">> => igor_json:pack(VarValue, double)
    }.

-spec numeric_point_from_json(igor_json:json_object()) -> numeric_point().

numeric_point_from_json(Json) ->
    Label = igor_json:parse(Json, <<"label">>, string),
    VarValue = igor_json:parse(Json, <<"value">>, double),
    #numeric_point{label = Label, value = VarValue}.

-spec box_plot_point_to_json(box_plot_point()) -> igor_json:json_object().

box_plot_point_to_json(Record) ->
    #box_plot_point{label = Label, value = VarValue} = Record,
    ?assert(Label =/= undefined),
    ?assert(VarValue =/= undefined),
    #{
        <<"label">> => igor_json:pack(Label, string),
        <<"value">> => igor_json:pack(VarValue, {list, double})
    }.

-spec box_plot_point_from_json(igor_json:json_object()) -> box_plot_point().

box_plot_point_from_json(Json) ->
    Label = igor_json:parse(Json, <<"label">>, string),
    VarValue = igor_json:parse(Json, <<"value">>, {list, double}),
    #box_plot_point{label = Label, value = VarValue}.

-spec confidence_point_to_json(confidence_point()) -> igor_json:json_object().

confidence_point_to_json(Record) ->
    #confidence_point{
        label = Label,
        value = VarValue,
        t_value = TValue,
        std_error = StdError
    } = Record,
    ?assert(Label =/= undefined),
    ?assert(VarValue =/= undefined),
    ?assert(TValue =/= undefined),
    ?assert(StdError =/= undefined),
    #{
        <<"label">> => igor_json:pack(Label, string),
        <<"value">> => igor_json:pack(VarValue, double),
        <<"t_value">> => igor_json:pack(TValue, double),
        <<"std_error">> => igor_json:pack(StdError, double)
    }.

-spec confidence_point_from_json(igor_json:json_object()) -> confidence_point().

confidence_point_from_json(Json) ->
    Label = igor_json:parse(Json, <<"label">>, string),
    VarValue = igor_json:parse(Json, <<"value">>, double),
    TValue = igor_json:parse(Json, <<"t_value">>, double),
    StdError = igor_json:parse(Json, <<"std_error">>, double),
    #confidence_point{
        label = Label,
        value = VarValue,
        t_value = TValue,
        std_error = StdError
    }.

-spec string_point_to_json(string_point()) -> igor_json:json_object().

string_point_to_json(Record) ->
    #string_point{label = Label, value = VarValue} = Record,
    ?assert(Label =/= undefined),
    ?assert(VarValue =/= undefined),
    #{
        <<"label">> => igor_json:pack(Label, string),
        <<"value">> => igor_json:pack(VarValue, string)
    }.

-spec string_point_from_json(igor_json:json_object()) -> string_point().

string_point_from_json(Json) ->
    Label = igor_json:parse(Json, <<"label">>, string),
    VarValue = igor_json:parse(Json, <<"value">>, string),
    #string_point{label = Label, value = VarValue}.

-spec date_point_to_json(date_point()) -> igor_json:json_object().

date_point_to_json(Record) ->
    #date_point{date = Date, count = Count} = Record,
    ?assert(Date =/= undefined),
    ?assert(Count =/= undefined),
    #{
        <<"date">> => igor_json:pack(Date, {custom, fun web_types:date_to_text/1}),
        <<"count">> => igor_json:pack(Count, int)
    }.

-spec date_point_from_json(igor_json:json_object()) -> date_point().

date_point_from_json(Json) ->
    Date = igor_json:parse(Json, <<"date">>, {custom, fun web_types:date_from_text/1}),
    Count = igor_json:parse(Json, <<"count">>, int),
    #date_point{date = Date, count = Count}.

-spec json_point_to_json(json_point()) -> igor_json:json_object().

json_point_to_json(Record) ->
    #json_point{label = Label, value = VarValue} = Record,
    ?assert(Label =/= undefined),
    ?assert(VarValue =/= undefined),
    #{
        <<"label">> => igor_json:pack(Label, string),
        <<"value">> => igor_json:pack(VarValue, json)
    }.

-spec json_point_from_json(igor_json:json_object()) -> json_point().

json_point_from_json(Json) ->
    Label = igor_json:parse(Json, <<"label">>, string),
    VarValue = igor_json:parse(Json, <<"value">>, json),
    #json_point{label = Label, value = VarValue}.

-spec point2_d_to_json(point2_d()) -> igor_json:json_object().

point2_d_to_json(Record) ->
    #point2_d{x = X, y = Y} = Record,
    ?assert(X =/= undefined),
    ?assert(Y =/= undefined),
    #{
        <<"x">> => igor_json:pack(X, double),
        <<"y">> => igor_json:pack(Y, double)
    }.

-spec point2_d_from_json(igor_json:json_object()) -> point2_d().

point2_d_from_json(Json) ->
    X = igor_json:parse(Json, <<"x">>, double),
    Y = igor_json:parse(Json, <<"y">>, double),
    #point2_d{x = X, y = Y}.

-spec point3_d_to_json(point3_d()) -> igor_json:json_object().

point3_d_to_json(Record) ->
    #point3_d{x = X, y = Y, z = Z} = Record,
    ?assert(X =/= undefined),
    ?assert(Y =/= undefined),
    ?assert(Z =/= undefined),
    #{
        <<"x">> => igor_json:pack(X, double),
        <<"y">> => igor_json:pack(Y, double),
        <<"z">> => igor_json:pack(Z, double)
    }.

-spec point3_d_from_json(igor_json:json_object()) -> point3_d().

point3_d_from_json(Json) ->
    X = igor_json:parse(Json, <<"x">>, double),
    Y = igor_json:parse(Json, <<"y">>, double),
    Z = igor_json:parse(Json, <<"z">>, double),
    #point3_d{x = X, y = Y, z = Z}.

-spec kill_point_to_json(kill_point()) -> igor_json:json_object().

kill_point_to_json(Record) ->
    #kill_point{
        killer_x = KillerX,
        killer_y = KillerY,
        killer_z = KillerZ,
        killer_team = KillerTeam,
        victim_x = VictimX,
        victim_y = VictimY,
        victim_z = VictimZ,
        victim_team = VictimTeam,
        death_reason = DeathReason,
        match_time = MatchTime
    } = Record,
    ?assert(KillerX =/= undefined),
    ?assert(KillerY =/= undefined),
    ?assert(KillerZ =/= undefined),
    ?assert(KillerTeam =/= undefined),
    ?assert(VictimX =/= undefined),
    ?assert(VictimY =/= undefined),
    ?assert(VictimZ =/= undefined),
    ?assert(VictimTeam =/= undefined),
    ?assert(DeathReason =/= undefined),
    ?assert(MatchTime =/= undefined),
    #{
        <<"killer_x">> => igor_json:pack(KillerX, double),
        <<"killer_y">> => igor_json:pack(KillerY, double),
        <<"killer_z">> => igor_json:pack(KillerZ, double),
        <<"killer_team">> => igor_json:pack(KillerTeam, string),
        <<"victim_x">> => igor_json:pack(VictimX, double),
        <<"victim_y">> => igor_json:pack(VictimY, double),
        <<"victim_z">> => igor_json:pack(VictimZ, double),
        <<"victim_team">> => igor_json:pack(VictimTeam, string),
        <<"death_reason">> => igor_json:pack(DeathReason, string),
        <<"match_time">> => igor_json:pack(MatchTime, int)
    }.

-spec kill_point_from_json(igor_json:json_object()) -> kill_point().

kill_point_from_json(Json) ->
    KillerX = igor_json:parse(Json, <<"killer_x">>, double),
    KillerY = igor_json:parse(Json, <<"killer_y">>, double),
    KillerZ = igor_json:parse(Json, <<"killer_z">>, double, 0.0),
    KillerTeam = igor_json:parse(Json, <<"killer_team">>, string),
    VictimX = igor_json:parse(Json, <<"victim_x">>, double),
    VictimY = igor_json:parse(Json, <<"victim_y">>, double),
    VictimZ = igor_json:parse(Json, <<"victim_z">>, double, 0.0),
    VictimTeam = igor_json:parse(Json, <<"victim_team">>, string),
    DeathReason = igor_json:parse(Json, <<"death_reason">>, string),
    MatchTime = igor_json:parse(Json, <<"match_time">>, int),
    #kill_point{
        killer_x = KillerX,
        killer_y = KillerY,
        killer_z = KillerZ,
        killer_team = KillerTeam,
        victim_x = VictimX,
        victim_y = VictimY,
        victim_z = VictimZ,
        victim_team = VictimTeam,
        death_reason = DeathReason,
        match_time = MatchTime
    }.

-spec scatter_point_to_json(scatter_point()) -> igor_json:json_object().

scatter_point_to_json(Record) ->
    #scatter_point{x = X, y = Y, value = VarValue} = Record,
    ?assert(X =/= undefined),
    ?assert(Y =/= undefined),
    ?assert(VarValue =/= undefined),
    #{
        <<"x">> => igor_json:pack(X, string),
        <<"y">> => igor_json:pack(Y, string),
        <<"value">> => igor_json:pack(VarValue, double)
    }.

-spec scatter_point_from_json(igor_json:json_object()) -> scatter_point().

scatter_point_from_json(Json) ->
    X = igor_json:parse(Json, <<"x">>, string),
    Y = igor_json:parse(Json, <<"y">>, string),
    VarValue = igor_json:parse(Json, <<"value">>, double),
    #scatter_point{x = X, y = Y, value = VarValue}.

-spec series_to_json(series()) -> igor_json:json_object().

series_to_json(Record) when is_record(Record, numeric_value) ->
    numeric_value_to_json(Record);
series_to_json(Record) when is_record(Record, box_plot_series) ->
    box_plot_series_to_json(Record);
series_to_json(Record) when is_record(Record, numeric_series) ->
    numeric_series_to_json(Record);
series_to_json(Record) when is_record(Record, date_series) ->
    date_series_to_json(Record);
series_to_json(Record) when is_record(Record, heatmap_series) ->
    heatmap_series_to_json(Record);
series_to_json(Record) when is_record(Record, killmap_series) ->
    killmap_series_to_json(Record);
series_to_json(Record) when is_record(Record, scatter_series) ->
    scatter_series_to_json(Record);
series_to_json(Record) when is_record(Record, confidence_series) ->
    confidence_series_to_json(Record);
series_to_json(Record) when is_record(Record, raw_series) ->
    raw_series_to_json(Record).

-spec series_from_json(igor_json:json_object()) -> series().

series_from_json(Json) ->
    Tag = igor_json:parse(Json, <<"kind">>, {custom, fun data_protocol:series_kind_from_json/1}),
    case Tag of
        value ->
            numeric_value_from_json(Json);
        box_plot ->
            box_plot_series_from_json(Json);
        numeric ->
            numeric_series_from_json(Json);
        date ->
            date_series_from_json(Json);
        heatmap ->
            heatmap_series_from_json(Json);
        killmap ->
            killmap_series_from_json(Json);
        scatter ->
            scatter_series_from_json(Json);
        confidence ->
            confidence_series_from_json(Json);
        raw ->
            raw_series_from_json(Json)
    end.

-spec numeric_value_to_json(numeric_value()) -> igor_json:json_object().

numeric_value_to_json(Record) ->
    #numeric_value{key = VarKey, data = Data} = Record,
    ?assert(Data =/= undefined),
    #{
        <<"kind">> => igor_json:pack(value, {custom, fun data_protocol:series_kind_to_json/1}),
        <<"key">> => igor_json:pack(VarKey, string),
        <<"data">> => igor_json:pack(Data, {custom, fun data_protocol:numeric_point_to_json/1})
    }.

-spec numeric_value_from_json(igor_json:json_object()) -> numeric_value().

numeric_value_from_json(Json) ->
    VarKey = igor_json:parse(Json, <<"key">>, string, undefined),
    Data = igor_json:parse(Json, <<"data">>, {custom, fun data_protocol:numeric_point_from_json/1}),
    #numeric_value{key = VarKey, data = Data}.

-spec box_plot_series_to_json(box_plot_series()) -> igor_json:json_object().

box_plot_series_to_json(Record) ->
    #box_plot_series{key = VarKey, data = Data} = Record,
    ?assert(Data =/= undefined),
    #{
        <<"kind">> => igor_json:pack(box_plot, {custom, fun data_protocol:series_kind_to_json/1}),
        <<"key">> => igor_json:pack(VarKey, string),
        <<"data">> => igor_json:pack(Data, {list, {custom, fun data_protocol:box_plot_point_to_json/1}})
    }.

-spec box_plot_series_from_json(igor_json:json_object()) -> box_plot_series().

box_plot_series_from_json(Json) ->
    VarKey = igor_json:parse(Json, <<"key">>, string, undefined),
    Data = igor_json:parse(Json, <<"data">>, {list, {custom, fun data_protocol:box_plot_point_from_json/1}}),
    #box_plot_series{key = VarKey, data = Data}.

-spec numeric_series_to_json(numeric_series()) -> igor_json:json_object().

numeric_series_to_json(Record) ->
    #numeric_series{key = VarKey, data = Data} = Record,
    ?assert(Data =/= undefined),
    #{
        <<"kind">> => igor_json:pack(numeric, {custom, fun data_protocol:series_kind_to_json/1}),
        <<"key">> => igor_json:pack(VarKey, string),
        <<"data">> => igor_json:pack(Data, {list, {custom, fun data_protocol:numeric_point_to_json/1}})
    }.

-spec numeric_series_from_json(igor_json:json_object()) -> numeric_series().

numeric_series_from_json(Json) ->
    VarKey = igor_json:parse(Json, <<"key">>, string, undefined),
    Data = igor_json:parse(Json, <<"data">>, {list, {custom, fun data_protocol:numeric_point_from_json/1}}),
    #numeric_series{key = VarKey, data = Data}.

-spec date_series_to_json(date_series()) -> igor_json:json_object().

date_series_to_json(Record) ->
    #date_series{key = VarKey, data = Data} = Record,
    ?assert(Data =/= undefined),
    #{
        <<"kind">> => igor_json:pack(date, {custom, fun data_protocol:series_kind_to_json/1}),
        <<"key">> => igor_json:pack(VarKey, string),
        <<"data">> => igor_json:pack(Data, {list, {custom, fun data_protocol:date_point_to_json/1}})
    }.

-spec date_series_from_json(igor_json:json_object()) -> date_series().

date_series_from_json(Json) ->
    VarKey = igor_json:parse(Json, <<"key">>, string, undefined),
    Data = igor_json:parse(Json, <<"data">>, {list, {custom, fun data_protocol:date_point_from_json/1}}),
    #date_series{key = VarKey, data = Data}.

-spec heatmap_series_to_json(heatmap_series()) -> igor_json:json_object().

heatmap_series_to_json(Record) ->
    #heatmap_series{key = VarKey, maps = Maps, data = Data} = Record,
    ?assert(Maps =/= undefined),
    ?assert(Data =/= undefined),
    #{
        <<"kind">> => igor_json:pack(heatmap, {custom, fun data_protocol:series_kind_to_json/1}),
        <<"key">> => igor_json:pack(VarKey, string),
        <<"maps">> => igor_json:pack(Maps, {list, string}),
        <<"data">> => igor_json:pack(Data, {list, {custom, fun data_protocol:point2_d_to_json/1}})
    }.

-spec heatmap_series_from_json(igor_json:json_object()) -> heatmap_series().

heatmap_series_from_json(Json) ->
    VarKey = igor_json:parse(Json, <<"key">>, string, undefined),
    Maps = igor_json:parse(Json, <<"maps">>, {list, string}, []),
    Data = igor_json:parse(Json, <<"data">>, {list, {custom, fun data_protocol:point2_d_from_json/1}}),
    #heatmap_series{key = VarKey, maps = Maps, data = Data}.

-spec killmap_series_to_json(killmap_series()) -> igor_json:json_object().

killmap_series_to_json(Record) ->
    #killmap_series{key = VarKey, map = Map, data = Data} = Record,
    ?assert(Map =/= undefined),
    ?assert(Data =/= undefined),
    #{
        <<"kind">> => igor_json:pack(killmap, {custom, fun data_protocol:series_kind_to_json/1}),
        <<"key">> => igor_json:pack(VarKey, string),
        <<"map">> => igor_json:pack(Map, string),
        <<"data">> => igor_json:pack(Data, {list, {custom, fun data_protocol:kill_point_to_json/1}})
    }.

-spec killmap_series_from_json(igor_json:json_object()) -> killmap_series().

killmap_series_from_json(Json) ->
    VarKey = igor_json:parse(Json, <<"key">>, string, undefined),
    Map = igor_json:parse(Json, <<"map">>, string),
    Data = igor_json:parse(Json, <<"data">>, {list, {custom, fun data_protocol:kill_point_from_json/1}}),
    #killmap_series{key = VarKey, map = Map, data = Data}.

-spec scatter_series_to_json(scatter_series()) -> igor_json:json_object().

scatter_series_to_json(Record) ->
    #scatter_series{key = VarKey, data = Data} = Record,
    ?assert(Data =/= undefined),
    #{
        <<"kind">> => igor_json:pack(scatter, {custom, fun data_protocol:series_kind_to_json/1}),
        <<"key">> => igor_json:pack(VarKey, string),
        <<"data">> => igor_json:pack(Data, {list, {custom, fun data_protocol:scatter_point_to_json/1}})
    }.

-spec scatter_series_from_json(igor_json:json_object()) -> scatter_series().

scatter_series_from_json(Json) ->
    VarKey = igor_json:parse(Json, <<"key">>, string, undefined),
    Data = igor_json:parse(Json, <<"data">>, {list, {custom, fun data_protocol:scatter_point_from_json/1}}),
    #scatter_series{key = VarKey, data = Data}.

-spec confidence_series_to_json(confidence_series()) -> igor_json:json_object().

confidence_series_to_json(Record) ->
    #confidence_series{key = VarKey, data = Data} = Record,
    ?assert(Data =/= undefined),
    #{
        <<"kind">> => igor_json:pack(confidence, {custom, fun data_protocol:series_kind_to_json/1}),
        <<"key">> => igor_json:pack(VarKey, string),
        <<"data">> => igor_json:pack(Data, {list, {custom, fun data_protocol:confidence_point_to_json/1}})
    }.

-spec confidence_series_from_json(igor_json:json_object()) -> confidence_series().

confidence_series_from_json(Json) ->
    VarKey = igor_json:parse(Json, <<"key">>, string, undefined),
    Data = igor_json:parse(Json, <<"data">>, {list, {custom, fun data_protocol:confidence_point_from_json/1}}),
    #confidence_series{key = VarKey, data = Data}.

-spec raw_series_to_json(raw_series()) -> igor_json:json_object().

raw_series_to_json(Record) ->
    #raw_series{key = VarKey, data = Data} = Record,
    ?assert(Data =/= undefined),
    #{
        <<"kind">> => igor_json:pack(raw, {custom, fun data_protocol:series_kind_to_json/1}),
        <<"key">> => igor_json:pack(VarKey, string),
        <<"data">> => igor_json:pack(Data, {list, json})
    }.

-spec raw_series_from_json(igor_json:json_object()) -> raw_series().

raw_series_from_json(Json) ->
    VarKey = igor_json:parse(Json, <<"key">>, string, undefined),
    Data = igor_json:parse(Json, <<"data">>, {list, json}),
    #raw_series{key = VarKey, data = Data}.

-spec query_node_to_json(query_node()) -> igor_json:json_object().

query_node_to_json(Record) ->
    #query_node{input_sql = InputSql, output = Output} = Record,
    ?assert(InputSql =/= undefined),
    ?assert(Output =/= undefined),
    #{
        <<"input_sql">> => igor_json:pack(InputSql, string),
        <<"output">> => igor_json:pack(Output, {custom, fun visualization_protocol:visualization_to_json/1})
    }.

-spec query_node_from_json(igor_json:json_object()) -> query_node().

query_node_from_json(Json) ->
    InputSql = igor_json:parse(Json, <<"input_sql">>, string),
    Output = igor_json:parse(Json, <<"output">>, {custom, fun visualization_protocol:visualization_from_json/1}),
    #query_node{input_sql = InputSql, output = Output}.

