%% @author Igor compiler
%% @doc Compiler version: igorc 2.1.4
%% DO NOT EDIT THIS FILE - it is machine generated

-module(visualization_protocol).

-include_lib("stdlib/include/assert.hrl").
-include("visualization_protocol.hrl").

-export([
    axis_kind_y_to_string/1,
    axis_kind_y_from_string/1,
    axis_kind_y_to_json/1,
    axis_kind_y_from_json/1,
    axis_value_type_to_string/1,
    axis_value_type_from_string/1,
    axis_value_type_to_json/1,
    axis_value_type_from_json/1,
    chart_type_to_string/1,
    chart_type_from_string/1,
    chart_type_to_json/1,
    chart_type_from_json/1,
    visualization_kind_to_string/1,
    visualization_kind_from_string/1,
    visualization_kind_to_json/1,
    visualization_kind_from_json/1,
    simple_serie_to_json/1,
    simple_serie_from_json/1,
    chart_serie_to_json/1,
    chart_serie_from_json/1,
    scatter_serie_to_json/1,
    scatter_serie_from_json/1,
    visualization_to_json/1,
    visualization_from_json/1,
    visualization_indicator_to_json/1,
    visualization_indicator_from_json/1,
    visualization_common_plot_to_json/1,
    visualization_common_plot_from_json/1,
    visualization_synchronized_plot_to_json/1,
    visualization_synchronized_plot_from_json/1,
    visualization_horizontal_bars_to_json/1,
    visualization_horizontal_bars_from_json/1,
    visualization_funnel_to_json/1,
    visualization_funnel_from_json/1,
    visualization_heatmap_to_json/1,
    visualization_heatmap_from_json/1,
    visualization_killmap_to_json/1,
    visualization_killmap_from_json/1,
    visualization_scatter_to_json/1,
    visualization_scatter_from_json/1,
    visualization_box_plot_to_json/1,
    visualization_box_plot_from_json/1,
    visualization_raw_to_json/1,
    visualization_raw_from_json/1
]).

-export_type([
    axis_kind_y/0,
    axis_value_type/0,
    chart_type/0,
    simple_serie/0,
    chart_serie/0,
    scatter_serie/0,
    visualization_kind/0,
    visualization/0,
    visualization_indicator/0,
    visualization_common_plot/0,
    visualization_synchronized_plot/0,
    visualization_horizontal_bars/0,
    visualization_funnel/0,
    visualization_heatmap/0,
    visualization_killmap/0,
    visualization_scatter/0,
    visualization_box_plot/0,
    visualization_raw/0
]).

-type axis_kind_y() :: 'primary' | 'secondary'.
-type axis_value_type() :: 'numeric' | 'date' | 'text'.
-type chart_type() :: 'line' | 'spline' | 'area' | 'area_spline' | 'vertical_bar' | 'confidence'.
-type simple_serie() :: #simple_serie{}.
-type chart_serie() :: #chart_serie{}.
-type scatter_serie() :: #scatter_serie{}.
-type visualization_kind() :: 'indicator' | 'common_plot' | 'synchronized_plot' | 'horizontal_bars' | 'funnel' | 'heatmap' | 'killmap' | 'scatter' | 'box_plot' | 'raw'.
-type visualization() :: visualization_protocol:visualization_indicator() | visualization_protocol:visualization_common_plot() | visualization_protocol:visualization_synchronized_plot() | visualization_protocol:visualization_horizontal_bars() | visualization_protocol:visualization_funnel() | visualization_protocol:visualization_heatmap() | visualization_protocol:visualization_killmap() | visualization_protocol:visualization_scatter() | visualization_protocol:visualization_box_plot() | visualization_protocol:visualization_raw().
-type visualization_indicator() :: #visualization_indicator{}.
-type visualization_common_plot() :: #visualization_common_plot{}.
-type visualization_synchronized_plot() :: #visualization_synchronized_plot{}.
-type visualization_horizontal_bars() :: #visualization_horizontal_bars{}.
-type visualization_funnel() :: #visualization_funnel{}.
-type visualization_heatmap() :: #visualization_heatmap{}.
-type visualization_killmap() :: #visualization_killmap{}.
-type visualization_scatter() :: #visualization_scatter{}.
-type visualization_box_plot() :: #visualization_box_plot{}.
-type visualization_raw() :: #visualization_raw{}.

-spec axis_kind_y_to_string(axis_kind_y()) -> binary().

axis_kind_y_to_string(primary) -> <<"primary">>;
axis_kind_y_to_string(secondary) -> <<"secondary">>.

-spec axis_kind_y_from_string(binary()) -> axis_kind_y().

axis_kind_y_from_string(<<"primary">>) -> primary;
axis_kind_y_from_string(<<"secondary">>) -> secondary.

-spec axis_kind_y_to_json(axis_kind_y()) -> igor_json:json_string().

axis_kind_y_to_json(primary) -> <<"primary">>;
axis_kind_y_to_json(secondary) -> <<"secondary">>.

-spec axis_kind_y_from_json(igor_json:json()) -> axis_kind_y().

axis_kind_y_from_json(<<"primary">>) -> primary;
axis_kind_y_from_json(<<"secondary">>) -> secondary.

-spec axis_value_type_to_string(axis_value_type()) -> binary().

axis_value_type_to_string(numeric) -> <<"numeric">>;
axis_value_type_to_string(date) -> <<"date">>;
axis_value_type_to_string(text) -> <<"text">>.

-spec axis_value_type_from_string(binary()) -> axis_value_type().

axis_value_type_from_string(<<"numeric">>) -> numeric;
axis_value_type_from_string(<<"date">>) -> date;
axis_value_type_from_string(<<"text">>) -> text.

-spec axis_value_type_to_json(axis_value_type()) -> igor_json:json_string().

axis_value_type_to_json(numeric) -> <<"numeric">>;
axis_value_type_to_json(date) -> <<"date">>;
axis_value_type_to_json(text) -> <<"text">>.

-spec axis_value_type_from_json(igor_json:json()) -> axis_value_type().

axis_value_type_from_json(<<"numeric">>) -> numeric;
axis_value_type_from_json(<<"date">>) -> date;
axis_value_type_from_json(<<"text">>) -> text.

-spec chart_type_to_string(chart_type()) -> binary().

chart_type_to_string(line) -> <<"line">>;
chart_type_to_string(spline) -> <<"spline">>;
chart_type_to_string(area) -> <<"area">>;
chart_type_to_string(area_spline) -> <<"area_spline">>;
chart_type_to_string(vertical_bar) -> <<"vertical_bar">>;
chart_type_to_string(confidence) -> <<"confidence">>.

-spec chart_type_from_string(binary()) -> chart_type().

chart_type_from_string(<<"line">>) -> line;
chart_type_from_string(<<"spline">>) -> spline;
chart_type_from_string(<<"area">>) -> area;
chart_type_from_string(<<"area_spline">>) -> area_spline;
chart_type_from_string(<<"vertical_bar">>) -> vertical_bar;
chart_type_from_string(<<"confidence">>) -> confidence.

-spec chart_type_to_json(chart_type()) -> igor_json:json_string().

chart_type_to_json(line) -> <<"line">>;
chart_type_to_json(spline) -> <<"spline">>;
chart_type_to_json(area) -> <<"area">>;
chart_type_to_json(area_spline) -> <<"area_spline">>;
chart_type_to_json(vertical_bar) -> <<"vertical_bar">>;
chart_type_to_json(confidence) -> <<"confidence">>.

-spec chart_type_from_json(igor_json:json()) -> chart_type().

chart_type_from_json(<<"line">>) -> line;
chart_type_from_json(<<"spline">>) -> spline;
chart_type_from_json(<<"area">>) -> area;
chart_type_from_json(<<"area_spline">>) -> area_spline;
chart_type_from_json(<<"vertical_bar">>) -> vertical_bar;
chart_type_from_json(<<"confidence">>) -> confidence.

-spec visualization_kind_to_string(visualization_kind()) -> binary().

visualization_kind_to_string(indicator) -> <<"indicator">>;
visualization_kind_to_string(common_plot) -> <<"common_plot">>;
visualization_kind_to_string(synchronized_plot) -> <<"synchronized_plot">>;
visualization_kind_to_string(horizontal_bars) -> <<"horizontal_bars">>;
visualization_kind_to_string(funnel) -> <<"funnel">>;
visualization_kind_to_string(heatmap) -> <<"heatmap">>;
visualization_kind_to_string(killmap) -> <<"killmap">>;
visualization_kind_to_string(scatter) -> <<"scatter">>;
visualization_kind_to_string(box_plot) -> <<"box_plot">>;
visualization_kind_to_string(raw) -> <<"raw">>.

-spec visualization_kind_from_string(binary()) -> visualization_kind().

visualization_kind_from_string(<<"indicator">>) -> indicator;
visualization_kind_from_string(<<"common_plot">>) -> common_plot;
visualization_kind_from_string(<<"synchronized_plot">>) -> synchronized_plot;
visualization_kind_from_string(<<"horizontal_bars">>) -> horizontal_bars;
visualization_kind_from_string(<<"funnel">>) -> funnel;
visualization_kind_from_string(<<"heatmap">>) -> heatmap;
visualization_kind_from_string(<<"killmap">>) -> killmap;
visualization_kind_from_string(<<"scatter">>) -> scatter;
visualization_kind_from_string(<<"box_plot">>) -> box_plot;
visualization_kind_from_string(<<"raw">>) -> raw.

-spec visualization_kind_to_json(visualization_kind()) -> igor_json:json_string().

visualization_kind_to_json(indicator) -> <<"indicator">>;
visualization_kind_to_json(common_plot) -> <<"common_plot">>;
visualization_kind_to_json(synchronized_plot) -> <<"synchronized_plot">>;
visualization_kind_to_json(horizontal_bars) -> <<"horizontal_bars">>;
visualization_kind_to_json(funnel) -> <<"funnel">>;
visualization_kind_to_json(heatmap) -> <<"heatmap">>;
visualization_kind_to_json(killmap) -> <<"killmap">>;
visualization_kind_to_json(scatter) -> <<"scatter">>;
visualization_kind_to_json(box_plot) -> <<"box_plot">>;
visualization_kind_to_json(raw) -> <<"raw">>.

-spec visualization_kind_from_json(igor_json:json()) -> visualization_kind().

visualization_kind_from_json(<<"indicator">>) -> indicator;
visualization_kind_from_json(<<"common_plot">>) -> common_plot;
visualization_kind_from_json(<<"synchronized_plot">>) -> synchronized_plot;
visualization_kind_from_json(<<"horizontal_bars">>) -> horizontal_bars;
visualization_kind_from_json(<<"funnel">>) -> funnel;
visualization_kind_from_json(<<"heatmap">>) -> heatmap;
visualization_kind_from_json(<<"killmap">>) -> killmap;
visualization_kind_from_json(<<"scatter">>) -> scatter;
visualization_kind_from_json(<<"box_plot">>) -> box_plot;
visualization_kind_from_json(<<"raw">>) -> raw.

-spec simple_serie_to_json(simple_serie()) -> igor_json:json_object().

simple_serie_to_json(Record) ->
    #simple_serie{name = Name, key = VarKey} = Record,
    #{
        <<"name">> => igor_json:pack(Name, string),
        <<"key">> => igor_json:pack(VarKey, string)
    }.

-spec simple_serie_from_json(igor_json:json_object()) -> simple_serie().

simple_serie_from_json(Json) ->
    Name = igor_json:parse(Json, <<"name">>, string, undefined),
    VarKey = igor_json:parse(Json, <<"key">>, string, undefined),
    #simple_serie{name = Name, key = VarKey}.

-spec chart_serie_to_json(chart_serie()) -> igor_json:json_object().

chart_serie_to_json(Record) ->
    #chart_serie{
        name = Name,
        key = VarKey,
        group_index = GroupIndex,
        color = Color,
        chart_type = ChartType,
        y_axis = YAxis,
        show_values = ShowValues
    } = Record,
    ?assert(ChartType =/= undefined),
    ?assert(YAxis =/= undefined),
    ?assert(ShowValues =/= undefined),
    #{
        <<"name">> => igor_json:pack(Name, string),
        <<"key">> => igor_json:pack(VarKey, string),
        <<"group_index">> => igor_json:pack(GroupIndex, int),
        <<"color">> => igor_json:pack(Color, string),
        <<"chart_type">> => igor_json:pack(ChartType, {custom, fun visualization_protocol:chart_type_to_json/1}),
        <<"y_axis">> => igor_json:pack(YAxis, {custom, fun visualization_protocol:axis_kind_y_to_json/1}),
        <<"show_values">> => igor_json:pack(ShowValues, boolean)
    }.

-spec chart_serie_from_json(igor_json:json_object()) -> chart_serie().

chart_serie_from_json(Json) ->
    Name = igor_json:parse(Json, <<"name">>, string, undefined),
    VarKey = igor_json:parse(Json, <<"key">>, string, undefined),
    GroupIndex = igor_json:parse(Json, <<"group_index">>, int, undefined),
    Color = igor_json:parse(Json, <<"color">>, string, undefined),
    ChartType = igor_json:parse(Json, <<"chart_type">>, {custom, fun visualization_protocol:chart_type_from_json/1}),
    YAxis = igor_json:parse(Json, <<"y_axis">>, {custom, fun visualization_protocol:axis_kind_y_from_json/1}, primary),
    ShowValues = igor_json:parse(Json, <<"show_values">>, boolean, true),
    #chart_serie{
        name = Name,
        key = VarKey,
        group_index = GroupIndex,
        color = Color,
        chart_type = ChartType,
        y_axis = YAxis,
        show_values = ShowValues
    }.

-spec scatter_serie_to_json(scatter_serie()) -> igor_json:json_object().

scatter_serie_to_json(Record) ->
    #scatter_serie{
        name = Name,
        key = VarKey,
        color = Color,
        radius = Radius
    } = Record,
    #{
        <<"name">> => igor_json:pack(Name, string),
        <<"key">> => igor_json:pack(VarKey, string),
        <<"color">> => igor_json:pack(Color, string),
        <<"radius">> => igor_json:pack(Radius, double)
    }.

-spec scatter_serie_from_json(igor_json:json_object()) -> scatter_serie().

scatter_serie_from_json(Json) ->
    Name = igor_json:parse(Json, <<"name">>, string, undefined),
    VarKey = igor_json:parse(Json, <<"key">>, string, undefined),
    Color = igor_json:parse(Json, <<"color">>, string, undefined),
    Radius = igor_json:parse(Json, <<"radius">>, double, undefined),
    #scatter_serie{
        name = Name,
        key = VarKey,
        color = Color,
        radius = Radius
    }.

-spec visualization_to_json(visualization()) -> igor_json:json_object().

visualization_to_json(Record) when is_record(Record, visualization_indicator) ->
    visualization_indicator_to_json(Record);
visualization_to_json(Record) when is_record(Record, visualization_common_plot) ->
    visualization_common_plot_to_json(Record);
visualization_to_json(Record) when is_record(Record, visualization_synchronized_plot) ->
    visualization_synchronized_plot_to_json(Record);
visualization_to_json(Record) when is_record(Record, visualization_horizontal_bars) ->
    visualization_horizontal_bars_to_json(Record);
visualization_to_json(Record) when is_record(Record, visualization_funnel) ->
    visualization_funnel_to_json(Record);
visualization_to_json(Record) when is_record(Record, visualization_heatmap) ->
    visualization_heatmap_to_json(Record);
visualization_to_json(Record) when is_record(Record, visualization_killmap) ->
    visualization_killmap_to_json(Record);
visualization_to_json(Record) when is_record(Record, visualization_scatter) ->
    visualization_scatter_to_json(Record);
visualization_to_json(Record) when is_record(Record, visualization_box_plot) ->
    visualization_box_plot_to_json(Record);
visualization_to_json(Record) when is_record(Record, visualization_raw) ->
    visualization_raw_to_json(Record).

-spec visualization_from_json(igor_json:json_object()) -> visualization().

visualization_from_json(Json) ->
    Tag = igor_json:parse(Json, <<"kind">>, {custom, fun visualization_protocol:visualization_kind_from_json/1}),
    case Tag of
        indicator ->
            visualization_indicator_from_json(Json);
        common_plot ->
            visualization_common_plot_from_json(Json);
        synchronized_plot ->
            visualization_synchronized_plot_from_json(Json);
        horizontal_bars ->
            visualization_horizontal_bars_from_json(Json);
        funnel ->
            visualization_funnel_from_json(Json);
        heatmap ->
            visualization_heatmap_from_json(Json);
        killmap ->
            visualization_killmap_from_json(Json);
        scatter ->
            visualization_scatter_from_json(Json);
        box_plot ->
            visualization_box_plot_from_json(Json);
        raw ->
            visualization_raw_from_json(Json)
    end.

-spec visualization_indicator_to_json(visualization_indicator()) -> igor_json:json_object().

visualization_indicator_to_json(Record) ->
    #visualization_indicator{
        name = Name,
        subtitle = Subtitle,
        description = Description,
        label = Label
    } = Record,
    ?assert(Name =/= undefined),
    ?assert(Description =/= undefined),
    ?assert(Label =/= undefined),
    #{
        <<"kind">> => igor_json:pack(indicator, {custom, fun visualization_protocol:visualization_kind_to_json/1}),
        <<"name">> => igor_json:pack(Name, string),
        <<"subtitle">> => igor_json:pack(Subtitle, string),
        <<"description">> => igor_json:pack(Description, string),
        <<"label">> => igor_json:pack(Label, string)
    }.

-spec visualization_indicator_from_json(igor_json:json_object()) -> visualization_indicator().

visualization_indicator_from_json(Json) ->
    Name = igor_json:parse(Json, <<"name">>, string),
    Subtitle = igor_json:parse(Json, <<"subtitle">>, string, undefined),
    Description = igor_json:parse(Json, <<"description">>, string),
    Label = igor_json:parse(Json, <<"label">>, string),
    #visualization_indicator{
        name = Name,
        subtitle = Subtitle,
        description = Description,
        label = Label
    }.

-spec visualization_common_plot_to_json(visualization_common_plot()) -> igor_json:json_object().

visualization_common_plot_to_json(Record) ->
    #visualization_common_plot{
        name = Name,
        subtitle = Subtitle,
        description = Description,
        series = Series,
        show_x_axis = ShowXAxis,
        show_y_axis = ShowYAxis,
        show_x_grid_line = ShowXGridLine,
        show_y_grid_line = ShowYGridLine,
        x_axis_type = XAxisType,
        y_axis_type = YAxisType,
        x_axis_title = XAxisTitle,
        y_axis_title = YAxisTitle,
        secondary_y_axis_title = SecondaryYAxisTitle,
        secondary_y_axis_type = SecondaryYAxisType,
        show_timeline = ShowTimeline,
        show_legend = ShowLegend,
        show_estimate = ShowEstimate
    } = Record,
    ?assert(Name =/= undefined),
    ?assert(Description =/= undefined),
    ?assert(Series =/= undefined),
    ?assert(ShowXAxis =/= undefined),
    ?assert(ShowYAxis =/= undefined),
    ?assert(ShowXGridLine =/= undefined),
    ?assert(ShowYGridLine =/= undefined),
    ?assert(XAxisType =/= undefined),
    ?assert(YAxisType =/= undefined),
    ?assert(XAxisTitle =/= undefined),
    ?assert(YAxisTitle =/= undefined),
    ?assert(ShowTimeline =/= undefined),
    ?assert(ShowLegend =/= undefined),
    ?assert(ShowEstimate =/= undefined),
    #{
        <<"kind">> => igor_json:pack(common_plot, {custom, fun visualization_protocol:visualization_kind_to_json/1}),
        <<"name">> => igor_json:pack(Name, string),
        <<"subtitle">> => igor_json:pack(Subtitle, string),
        <<"description">> => igor_json:pack(Description, string),
        <<"series">> => igor_json:pack(Series, {list, {custom, fun visualization_protocol:chart_serie_to_json/1}}),
        <<"show_x_axis">> => igor_json:pack(ShowXAxis, boolean),
        <<"show_y_axis">> => igor_json:pack(ShowYAxis, boolean),
        <<"show_x_grid_line">> => igor_json:pack(ShowXGridLine, boolean),
        <<"show_y_grid_line">> => igor_json:pack(ShowYGridLine, boolean),
        <<"x_axis_type">> => igor_json:pack(XAxisType, {custom, fun visualization_protocol:axis_value_type_to_json/1}),
        <<"y_axis_type">> => igor_json:pack(YAxisType, {custom, fun visualization_protocol:axis_value_type_to_json/1}),
        <<"x_axis_title">> => igor_json:pack(XAxisTitle, string),
        <<"y_axis_title">> => igor_json:pack(YAxisTitle, string),
        <<"secondary_y_axis_title">> => igor_json:pack(SecondaryYAxisTitle, string),
        <<"secondary_y_axis_type">> => igor_json:pack(SecondaryYAxisType, {custom, fun visualization_protocol:axis_value_type_to_json/1}),
        <<"show_timeline">> => igor_json:pack(ShowTimeline, boolean),
        <<"show_legend">> => igor_json:pack(ShowLegend, boolean),
        <<"show_estimate">> => igor_json:pack(ShowEstimate, boolean)
    }.

-spec visualization_common_plot_from_json(igor_json:json_object()) -> visualization_common_plot().

visualization_common_plot_from_json(Json) ->
    Name = igor_json:parse(Json, <<"name">>, string),
    Subtitle = igor_json:parse(Json, <<"subtitle">>, string, undefined),
    Description = igor_json:parse(Json, <<"description">>, string),
    Series = igor_json:parse(Json, <<"series">>, {list, {custom, fun visualization_protocol:chart_serie_from_json/1}}),
    ShowXAxis = igor_json:parse(Json, <<"show_x_axis">>, boolean, true),
    ShowYAxis = igor_json:parse(Json, <<"show_y_axis">>, boolean, true),
    ShowXGridLine = igor_json:parse(Json, <<"show_x_grid_line">>, boolean, true),
    ShowYGridLine = igor_json:parse(Json, <<"show_y_grid_line">>, boolean, true),
    XAxisType = igor_json:parse(Json, <<"x_axis_type">>, {custom, fun visualization_protocol:axis_value_type_from_json/1}),
    YAxisType = igor_json:parse(Json, <<"y_axis_type">>, {custom, fun visualization_protocol:axis_value_type_from_json/1}),
    XAxisTitle = igor_json:parse(Json, <<"x_axis_title">>, string, <<"">>),
    YAxisTitle = igor_json:parse(Json, <<"y_axis_title">>, string, <<"">>),
    SecondaryYAxisTitle = igor_json:parse(Json, <<"secondary_y_axis_title">>, string, undefined),
    SecondaryYAxisType = igor_json:parse(Json, <<"secondary_y_axis_type">>, {custom, fun visualization_protocol:axis_value_type_from_json/1}, undefined),
    ShowTimeline = igor_json:parse(Json, <<"show_timeline">>, boolean, false),
    ShowLegend = igor_json:parse(Json, <<"show_legend">>, boolean, true),
    ShowEstimate = igor_json:parse(Json, <<"show_estimate">>, boolean, false),
    #visualization_common_plot{
        name = Name,
        subtitle = Subtitle,
        description = Description,
        series = Series,
        show_x_axis = ShowXAxis,
        show_y_axis = ShowYAxis,
        show_x_grid_line = ShowXGridLine,
        show_y_grid_line = ShowYGridLine,
        x_axis_type = XAxisType,
        y_axis_type = YAxisType,
        x_axis_title = XAxisTitle,
        y_axis_title = YAxisTitle,
        secondary_y_axis_title = SecondaryYAxisTitle,
        secondary_y_axis_type = SecondaryYAxisType,
        show_timeline = ShowTimeline,
        show_legend = ShowLegend,
        show_estimate = ShowEstimate
    }.

-spec visualization_synchronized_plot_to_json(visualization_synchronized_plot()) -> igor_json:json_object().

visualization_synchronized_plot_to_json(Record) ->
    #visualization_synchronized_plot{
        name = Name,
        subtitle = Subtitle,
        description = Description,
        series = Series,
        show_x_axis = ShowXAxis,
        show_y_axis = ShowYAxis,
        show_x_grid_line = ShowXGridLine,
        show_y_grid_line = ShowYGridLine,
        x_axis_type = XAxisType,
        y_axis_type = YAxisType,
        x_axis_title = XAxisTitle,
        y_axis_title = YAxisTitle,
        secondary_y_axis_title = SecondaryYAxisTitle,
        secondary_y_axis_type = SecondaryYAxisType,
        show_timeline = ShowTimeline,
        show_legend = ShowLegend
    } = Record,
    ?assert(Name =/= undefined),
    ?assert(Description =/= undefined),
    ?assert(Series =/= undefined),
    ?assert(ShowXAxis =/= undefined),
    ?assert(ShowYAxis =/= undefined),
    ?assert(ShowXGridLine =/= undefined),
    ?assert(ShowYGridLine =/= undefined),
    ?assert(XAxisType =/= undefined),
    ?assert(YAxisType =/= undefined),
    ?assert(XAxisTitle =/= undefined),
    ?assert(YAxisTitle =/= undefined),
    ?assert(ShowTimeline =/= undefined),
    ?assert(ShowLegend =/= undefined),
    #{
        <<"kind">> => igor_json:pack(synchronized_plot, {custom, fun visualization_protocol:visualization_kind_to_json/1}),
        <<"name">> => igor_json:pack(Name, string),
        <<"subtitle">> => igor_json:pack(Subtitle, string),
        <<"description">> => igor_json:pack(Description, string),
        <<"series">> => igor_json:pack(Series, {list, {custom, fun visualization_protocol:chart_serie_to_json/1}}),
        <<"show_x_axis">> => igor_json:pack(ShowXAxis, boolean),
        <<"show_y_axis">> => igor_json:pack(ShowYAxis, boolean),
        <<"show_x_grid_line">> => igor_json:pack(ShowXGridLine, boolean),
        <<"show_y_grid_line">> => igor_json:pack(ShowYGridLine, boolean),
        <<"x_axis_type">> => igor_json:pack(XAxisType, {custom, fun visualization_protocol:axis_value_type_to_json/1}),
        <<"y_axis_type">> => igor_json:pack(YAxisType, {custom, fun visualization_protocol:axis_value_type_to_json/1}),
        <<"x_axis_title">> => igor_json:pack(XAxisTitle, string),
        <<"y_axis_title">> => igor_json:pack(YAxisTitle, string),
        <<"secondary_y_axis_title">> => igor_json:pack(SecondaryYAxisTitle, string),
        <<"secondary_y_axis_type">> => igor_json:pack(SecondaryYAxisType, {custom, fun visualization_protocol:axis_value_type_to_json/1}),
        <<"show_timeline">> => igor_json:pack(ShowTimeline, boolean),
        <<"show_legend">> => igor_json:pack(ShowLegend, boolean)
    }.

-spec visualization_synchronized_plot_from_json(igor_json:json_object()) -> visualization_synchronized_plot().

visualization_synchronized_plot_from_json(Json) ->
    Name = igor_json:parse(Json, <<"name">>, string),
    Subtitle = igor_json:parse(Json, <<"subtitle">>, string, undefined),
    Description = igor_json:parse(Json, <<"description">>, string),
    Series = igor_json:parse(Json, <<"series">>, {list, {custom, fun visualization_protocol:chart_serie_from_json/1}}),
    ShowXAxis = igor_json:parse(Json, <<"show_x_axis">>, boolean, true),
    ShowYAxis = igor_json:parse(Json, <<"show_y_axis">>, boolean, true),
    ShowXGridLine = igor_json:parse(Json, <<"show_x_grid_line">>, boolean, true),
    ShowYGridLine = igor_json:parse(Json, <<"show_y_grid_line">>, boolean, true),
    XAxisType = igor_json:parse(Json, <<"x_axis_type">>, {custom, fun visualization_protocol:axis_value_type_from_json/1}),
    YAxisType = igor_json:parse(Json, <<"y_axis_type">>, {custom, fun visualization_protocol:axis_value_type_from_json/1}),
    XAxisTitle = igor_json:parse(Json, <<"x_axis_title">>, string, <<"">>),
    YAxisTitle = igor_json:parse(Json, <<"y_axis_title">>, string, <<"">>),
    SecondaryYAxisTitle = igor_json:parse(Json, <<"secondary_y_axis_title">>, string, undefined),
    SecondaryYAxisType = igor_json:parse(Json, <<"secondary_y_axis_type">>, {custom, fun visualization_protocol:axis_value_type_from_json/1}, undefined),
    ShowTimeline = igor_json:parse(Json, <<"show_timeline">>, boolean, false),
    ShowLegend = igor_json:parse(Json, <<"show_legend">>, boolean, true),
    #visualization_synchronized_plot{
        name = Name,
        subtitle = Subtitle,
        description = Description,
        series = Series,
        show_x_axis = ShowXAxis,
        show_y_axis = ShowYAxis,
        show_x_grid_line = ShowXGridLine,
        show_y_grid_line = ShowYGridLine,
        x_axis_type = XAxisType,
        y_axis_type = YAxisType,
        x_axis_title = XAxisTitle,
        y_axis_title = YAxisTitle,
        secondary_y_axis_title = SecondaryYAxisTitle,
        secondary_y_axis_type = SecondaryYAxisType,
        show_timeline = ShowTimeline,
        show_legend = ShowLegend
    }.

-spec visualization_horizontal_bars_to_json(visualization_horizontal_bars()) -> igor_json:json_object().

visualization_horizontal_bars_to_json(Record) ->
    #visualization_horizontal_bars{
        name = Name,
        subtitle = Subtitle,
        description = Description,
        series = Series,
        show_x_axis = ShowXAxis,
        show_y_axis = ShowYAxis,
        show_x_grid_line = ShowXGridLine,
        show_y_grid_line = ShowYGridLine,
        x_axis_title = XAxisTitle,
        y_axis_title = YAxisTitle,
        show_legend = ShowLegend
    } = Record,
    ?assert(Name =/= undefined),
    ?assert(Description =/= undefined),
    ?assert(Series =/= undefined),
    ?assert(ShowXAxis =/= undefined),
    ?assert(ShowYAxis =/= undefined),
    ?assert(ShowXGridLine =/= undefined),
    ?assert(ShowYGridLine =/= undefined),
    ?assert(XAxisTitle =/= undefined),
    ?assert(YAxisTitle =/= undefined),
    ?assert(ShowLegend =/= undefined),
    #{
        <<"kind">> => igor_json:pack(horizontal_bars, {custom, fun visualization_protocol:visualization_kind_to_json/1}),
        <<"name">> => igor_json:pack(Name, string),
        <<"subtitle">> => igor_json:pack(Subtitle, string),
        <<"description">> => igor_json:pack(Description, string),
        <<"series">> => igor_json:pack(Series, {list, {custom, fun visualization_protocol:simple_serie_to_json/1}}),
        <<"show_x_axis">> => igor_json:pack(ShowXAxis, boolean),
        <<"show_y_axis">> => igor_json:pack(ShowYAxis, boolean),
        <<"show_x_grid_line">> => igor_json:pack(ShowXGridLine, boolean),
        <<"show_y_grid_line">> => igor_json:pack(ShowYGridLine, boolean),
        <<"x_axis_title">> => igor_json:pack(XAxisTitle, string),
        <<"y_axis_title">> => igor_json:pack(YAxisTitle, string),
        <<"show_legend">> => igor_json:pack(ShowLegend, boolean)
    }.

-spec visualization_horizontal_bars_from_json(igor_json:json_object()) -> visualization_horizontal_bars().

visualization_horizontal_bars_from_json(Json) ->
    Name = igor_json:parse(Json, <<"name">>, string),
    Subtitle = igor_json:parse(Json, <<"subtitle">>, string, undefined),
    Description = igor_json:parse(Json, <<"description">>, string),
    Series = igor_json:parse(Json, <<"series">>, {list, {custom, fun visualization_protocol:simple_serie_from_json/1}}),
    ShowXAxis = igor_json:parse(Json, <<"show_x_axis">>, boolean, true),
    ShowYAxis = igor_json:parse(Json, <<"show_y_axis">>, boolean, true),
    ShowXGridLine = igor_json:parse(Json, <<"show_x_grid_line">>, boolean, true),
    ShowYGridLine = igor_json:parse(Json, <<"show_y_grid_line">>, boolean, true),
    XAxisTitle = igor_json:parse(Json, <<"x_axis_title">>, string, <<"">>),
    YAxisTitle = igor_json:parse(Json, <<"y_axis_title">>, string, <<"">>),
    ShowLegend = igor_json:parse(Json, <<"show_legend">>, boolean, true),
    #visualization_horizontal_bars{
        name = Name,
        subtitle = Subtitle,
        description = Description,
        series = Series,
        show_x_axis = ShowXAxis,
        show_y_axis = ShowYAxis,
        show_x_grid_line = ShowXGridLine,
        show_y_grid_line = ShowYGridLine,
        x_axis_title = XAxisTitle,
        y_axis_title = YAxisTitle,
        show_legend = ShowLegend
    }.

-spec visualization_funnel_to_json(visualization_funnel()) -> igor_json:json_object().

visualization_funnel_to_json(Record) ->
    #visualization_funnel{
        name = Name,
        subtitle = Subtitle,
        description = Description,
        series = Series
    } = Record,
    ?assert(Name =/= undefined),
    ?assert(Description =/= undefined),
    ?assert(Series =/= undefined),
    #{
        <<"kind">> => igor_json:pack(funnel, {custom, fun visualization_protocol:visualization_kind_to_json/1}),
        <<"name">> => igor_json:pack(Name, string),
        <<"subtitle">> => igor_json:pack(Subtitle, string),
        <<"description">> => igor_json:pack(Description, string),
        <<"series">> => igor_json:pack(Series, {list, {custom, fun visualization_protocol:simple_serie_to_json/1}})
    }.

-spec visualization_funnel_from_json(igor_json:json_object()) -> visualization_funnel().

visualization_funnel_from_json(Json) ->
    Name = igor_json:parse(Json, <<"name">>, string),
    Subtitle = igor_json:parse(Json, <<"subtitle">>, string, undefined),
    Description = igor_json:parse(Json, <<"description">>, string),
    Series = igor_json:parse(Json, <<"series">>, {list, {custom, fun visualization_protocol:simple_serie_from_json/1}}),
    #visualization_funnel{
        name = Name,
        subtitle = Subtitle,
        description = Description,
        series = Series
    }.

-spec visualization_heatmap_to_json(visualization_heatmap()) -> igor_json:json_object().

visualization_heatmap_to_json(Record) ->
    #visualization_heatmap{
        name = Name,
        subtitle = Subtitle,
        description = Description,
        invert_x_axis = InvertXAxis,
        invert_y_axis = InvertYAxis,
        zoom_outside_map = ZoomOutsideMap
    } = Record,
    ?assert(Name =/= undefined),
    ?assert(Description =/= undefined),
    ?assert(InvertXAxis =/= undefined),
    ?assert(InvertYAxis =/= undefined),
    ?assert(ZoomOutsideMap =/= undefined),
    #{
        <<"kind">> => igor_json:pack(heatmap, {custom, fun visualization_protocol:visualization_kind_to_json/1}),
        <<"name">> => igor_json:pack(Name, string),
        <<"subtitle">> => igor_json:pack(Subtitle, string),
        <<"description">> => igor_json:pack(Description, string),
        <<"invert_x_axis">> => igor_json:pack(InvertXAxis, boolean),
        <<"invert_y_axis">> => igor_json:pack(InvertYAxis, boolean),
        <<"zoom_outside_map">> => igor_json:pack(ZoomOutsideMap, boolean)
    }.

-spec visualization_heatmap_from_json(igor_json:json_object()) -> visualization_heatmap().

visualization_heatmap_from_json(Json) ->
    Name = igor_json:parse(Json, <<"name">>, string),
    Subtitle = igor_json:parse(Json, <<"subtitle">>, string, undefined),
    Description = igor_json:parse(Json, <<"description">>, string),
    InvertXAxis = igor_json:parse(Json, <<"invert_x_axis">>, boolean, false),
    InvertYAxis = igor_json:parse(Json, <<"invert_y_axis">>, boolean, false),
    ZoomOutsideMap = igor_json:parse(Json, <<"zoom_outside_map">>, boolean, false),
    #visualization_heatmap{
        name = Name,
        subtitle = Subtitle,
        description = Description,
        invert_x_axis = InvertXAxis,
        invert_y_axis = InvertYAxis,
        zoom_outside_map = ZoomOutsideMap
    }.

-spec visualization_killmap_to_json(visualization_killmap()) -> igor_json:json_object().

visualization_killmap_to_json(Record) ->
    #visualization_killmap{
        name = Name,
        subtitle = Subtitle,
        description = Description,
        invert_x_axis = InvertXAxis,
        invert_y_axis = InvertYAxis,
        zoom_outside_map = ZoomOutsideMap,
        team_colors = TeamColors,
        radius = Radius
    } = Record,
    ?assert(Name =/= undefined),
    ?assert(Description =/= undefined),
    ?assert(InvertXAxis =/= undefined),
    ?assert(InvertYAxis =/= undefined),
    ?assert(ZoomOutsideMap =/= undefined),
    #{
        <<"kind">> => igor_json:pack(killmap, {custom, fun visualization_protocol:visualization_kind_to_json/1}),
        <<"name">> => igor_json:pack(Name, string),
        <<"subtitle">> => igor_json:pack(Subtitle, string),
        <<"description">> => igor_json:pack(Description, string),
        <<"invert_x_axis">> => igor_json:pack(InvertXAxis, boolean),
        <<"invert_y_axis">> => igor_json:pack(InvertYAxis, boolean),
        <<"zoom_outside_map">> => igor_json:pack(ZoomOutsideMap, boolean),
        <<"team_colors">> => igor_json:pack(TeamColors, {dict, string, string}),
        <<"radius">> => igor_json:pack(Radius, double)
    }.

-spec visualization_killmap_from_json(igor_json:json_object()) -> visualization_killmap().

visualization_killmap_from_json(Json) ->
    Name = igor_json:parse(Json, <<"name">>, string),
    Subtitle = igor_json:parse(Json, <<"subtitle">>, string, undefined),
    Description = igor_json:parse(Json, <<"description">>, string),
    InvertXAxis = igor_json:parse(Json, <<"invert_x_axis">>, boolean, false),
    InvertYAxis = igor_json:parse(Json, <<"invert_y_axis">>, boolean, false),
    ZoomOutsideMap = igor_json:parse(Json, <<"zoom_outside_map">>, boolean, false),
    TeamColors = igor_json:parse(Json, <<"team_colors">>, {dict, string, string}, undefined),
    Radius = igor_json:parse(Json, <<"radius">>, double, undefined),
    #visualization_killmap{
        name = Name,
        subtitle = Subtitle,
        description = Description,
        invert_x_axis = InvertXAxis,
        invert_y_axis = InvertYAxis,
        zoom_outside_map = ZoomOutsideMap,
        team_colors = TeamColors,
        radius = Radius
    }.

-spec visualization_scatter_to_json(visualization_scatter()) -> igor_json:json_object().

visualization_scatter_to_json(Record) ->
    #visualization_scatter{
        name = Name,
        subtitle = Subtitle,
        description = Description,
        series = Series,
        show_x_axis = ShowXAxis,
        show_y_axis = ShowYAxis,
        show_x_grid_line = ShowXGridLine,
        show_y_grid_line = ShowYGridLine,
        x_axis_type = XAxisType,
        y_axis_type = YAxisType,
        x_axis_title = XAxisTitle,
        y_axis_title = YAxisTitle,
        show_legend = ShowLegend,
        invert_x_axis = InvertXAxis,
        invert_y_axis = InvertYAxis
    } = Record,
    ?assert(Name =/= undefined),
    ?assert(Description =/= undefined),
    ?assert(Series =/= undefined),
    ?assert(ShowXAxis =/= undefined),
    ?assert(ShowYAxis =/= undefined),
    ?assert(ShowXGridLine =/= undefined),
    ?assert(ShowYGridLine =/= undefined),
    ?assert(XAxisType =/= undefined),
    ?assert(YAxisType =/= undefined),
    ?assert(XAxisTitle =/= undefined),
    ?assert(YAxisTitle =/= undefined),
    ?assert(ShowLegend =/= undefined),
    ?assert(InvertXAxis =/= undefined),
    ?assert(InvertYAxis =/= undefined),
    #{
        <<"kind">> => igor_json:pack(scatter, {custom, fun visualization_protocol:visualization_kind_to_json/1}),
        <<"name">> => igor_json:pack(Name, string),
        <<"subtitle">> => igor_json:pack(Subtitle, string),
        <<"description">> => igor_json:pack(Description, string),
        <<"series">> => igor_json:pack(Series, {list, {custom, fun visualization_protocol:scatter_serie_to_json/1}}),
        <<"show_x_axis">> => igor_json:pack(ShowXAxis, boolean),
        <<"show_y_axis">> => igor_json:pack(ShowYAxis, boolean),
        <<"show_x_grid_line">> => igor_json:pack(ShowXGridLine, boolean),
        <<"show_y_grid_line">> => igor_json:pack(ShowYGridLine, boolean),
        <<"x_axis_type">> => igor_json:pack(XAxisType, {custom, fun visualization_protocol:axis_value_type_to_json/1}),
        <<"y_axis_type">> => igor_json:pack(YAxisType, {custom, fun visualization_protocol:axis_value_type_to_json/1}),
        <<"x_axis_title">> => igor_json:pack(XAxisTitle, string),
        <<"y_axis_title">> => igor_json:pack(YAxisTitle, string),
        <<"show_legend">> => igor_json:pack(ShowLegend, boolean),
        <<"invert_x_axis">> => igor_json:pack(InvertXAxis, boolean),
        <<"invert_y_axis">> => igor_json:pack(InvertYAxis, boolean)
    }.

-spec visualization_scatter_from_json(igor_json:json_object()) -> visualization_scatter().

visualization_scatter_from_json(Json) ->
    Name = igor_json:parse(Json, <<"name">>, string),
    Subtitle = igor_json:parse(Json, <<"subtitle">>, string, undefined),
    Description = igor_json:parse(Json, <<"description">>, string),
    Series = igor_json:parse(Json, <<"series">>, {list, {custom, fun visualization_protocol:scatter_serie_from_json/1}}),
    ShowXAxis = igor_json:parse(Json, <<"show_x_axis">>, boolean, true),
    ShowYAxis = igor_json:parse(Json, <<"show_y_axis">>, boolean, true),
    ShowXGridLine = igor_json:parse(Json, <<"show_x_grid_line">>, boolean, true),
    ShowYGridLine = igor_json:parse(Json, <<"show_y_grid_line">>, boolean, true),
    XAxisType = igor_json:parse(Json, <<"x_axis_type">>, {custom, fun visualization_protocol:axis_value_type_from_json/1}),
    YAxisType = igor_json:parse(Json, <<"y_axis_type">>, {custom, fun visualization_protocol:axis_value_type_from_json/1}),
    XAxisTitle = igor_json:parse(Json, <<"x_axis_title">>, string, <<"">>),
    YAxisTitle = igor_json:parse(Json, <<"y_axis_title">>, string, <<"">>),
    ShowLegend = igor_json:parse(Json, <<"show_legend">>, boolean, true),
    InvertXAxis = igor_json:parse(Json, <<"invert_x_axis">>, boolean, false),
    InvertYAxis = igor_json:parse(Json, <<"invert_y_axis">>, boolean, false),
    #visualization_scatter{
        name = Name,
        subtitle = Subtitle,
        description = Description,
        series = Series,
        show_x_axis = ShowXAxis,
        show_y_axis = ShowYAxis,
        show_x_grid_line = ShowXGridLine,
        show_y_grid_line = ShowYGridLine,
        x_axis_type = XAxisType,
        y_axis_type = YAxisType,
        x_axis_title = XAxisTitle,
        y_axis_title = YAxisTitle,
        show_legend = ShowLegend,
        invert_x_axis = InvertXAxis,
        invert_y_axis = InvertYAxis
    }.

-spec visualization_box_plot_to_json(visualization_box_plot()) -> igor_json:json_object().

visualization_box_plot_to_json(Record) ->
    #visualization_box_plot{
        name = Name,
        subtitle = Subtitle,
        description = Description,
        show_x_axis = ShowXAxis,
        show_y_axis = ShowYAxis,
        show_x_grid_line = ShowXGridLine,
        show_y_grid_line = ShowYGridLine,
        x_axis_type = XAxisType,
        y_axis_type = YAxisType,
        x_axis_title = XAxisTitle,
        y_axis_title = YAxisTitle,
        show_legend = ShowLegend
    } = Record,
    ?assert(Name =/= undefined),
    ?assert(Description =/= undefined),
    ?assert(ShowXAxis =/= undefined),
    ?assert(ShowYAxis =/= undefined),
    ?assert(ShowXGridLine =/= undefined),
    ?assert(ShowYGridLine =/= undefined),
    ?assert(XAxisType =/= undefined),
    ?assert(YAxisType =/= undefined),
    ?assert(XAxisTitle =/= undefined),
    ?assert(YAxisTitle =/= undefined),
    ?assert(ShowLegend =/= undefined),
    #{
        <<"kind">> => igor_json:pack(box_plot, {custom, fun visualization_protocol:visualization_kind_to_json/1}),
        <<"name">> => igor_json:pack(Name, string),
        <<"subtitle">> => igor_json:pack(Subtitle, string),
        <<"description">> => igor_json:pack(Description, string),
        <<"show_x_axis">> => igor_json:pack(ShowXAxis, boolean),
        <<"show_y_axis">> => igor_json:pack(ShowYAxis, boolean),
        <<"show_x_grid_line">> => igor_json:pack(ShowXGridLine, boolean),
        <<"show_y_grid_line">> => igor_json:pack(ShowYGridLine, boolean),
        <<"x_axis_type">> => igor_json:pack(XAxisType, {custom, fun visualization_protocol:axis_value_type_to_json/1}),
        <<"y_axis_type">> => igor_json:pack(YAxisType, {custom, fun visualization_protocol:axis_value_type_to_json/1}),
        <<"x_axis_title">> => igor_json:pack(XAxisTitle, string),
        <<"y_axis_title">> => igor_json:pack(YAxisTitle, string),
        <<"show_legend">> => igor_json:pack(ShowLegend, boolean)
    }.

-spec visualization_box_plot_from_json(igor_json:json_object()) -> visualization_box_plot().

visualization_box_plot_from_json(Json) ->
    Name = igor_json:parse(Json, <<"name">>, string),
    Subtitle = igor_json:parse(Json, <<"subtitle">>, string, undefined),
    Description = igor_json:parse(Json, <<"description">>, string),
    ShowXAxis = igor_json:parse(Json, <<"show_x_axis">>, boolean, true),
    ShowYAxis = igor_json:parse(Json, <<"show_y_axis">>, boolean, true),
    ShowXGridLine = igor_json:parse(Json, <<"show_x_grid_line">>, boolean, true),
    ShowYGridLine = igor_json:parse(Json, <<"show_y_grid_line">>, boolean, true),
    XAxisType = igor_json:parse(Json, <<"x_axis_type">>, {custom, fun visualization_protocol:axis_value_type_from_json/1}),
    YAxisType = igor_json:parse(Json, <<"y_axis_type">>, {custom, fun visualization_protocol:axis_value_type_from_json/1}),
    XAxisTitle = igor_json:parse(Json, <<"x_axis_title">>, string, <<"">>),
    YAxisTitle = igor_json:parse(Json, <<"y_axis_title">>, string, <<"">>),
    ShowLegend = igor_json:parse(Json, <<"show_legend">>, boolean, true),
    #visualization_box_plot{
        name = Name,
        subtitle = Subtitle,
        description = Description,
        show_x_axis = ShowXAxis,
        show_y_axis = ShowYAxis,
        show_x_grid_line = ShowXGridLine,
        show_y_grid_line = ShowYGridLine,
        x_axis_type = XAxisType,
        y_axis_type = YAxisType,
        x_axis_title = XAxisTitle,
        y_axis_title = YAxisTitle,
        show_legend = ShowLegend
    }.

-spec visualization_raw_to_json(visualization_raw()) -> igor_json:json_object().

visualization_raw_to_json(Record) ->
    #visualization_raw{name = Name, subtitle = Subtitle, description = Description} = Record,
    ?assert(Name =/= undefined),
    ?assert(Description =/= undefined),
    #{
        <<"kind">> => igor_json:pack(raw, {custom, fun visualization_protocol:visualization_kind_to_json/1}),
        <<"name">> => igor_json:pack(Name, string),
        <<"subtitle">> => igor_json:pack(Subtitle, string),
        <<"description">> => igor_json:pack(Description, string)
    }.

-spec visualization_raw_from_json(igor_json:json_object()) -> visualization_raw().

visualization_raw_from_json(Json) ->
    Name = igor_json:parse(Json, <<"name">>, string),
    Subtitle = igor_json:parse(Json, <<"subtitle">>, string, undefined),
    Description = igor_json:parse(Json, <<"description">>, string),
    #visualization_raw{name = Name, subtitle = Subtitle, description = Description}.

