%% @author Igor compiler
%% @doc Compiler version: igorc 2.1.4
%% DO NOT EDIT THIS FILE - it is machine generated

-module(web_protocol).

-include_lib("stdlib/include/assert.hrl").
-include("web_protocol.hrl").

-export([
    access_role_to_string/1,
    access_role_from_string/1,
    access_role_to_json/1,
    access_role_from_json/1,
    personnel_login_error_to_string/1,
    personnel_login_error_from_string/1,
    personnel_login_error_to_json/1,
    personnel_login_error_from_json/1,
    personnel_account_order_by_to_string/1,
    personnel_account_order_by_from_string/1,
    personnel_account_order_by_to_json/1,
    personnel_account_order_by_from_json/1,
    personnel_group_order_by_to_string/1,
    personnel_group_order_by_from_string/1,
    personnel_group_order_by_to_json/1,
    personnel_group_order_by_from_json/1,
    personnel_account_role_order_by_to_string/1,
    personnel_account_role_order_by_from_string/1,
    personnel_account_role_order_by_to_json/1,
    personnel_account_role_order_by_from_json/1,
    personnel_group_role_order_by_to_string/1,
    personnel_group_role_order_by_from_string/1,
    personnel_group_role_order_by_to_json/1,
    personnel_group_role_order_by_from_json/1,
    generic_response_to_json/1,
    generic_response_from_json/1,
    personnel_status_response_to_json/1,
    personnel_status_response_from_json/1,
    personnel_login_request_to_json/1,
    personnel_login_request_from_json/1,
    personnel_login_response_to_json/1,
    personnel_login_response_from_json/1,
    personnel_account_to_json/1,
    personnel_account_from_json/1,
    personnel_account_profile_to_json/1,
    personnel_account_profile_from_json/1,
    personnel_group_to_json/1,
    personnel_group_from_json/1,
    personnel_account_role_to_json/1,
    personnel_account_role_from_json/1,
    personnel_group_role_to_json/1,
    personnel_group_role_from_json/1,
    access_role_update_request_to_json/1,
    access_role_update_request_from_json/1,
    settings_to_json/1,
    settings_from_json/1,
    settings_update_request_to_json/1,
    settings_update_request_from_json/1,
    analytics_query_node_result_to_json/1,
    analytics_query_node_result_from_json/1,
    analytics_query_result_to_json/1,
    analytics_query_result_from_json/1,
    widget_query_result_to_json/1,
    widget_query_result_from_json/1,
    project_config_to_json/1,
    project_config_from_json/1,
    dashboard_data_to_json/1,
    dashboard_data_from_json/1,
    analytics_data_to_json/1,
    analytics_data_from_json/1,
    event_data_to_json/1,
    event_data_from_json/1
]).

-export_type([
    access_role/0,
    generic_response/0,
    personnel_status_response/0,
    personnel_login_request/0,
    personnel_login_error/0,
    personnel_login_response/0,
    personnel_account/0,
    personnel_account_order_by/0,
    personnel_account_profile/0,
    personnel_group/0,
    personnel_group_order_by/0,
    personnel_account_role/0,
    personnel_account_role_order_by/0,
    personnel_group_role/0,
    personnel_group_role_order_by/0,
    access_role_update_request/0,
    settings/0,
    settings_update_request/0,
    analytics_query_node_result/0,
    analytics_query_result/0,
    widget_query_result/0,
    project_config/0,
    dashboard_data/0,
    analytics_data/0,
    event_data/0
]).

-type access_role() :: 'consumer' | 'maintainer' | 'admin'.
-type generic_response() :: #generic_response{}.
-type personnel_status_response() :: #personnel_status_response{}.
-type personnel_login_request() :: #personnel_login_request{}.
-type personnel_login_error() :: 'failure' | 'already_logged_in' | 'account_not_exists' | 'account_is_blocked' | 'account_is_deleted' | 'invalid_password'.
-type personnel_login_response() :: #personnel_login_response{}.
-type personnel_account() :: #personnel_account{}.
-type personnel_account_order_by() :: 'id' | 'username' | 'email' | 'is_blocked' | 'is_deleted' | 'created_at' | 'updated_at'.
-type personnel_account_profile() :: #personnel_account_profile{}.
-type personnel_group() :: #personnel_group{}.
-type personnel_group_order_by() :: 'id' | 'name' | 'is_deleted' | 'member_count' | 'created_at' | 'updated_at'.
-type personnel_account_role() :: #personnel_account_role{}.
-type personnel_account_role_order_by() :: 'personnel_id' | 'username' | 'project_id' | 'project_title' | 'user_role'.
-type personnel_group_role() :: #personnel_group_role{}.
-type personnel_group_role_order_by() :: 'group_id' | 'group_name' | 'project_id' | 'project_title' | 'group_role'.
-type access_role_update_request() :: #access_role_update_request{}.
-type settings() :: #settings{}.
-type settings_update_request() :: #settings_update_request{}.
-type analytics_query_node_result() :: #analytics_query_node_result{}.
-type analytics_query_result() :: #analytics_query_result{}.
-type widget_query_result() :: #widget_query_result{}.
-type project_config() :: #project_config{}.
-type dashboard_data() :: #dashboard_data{}.
-type analytics_data() :: #analytics_data{}.
-type event_data() :: #event_data{}.

-spec access_role_to_string(access_role()) -> binary().

access_role_to_string(consumer) -> <<"consumer">>;
access_role_to_string(maintainer) -> <<"maintainer">>;
access_role_to_string(admin) -> <<"admin">>.

-spec access_role_from_string(binary()) -> access_role().

access_role_from_string(<<"consumer">>) -> consumer;
access_role_from_string(<<"maintainer">>) -> maintainer;
access_role_from_string(<<"admin">>) -> admin.

-spec access_role_to_json(access_role()) -> igor_json:json_string().

access_role_to_json(consumer) -> <<"consumer">>;
access_role_to_json(maintainer) -> <<"maintainer">>;
access_role_to_json(admin) -> <<"admin">>.

-spec access_role_from_json(igor_json:json()) -> access_role().

access_role_from_json(<<"consumer">>) -> consumer;
access_role_from_json(<<"maintainer">>) -> maintainer;
access_role_from_json(<<"admin">>) -> admin.

-spec personnel_login_error_to_string(personnel_login_error()) -> binary().

personnel_login_error_to_string(failure) -> <<"failure">>;
personnel_login_error_to_string(already_logged_in) -> <<"already_logged_in">>;
personnel_login_error_to_string(account_not_exists) -> <<"account_not_exists">>;
personnel_login_error_to_string(account_is_blocked) -> <<"account_is_blocked">>;
personnel_login_error_to_string(account_is_deleted) -> <<"account_is_deleted">>;
personnel_login_error_to_string(invalid_password) -> <<"invalid_password">>.

-spec personnel_login_error_from_string(binary()) -> personnel_login_error().

personnel_login_error_from_string(<<"failure">>) -> failure;
personnel_login_error_from_string(<<"already_logged_in">>) -> already_logged_in;
personnel_login_error_from_string(<<"account_not_exists">>) -> account_not_exists;
personnel_login_error_from_string(<<"account_is_blocked">>) -> account_is_blocked;
personnel_login_error_from_string(<<"account_is_deleted">>) -> account_is_deleted;
personnel_login_error_from_string(<<"invalid_password">>) -> invalid_password.

-spec personnel_login_error_to_json(personnel_login_error()) -> igor_json:json_string().

personnel_login_error_to_json(failure) -> <<"failure">>;
personnel_login_error_to_json(already_logged_in) -> <<"already_logged_in">>;
personnel_login_error_to_json(account_not_exists) -> <<"account_not_exists">>;
personnel_login_error_to_json(account_is_blocked) -> <<"account_is_blocked">>;
personnel_login_error_to_json(account_is_deleted) -> <<"account_is_deleted">>;
personnel_login_error_to_json(invalid_password) -> <<"invalid_password">>.

-spec personnel_login_error_from_json(igor_json:json()) -> personnel_login_error().

personnel_login_error_from_json(<<"failure">>) -> failure;
personnel_login_error_from_json(<<"already_logged_in">>) -> already_logged_in;
personnel_login_error_from_json(<<"account_not_exists">>) -> account_not_exists;
personnel_login_error_from_json(<<"account_is_blocked">>) -> account_is_blocked;
personnel_login_error_from_json(<<"account_is_deleted">>) -> account_is_deleted;
personnel_login_error_from_json(<<"invalid_password">>) -> invalid_password.

-spec personnel_account_order_by_to_string(personnel_account_order_by()) -> binary().

personnel_account_order_by_to_string(id) -> <<"id">>;
personnel_account_order_by_to_string(username) -> <<"username">>;
personnel_account_order_by_to_string(email) -> <<"email">>;
personnel_account_order_by_to_string(is_blocked) -> <<"is_blocked">>;
personnel_account_order_by_to_string(is_deleted) -> <<"is_deleted">>;
personnel_account_order_by_to_string(created_at) -> <<"created_at">>;
personnel_account_order_by_to_string(updated_at) -> <<"updated_at">>.

-spec personnel_account_order_by_from_string(binary()) -> personnel_account_order_by().

personnel_account_order_by_from_string(<<"id">>) -> id;
personnel_account_order_by_from_string(<<"username">>) -> username;
personnel_account_order_by_from_string(<<"email">>) -> email;
personnel_account_order_by_from_string(<<"is_blocked">>) -> is_blocked;
personnel_account_order_by_from_string(<<"is_deleted">>) -> is_deleted;
personnel_account_order_by_from_string(<<"created_at">>) -> created_at;
personnel_account_order_by_from_string(<<"updated_at">>) -> updated_at.

-spec personnel_account_order_by_to_json(personnel_account_order_by()) -> igor_json:json_string().

personnel_account_order_by_to_json(id) -> <<"id">>;
personnel_account_order_by_to_json(username) -> <<"username">>;
personnel_account_order_by_to_json(email) -> <<"email">>;
personnel_account_order_by_to_json(is_blocked) -> <<"is_blocked">>;
personnel_account_order_by_to_json(is_deleted) -> <<"is_deleted">>;
personnel_account_order_by_to_json(created_at) -> <<"created_at">>;
personnel_account_order_by_to_json(updated_at) -> <<"updated_at">>.

-spec personnel_account_order_by_from_json(igor_json:json()) -> personnel_account_order_by().

personnel_account_order_by_from_json(<<"id">>) -> id;
personnel_account_order_by_from_json(<<"username">>) -> username;
personnel_account_order_by_from_json(<<"email">>) -> email;
personnel_account_order_by_from_json(<<"is_blocked">>) -> is_blocked;
personnel_account_order_by_from_json(<<"is_deleted">>) -> is_deleted;
personnel_account_order_by_from_json(<<"created_at">>) -> created_at;
personnel_account_order_by_from_json(<<"updated_at">>) -> updated_at.

-spec personnel_group_order_by_to_string(personnel_group_order_by()) -> binary().

personnel_group_order_by_to_string(id) -> <<"id">>;
personnel_group_order_by_to_string(name) -> <<"name">>;
personnel_group_order_by_to_string(is_deleted) -> <<"is_deleted">>;
personnel_group_order_by_to_string(member_count) -> <<"member_count">>;
personnel_group_order_by_to_string(created_at) -> <<"created_at">>;
personnel_group_order_by_to_string(updated_at) -> <<"updated_at">>.

-spec personnel_group_order_by_from_string(binary()) -> personnel_group_order_by().

personnel_group_order_by_from_string(<<"id">>) -> id;
personnel_group_order_by_from_string(<<"name">>) -> name;
personnel_group_order_by_from_string(<<"is_deleted">>) -> is_deleted;
personnel_group_order_by_from_string(<<"member_count">>) -> member_count;
personnel_group_order_by_from_string(<<"created_at">>) -> created_at;
personnel_group_order_by_from_string(<<"updated_at">>) -> updated_at.

-spec personnel_group_order_by_to_json(personnel_group_order_by()) -> igor_json:json_string().

personnel_group_order_by_to_json(id) -> <<"id">>;
personnel_group_order_by_to_json(name) -> <<"name">>;
personnel_group_order_by_to_json(is_deleted) -> <<"is_deleted">>;
personnel_group_order_by_to_json(member_count) -> <<"member_count">>;
personnel_group_order_by_to_json(created_at) -> <<"created_at">>;
personnel_group_order_by_to_json(updated_at) -> <<"updated_at">>.

-spec personnel_group_order_by_from_json(igor_json:json()) -> personnel_group_order_by().

personnel_group_order_by_from_json(<<"id">>) -> id;
personnel_group_order_by_from_json(<<"name">>) -> name;
personnel_group_order_by_from_json(<<"is_deleted">>) -> is_deleted;
personnel_group_order_by_from_json(<<"member_count">>) -> member_count;
personnel_group_order_by_from_json(<<"created_at">>) -> created_at;
personnel_group_order_by_from_json(<<"updated_at">>) -> updated_at.

-spec personnel_account_role_order_by_to_string(personnel_account_role_order_by()) -> binary().

personnel_account_role_order_by_to_string(personnel_id) -> <<"personnel_id">>;
personnel_account_role_order_by_to_string(username) -> <<"username">>;
personnel_account_role_order_by_to_string(project_id) -> <<"project_id">>;
personnel_account_role_order_by_to_string(project_title) -> <<"project_title">>;
personnel_account_role_order_by_to_string(user_role) -> <<"user_role">>.

-spec personnel_account_role_order_by_from_string(binary()) -> personnel_account_role_order_by().

personnel_account_role_order_by_from_string(<<"personnel_id">>) -> personnel_id;
personnel_account_role_order_by_from_string(<<"username">>) -> username;
personnel_account_role_order_by_from_string(<<"project_id">>) -> project_id;
personnel_account_role_order_by_from_string(<<"project_title">>) -> project_title;
personnel_account_role_order_by_from_string(<<"user_role">>) -> user_role.

-spec personnel_account_role_order_by_to_json(personnel_account_role_order_by()) -> igor_json:json_string().

personnel_account_role_order_by_to_json(personnel_id) -> <<"personnel_id">>;
personnel_account_role_order_by_to_json(username) -> <<"username">>;
personnel_account_role_order_by_to_json(project_id) -> <<"project_id">>;
personnel_account_role_order_by_to_json(project_title) -> <<"project_title">>;
personnel_account_role_order_by_to_json(user_role) -> <<"user_role">>.

-spec personnel_account_role_order_by_from_json(igor_json:json()) -> personnel_account_role_order_by().

personnel_account_role_order_by_from_json(<<"personnel_id">>) -> personnel_id;
personnel_account_role_order_by_from_json(<<"username">>) -> username;
personnel_account_role_order_by_from_json(<<"project_id">>) -> project_id;
personnel_account_role_order_by_from_json(<<"project_title">>) -> project_title;
personnel_account_role_order_by_from_json(<<"user_role">>) -> user_role.

-spec personnel_group_role_order_by_to_string(personnel_group_role_order_by()) -> binary().

personnel_group_role_order_by_to_string(group_id) -> <<"group_id">>;
personnel_group_role_order_by_to_string(group_name) -> <<"group_name">>;
personnel_group_role_order_by_to_string(project_id) -> <<"project_id">>;
personnel_group_role_order_by_to_string(project_title) -> <<"project_title">>;
personnel_group_role_order_by_to_string(group_role) -> <<"group_role">>.

-spec personnel_group_role_order_by_from_string(binary()) -> personnel_group_role_order_by().

personnel_group_role_order_by_from_string(<<"group_id">>) -> group_id;
personnel_group_role_order_by_from_string(<<"group_name">>) -> group_name;
personnel_group_role_order_by_from_string(<<"project_id">>) -> project_id;
personnel_group_role_order_by_from_string(<<"project_title">>) -> project_title;
personnel_group_role_order_by_from_string(<<"group_role">>) -> group_role.

-spec personnel_group_role_order_by_to_json(personnel_group_role_order_by()) -> igor_json:json_string().

personnel_group_role_order_by_to_json(group_id) -> <<"group_id">>;
personnel_group_role_order_by_to_json(group_name) -> <<"group_name">>;
personnel_group_role_order_by_to_json(project_id) -> <<"project_id">>;
personnel_group_role_order_by_to_json(project_title) -> <<"project_title">>;
personnel_group_role_order_by_to_json(group_role) -> <<"group_role">>.

-spec personnel_group_role_order_by_from_json(igor_json:json()) -> personnel_group_role_order_by().

personnel_group_role_order_by_from_json(<<"group_id">>) -> group_id;
personnel_group_role_order_by_from_json(<<"group_name">>) -> group_name;
personnel_group_role_order_by_from_json(<<"project_id">>) -> project_id;
personnel_group_role_order_by_from_json(<<"project_title">>) -> project_title;
personnel_group_role_order_by_from_json(<<"group_role">>) -> group_role.

-spec generic_response_to_json(generic_response()) -> igor_json:json_object().

generic_response_to_json(Record) ->
    #generic_response{result = VarResult} = Record,
    ?assert(VarResult =/= undefined),
    #{
        <<"result">> => igor_json:pack(VarResult, boolean)
    }.

-spec generic_response_from_json(igor_json:json_object()) -> generic_response().

generic_response_from_json(Json) ->
    VarResult = igor_json:parse(Json, <<"result">>, boolean),
    #generic_response{result = VarResult}.

-spec personnel_status_response_to_json(personnel_status_response()) -> igor_json:json_object().

personnel_status_response_to_json(Record) ->
    #personnel_status_response{
        logged_in = LoggedIn,
        user_id = UserId,
        email = Email,
        username = Username
    } = Record,
    ?assert(LoggedIn =/= undefined),
    #{
        <<"logged_in">> => igor_json:pack(LoggedIn, boolean),
        <<"user_id">> => igor_json:pack(UserId, long),
        <<"email">> => igor_json:pack(Email, string),
        <<"username">> => igor_json:pack(Username, string)
    }.

-spec personnel_status_response_from_json(igor_json:json_object()) -> personnel_status_response().

personnel_status_response_from_json(Json) ->
    LoggedIn = igor_json:parse(Json, <<"logged_in">>, boolean),
    UserId = igor_json:parse(Json, <<"user_id">>, long, undefined),
    Email = igor_json:parse(Json, <<"email">>, string, undefined),
    Username = igor_json:parse(Json, <<"username">>, string, undefined),
    #personnel_status_response{
        logged_in = LoggedIn,
        user_id = UserId,
        email = Email,
        username = Username
    }.

-spec personnel_login_request_to_json(personnel_login_request()) -> igor_json:json_object().

personnel_login_request_to_json(Record) ->
    #personnel_login_request{username = Username, password = Password} = Record,
    ?assert(Username =/= undefined),
    ?assert(Password =/= undefined),
    #{
        <<"username">> => igor_json:pack(Username, string),
        <<"password">> => igor_json:pack(Password, string)
    }.

-spec personnel_login_request_from_json(igor_json:json_object()) -> personnel_login_request().

personnel_login_request_from_json(Json) ->
    Username = igor_json:parse(Json, <<"username">>, string),
    Password = igor_json:parse(Json, <<"password">>, string),
    #personnel_login_request{username = Username, password = Password}.

-spec personnel_login_response_to_json(personnel_login_response()) -> igor_json:json_object().

personnel_login_response_to_json(Record) ->
    #personnel_login_response{
        result = VarResult,
        error = Error,
        session_id = SessionId,
        user_id = UserId,
        email = Email,
        username = Username
    } = Record,
    ?assert(VarResult =/= undefined),
    #{
        <<"result">> => igor_json:pack(VarResult, boolean),
        <<"error">> => igor_json:pack(Error, {custom, fun web_protocol:personnel_login_error_to_json/1}),
        <<"session_id">> => igor_json:pack(SessionId, string),
        <<"user_id">> => igor_json:pack(UserId, long),
        <<"email">> => igor_json:pack(Email, string),
        <<"username">> => igor_json:pack(Username, string)
    }.

-spec personnel_login_response_from_json(igor_json:json_object()) -> personnel_login_response().

personnel_login_response_from_json(Json) ->
    VarResult = igor_json:parse(Json, <<"result">>, boolean),
    Error = igor_json:parse(Json, <<"error">>, {custom, fun web_protocol:personnel_login_error_from_json/1}, undefined),
    SessionId = igor_json:parse(Json, <<"session_id">>, string, undefined),
    UserId = igor_json:parse(Json, <<"user_id">>, long, undefined),
    Email = igor_json:parse(Json, <<"email">>, string, undefined),
    Username = igor_json:parse(Json, <<"username">>, string, undefined),
    #personnel_login_response{
        result = VarResult,
        error = Error,
        session_id = SessionId,
        user_id = UserId,
        email = Email,
        username = Username
    }.

-spec personnel_account_to_json(personnel_account()) -> igor_json:json_object().

personnel_account_to_json(Record) ->
    #personnel_account{
        id = Id,
        rev = Rev,
        username = Username,
        name = Name,
        email = Email,
        phone = Phone,
        is_blocked = IsBlocked,
        is_deleted = IsDeleted,
        is_superadmin = IsSuperadmin,
        created_at = CreatedAt,
        updated_at = UpdatedAt
    } = Record,
    ?assert(Id =/= undefined),
    ?assert(Rev =/= undefined),
    ?assert(Username =/= undefined),
    ?assert(IsBlocked =/= undefined),
    ?assert(IsDeleted =/= undefined),
    ?assert(IsSuperadmin =/= undefined),
    ?assert(CreatedAt =/= undefined),
    ?assert(UpdatedAt =/= undefined),
    #{
        <<"id">> => igor_json:pack(Id, long),
        <<"rev">> => igor_json:pack(Rev, int),
        <<"username">> => igor_json:pack(Username, string),
        <<"name">> => igor_json:pack(Name, string),
        <<"email">> => igor_json:pack(Email, string),
        <<"phone">> => igor_json:pack(Phone, string),
        <<"is_blocked">> => igor_json:pack(IsBlocked, boolean),
        <<"is_deleted">> => igor_json:pack(IsDeleted, boolean),
        <<"is_superadmin">> => igor_json:pack(IsSuperadmin, boolean),
        <<"created_at">> => igor_json:pack(CreatedAt, {custom, fun web_types:datetime_to_text/1}),
        <<"updated_at">> => igor_json:pack(UpdatedAt, {custom, fun web_types:datetime_to_text/1})
    }.

-spec personnel_account_from_json(igor_json:json_object()) -> personnel_account().

personnel_account_from_json(Json) ->
    Id = igor_json:parse(Json, <<"id">>, long),
    Rev = igor_json:parse(Json, <<"rev">>, int),
    Username = igor_json:parse(Json, <<"username">>, string),
    Name = igor_json:parse(Json, <<"name">>, string, undefined),
    Email = igor_json:parse(Json, <<"email">>, string, undefined),
    Phone = igor_json:parse(Json, <<"phone">>, string, undefined),
    IsBlocked = igor_json:parse(Json, <<"is_blocked">>, boolean),
    IsDeleted = igor_json:parse(Json, <<"is_deleted">>, boolean),
    IsSuperadmin = igor_json:parse(Json, <<"is_superadmin">>, boolean),
    CreatedAt = igor_json:parse(Json, <<"created_at">>, {custom, fun web_types:datetime_from_text/1}),
    UpdatedAt = igor_json:parse(Json, <<"updated_at">>, {custom, fun web_types:datetime_from_text/1}),
    #personnel_account{
        id = Id,
        rev = Rev,
        username = Username,
        name = Name,
        email = Email,
        phone = Phone,
        is_blocked = IsBlocked,
        is_deleted = IsDeleted,
        is_superadmin = IsSuperadmin,
        created_at = CreatedAt,
        updated_at = UpdatedAt
    }.

-spec personnel_account_profile_to_json(personnel_account_profile()) -> igor_json:json_object().

personnel_account_profile_to_json(Record) ->
    #personnel_account_profile{
        id = Id,
        rev = Rev,
        username = Username,
        name = Name,
        email = Email,
        phone = Phone,
        is_blocked = IsBlocked,
        is_deleted = IsDeleted,
        is_project_manager = IsProjectManager,
        is_superadmin = IsSuperadmin,
        created_at = CreatedAt,
        updated_at = UpdatedAt
    } = Record,
    ?assert(Id =/= undefined),
    ?assert(Rev =/= undefined),
    ?assert(Username =/= undefined),
    ?assert(IsBlocked =/= undefined),
    ?assert(IsDeleted =/= undefined),
    ?assert(IsProjectManager =/= undefined),
    ?assert(IsSuperadmin =/= undefined),
    ?assert(CreatedAt =/= undefined),
    ?assert(UpdatedAt =/= undefined),
    #{
        <<"id">> => igor_json:pack(Id, long),
        <<"rev">> => igor_json:pack(Rev, int),
        <<"username">> => igor_json:pack(Username, string),
        <<"name">> => igor_json:pack(Name, string),
        <<"email">> => igor_json:pack(Email, string),
        <<"phone">> => igor_json:pack(Phone, string),
        <<"is_blocked">> => igor_json:pack(IsBlocked, boolean),
        <<"is_deleted">> => igor_json:pack(IsDeleted, boolean),
        <<"is_project_manager">> => igor_json:pack(IsProjectManager, boolean),
        <<"is_superadmin">> => igor_json:pack(IsSuperadmin, boolean),
        <<"created_at">> => igor_json:pack(CreatedAt, {custom, fun web_types:datetime_to_text/1}),
        <<"updated_at">> => igor_json:pack(UpdatedAt, {custom, fun web_types:datetime_to_text/1})
    }.

-spec personnel_account_profile_from_json(igor_json:json_object()) -> personnel_account_profile().

personnel_account_profile_from_json(Json) ->
    Id = igor_json:parse(Json, <<"id">>, long),
    Rev = igor_json:parse(Json, <<"rev">>, int),
    Username = igor_json:parse(Json, <<"username">>, string),
    Name = igor_json:parse(Json, <<"name">>, string, undefined),
    Email = igor_json:parse(Json, <<"email">>, string, undefined),
    Phone = igor_json:parse(Json, <<"phone">>, string, undefined),
    IsBlocked = igor_json:parse(Json, <<"is_blocked">>, boolean),
    IsDeleted = igor_json:parse(Json, <<"is_deleted">>, boolean),
    IsProjectManager = igor_json:parse(Json, <<"is_project_manager">>, boolean),
    IsSuperadmin = igor_json:parse(Json, <<"is_superadmin">>, boolean),
    CreatedAt = igor_json:parse(Json, <<"created_at">>, {custom, fun web_types:datetime_from_text/1}),
    UpdatedAt = igor_json:parse(Json, <<"updated_at">>, {custom, fun web_types:datetime_from_text/1}),
    #personnel_account_profile{
        id = Id,
        rev = Rev,
        username = Username,
        name = Name,
        email = Email,
        phone = Phone,
        is_blocked = IsBlocked,
        is_deleted = IsDeleted,
        is_project_manager = IsProjectManager,
        is_superadmin = IsSuperadmin,
        created_at = CreatedAt,
        updated_at = UpdatedAt
    }.

-spec personnel_group_to_json(personnel_group()) -> igor_json:json_object().

personnel_group_to_json(Record) ->
    #personnel_group{
        id = Id,
        rev = Rev,
        name = Name,
        description = Description,
        is_deleted = IsDeleted,
        members = Members,
        member_count = MemberCount,
        is_superadmin = IsSuperadmin,
        created_at = CreatedAt,
        updated_at = UpdatedAt
    } = Record,
    ?assert(Id =/= undefined),
    ?assert(Rev =/= undefined),
    ?assert(Name =/= undefined),
    ?assert(IsDeleted =/= undefined),
    ?assert(Members =/= undefined),
    ?assert(MemberCount =/= undefined),
    ?assert(IsSuperadmin =/= undefined),
    ?assert(CreatedAt =/= undefined),
    ?assert(UpdatedAt =/= undefined),
    #{
        <<"id">> => igor_json:pack(Id, long),
        <<"rev">> => igor_json:pack(Rev, int),
        <<"name">> => igor_json:pack(Name, string),
        <<"description">> => igor_json:pack(Description, string),
        <<"is_deleted">> => igor_json:pack(IsDeleted, boolean),
        <<"members">> => igor_json:pack(Members, {list, string}),
        <<"member_count">> => igor_json:pack(MemberCount, int),
        <<"is_superadmin">> => igor_json:pack(IsSuperadmin, boolean),
        <<"created_at">> => igor_json:pack(CreatedAt, {custom, fun web_types:datetime_to_text/1}),
        <<"updated_at">> => igor_json:pack(UpdatedAt, {custom, fun web_types:datetime_to_text/1})
    }.

-spec personnel_group_from_json(igor_json:json_object()) -> personnel_group().

personnel_group_from_json(Json) ->
    Id = igor_json:parse(Json, <<"id">>, long),
    Rev = igor_json:parse(Json, <<"rev">>, int),
    Name = igor_json:parse(Json, <<"name">>, string),
    Description = igor_json:parse(Json, <<"description">>, string, undefined),
    IsDeleted = igor_json:parse(Json, <<"is_deleted">>, boolean),
    Members = igor_json:parse(Json, <<"members">>, {list, string}),
    MemberCount = igor_json:parse(Json, <<"member_count">>, int),
    IsSuperadmin = igor_json:parse(Json, <<"is_superadmin">>, boolean),
    CreatedAt = igor_json:parse(Json, <<"created_at">>, {custom, fun web_types:datetime_from_text/1}),
    UpdatedAt = igor_json:parse(Json, <<"updated_at">>, {custom, fun web_types:datetime_from_text/1}),
    #personnel_group{
        id = Id,
        rev = Rev,
        name = Name,
        description = Description,
        is_deleted = IsDeleted,
        members = Members,
        member_count = MemberCount,
        is_superadmin = IsSuperadmin,
        created_at = CreatedAt,
        updated_at = UpdatedAt
    }.

-spec personnel_account_role_to_json(personnel_account_role()) -> igor_json:json_object().

personnel_account_role_to_json(Record) ->
    #personnel_account_role{
        personnel_id = PersonnelId,
        username = Username,
        project_id = ProjectId,
        project_title = ProjectTitle,
        project_dbs = ProjectDbs,
        group_roles = GroupRoles,
        user_role = UserRole,
        is_global = IsGlobal,
        dbs = Dbs
    } = Record,
    ?assert(PersonnelId =/= undefined),
    ?assert(Username =/= undefined),
    ?assert(ProjectId =/= undefined),
    ?assert(ProjectTitle =/= undefined),
    ?assert(ProjectDbs =/= undefined),
    #{
        <<"personnel_id">> => igor_json:pack(PersonnelId, long),
        <<"username">> => igor_json:pack(Username, string),
        <<"project_id">> => igor_json:pack(ProjectId, string),
        <<"project_title">> => igor_json:pack(ProjectTitle, string),
        <<"project_dbs">> => igor_json:pack(ProjectDbs, json),
        <<"group_roles">> => igor_json:pack(GroupRoles, json),
        <<"user_role">> => igor_json:pack(UserRole, {custom, fun web_protocol:access_role_to_json/1}),
        <<"is_global">> => igor_json:pack(IsGlobal, boolean),
        <<"dbs">> => igor_json:pack(Dbs, {list, string})
    }.

-spec personnel_account_role_from_json(igor_json:json_object()) -> personnel_account_role().

personnel_account_role_from_json(Json) ->
    PersonnelId = igor_json:parse(Json, <<"personnel_id">>, long),
    Username = igor_json:parse(Json, <<"username">>, string),
    ProjectId = igor_json:parse(Json, <<"project_id">>, string),
    ProjectTitle = igor_json:parse(Json, <<"project_title">>, string),
    ProjectDbs = igor_json:parse(Json, <<"project_dbs">>, json),
    GroupRoles = igor_json:parse(Json, <<"group_roles">>, json, undefined),
    UserRole = igor_json:parse(Json, <<"user_role">>, {custom, fun web_protocol:access_role_from_json/1}, undefined),
    IsGlobal = igor_json:parse(Json, <<"is_global">>, boolean, undefined),
    Dbs = igor_json:parse(Json, <<"dbs">>, {list, string}, undefined),
    #personnel_account_role{
        personnel_id = PersonnelId,
        username = Username,
        project_id = ProjectId,
        project_title = ProjectTitle,
        project_dbs = ProjectDbs,
        group_roles = GroupRoles,
        user_role = UserRole,
        is_global = IsGlobal,
        dbs = Dbs
    }.

-spec personnel_group_role_to_json(personnel_group_role()) -> igor_json:json_object().

personnel_group_role_to_json(Record) ->
    #personnel_group_role{
        group_id = GroupId,
        group_name = GroupName,
        project_id = ProjectId,
        project_title = ProjectTitle,
        project_dbs = ProjectDbs,
        group_role = GroupRole,
        is_global = IsGlobal,
        dbs = Dbs
    } = Record,
    ?assert(GroupId =/= undefined),
    ?assert(GroupName =/= undefined),
    ?assert(ProjectId =/= undefined),
    ?assert(ProjectTitle =/= undefined),
    ?assert(ProjectDbs =/= undefined),
    #{
        <<"group_id">> => igor_json:pack(GroupId, long),
        <<"group_name">> => igor_json:pack(GroupName, string),
        <<"project_id">> => igor_json:pack(ProjectId, string),
        <<"project_title">> => igor_json:pack(ProjectTitle, string),
        <<"project_dbs">> => igor_json:pack(ProjectDbs, json),
        <<"group_role">> => igor_json:pack(GroupRole, {custom, fun web_protocol:access_role_to_json/1}),
        <<"is_global">> => igor_json:pack(IsGlobal, boolean),
        <<"dbs">> => igor_json:pack(Dbs, {list, string})
    }.

-spec personnel_group_role_from_json(igor_json:json_object()) -> personnel_group_role().

personnel_group_role_from_json(Json) ->
    GroupId = igor_json:parse(Json, <<"group_id">>, long),
    GroupName = igor_json:parse(Json, <<"group_name">>, string),
    ProjectId = igor_json:parse(Json, <<"project_id">>, string),
    ProjectTitle = igor_json:parse(Json, <<"project_title">>, string),
    ProjectDbs = igor_json:parse(Json, <<"project_dbs">>, json),
    GroupRole = igor_json:parse(Json, <<"group_role">>, {custom, fun web_protocol:access_role_from_json/1}, undefined),
    IsGlobal = igor_json:parse(Json, <<"is_global">>, boolean, undefined),
    Dbs = igor_json:parse(Json, <<"dbs">>, {list, string}, undefined),
    #personnel_group_role{
        group_id = GroupId,
        group_name = GroupName,
        project_id = ProjectId,
        project_title = ProjectTitle,
        project_dbs = ProjectDbs,
        group_role = GroupRole,
        is_global = IsGlobal,
        dbs = Dbs
    }.

-spec access_role_update_request_to_json(access_role_update_request()) -> igor_json:json_object().

access_role_update_request_to_json(Record) ->
    #access_role_update_request{role = Role, is_global = IsGlobal, dbs = Dbs} = Record,
    ?assert(Role =/= undefined),
    #{
        <<"role">> => igor_json:pack(Role, {custom, fun web_protocol:access_role_to_json/1}),
        <<"is_global">> => igor_json:pack(IsGlobal, boolean),
        <<"dbs">> => igor_json:pack(Dbs, {list, string})
    }.

-spec access_role_update_request_from_json(igor_json:json_object()) -> access_role_update_request().

access_role_update_request_from_json(Json) ->
    Role = igor_json:parse(Json, <<"role">>, {custom, fun web_protocol:access_role_from_json/1}),
    IsGlobal = igor_json:parse(Json, <<"is_global">>, boolean, undefined),
    Dbs = igor_json:parse(Json, <<"dbs">>, {list, string}, undefined),
    #access_role_update_request{role = Role, is_global = IsGlobal, dbs = Dbs}.

-spec settings_to_json(settings()) -> igor_json:json_object().

settings_to_json(Record) ->
    #settings{personnel_session_duration = PersonnelSessionDuration} = Record,
    ?assert(PersonnelSessionDuration =/= undefined),
    #{
        <<"personnel_session_duration">> => igor_json:pack(PersonnelSessionDuration, int)
    }.

-spec settings_from_json(igor_json:json_object()) -> settings().

settings_from_json(Json) ->
    PersonnelSessionDuration = igor_json:parse(Json, <<"personnel_session_duration">>, int),
    #settings{personnel_session_duration = PersonnelSessionDuration}.

-spec settings_update_request_to_json(settings_update_request()) -> igor_json:json_object().

settings_update_request_to_json(Record) ->
    #settings_update_request{personnel_session_duration = PersonnelSessionDuration} = Record,
    #{
        <<"personnel_session_duration">> => igor_json:pack(PersonnelSessionDuration, int)
    }.

-spec settings_update_request_from_json(igor_json:json_object()) -> settings_update_request().

settings_update_request_from_json(Json) ->
    PersonnelSessionDuration = igor_json:parse(Json, <<"personnel_session_duration">>, int, undefined),
    #settings_update_request{personnel_session_duration = PersonnelSessionDuration}.

-spec analytics_query_node_result_to_json(analytics_query_node_result()) -> igor_json:json_object().

analytics_query_node_result_to_json(Record) ->
    #analytics_query_node_result{result = VarResult} = Record,
    ?assert(VarResult =/= undefined),
    #{
        <<"result">> => igor_json:pack(VarResult, {list, {option, {custom, fun data_protocol:series_to_json/1}}})
    }.

-spec analytics_query_node_result_from_json(igor_json:json_object()) -> analytics_query_node_result().

analytics_query_node_result_from_json(Json) ->
    VarResult = igor_json:parse(Json, <<"result">>, {list, {option, {custom, fun data_protocol:series_from_json/1}}}),
    #analytics_query_node_result{result = VarResult}.

-spec analytics_query_result_to_json(analytics_query_result()) -> igor_json:json_object().

analytics_query_result_to_json(Record) ->
    #analytics_query_result{query = Query, result = VarResult} = Record,
    ?assert(Query =/= undefined),
    ?assert(VarResult =/= undefined),
    #{
        <<"query">> => igor_json:pack(Query, string),
        <<"result">> => igor_json:pack(VarResult, {list, {custom, fun web_protocol:analytics_query_node_result_to_json/1}})
    }.

-spec analytics_query_result_from_json(igor_json:json_object()) -> analytics_query_result().

analytics_query_result_from_json(Json) ->
    Query = igor_json:parse(Json, <<"query">>, string),
    VarResult = igor_json:parse(Json, <<"result">>, {list, {custom, fun web_protocol:analytics_query_node_result_from_json/1}}),
    #analytics_query_result{query = Query, result = VarResult}.

-spec widget_query_result_to_json(widget_query_result()) -> igor_json:json_object().

widget_query_result_to_json(Record) ->
    #widget_query_result{query = Query, result = VarResult} = Record,
    ?assert(Query =/= undefined),
    ?assert(VarResult =/= undefined),
    #{
        <<"query">> => igor_json:pack(Query, string),
        <<"result">> => igor_json:pack(VarResult, {custom, fun web_protocol:analytics_query_node_result_to_json/1})
    }.

-spec widget_query_result_from_json(igor_json:json_object()) -> widget_query_result().

widget_query_result_from_json(Json) ->
    Query = igor_json:parse(Json, <<"query">>, string),
    VarResult = igor_json:parse(Json, <<"result">>, {custom, fun web_protocol:analytics_query_node_result_from_json/1}),
    #widget_query_result{query = Query, result = VarResult}.

-spec project_config_to_json(project_config()) -> igor_json:json_object().

project_config_to_json(Record) ->
    #project_config{id = Id, name = Name, databases = Databases} = Record,
    ?assert(Id =/= undefined),
    ?assert(Name =/= undefined),
    ?assert(Databases =/= undefined),
    #{
        <<"id">> => igor_json:pack(Id, string),
        <<"name">> => igor_json:pack(Name, string),
        <<"databases">> => igor_json:pack(Databases, {list, string})
    }.

-spec project_config_from_json(igor_json:json_object()) -> project_config().

project_config_from_json(Json) ->
    Id = igor_json:parse(Json, <<"id">>, string),
    Name = igor_json:parse(Json, <<"name">>, string),
    Databases = igor_json:parse(Json, <<"databases">>, {list, string}),
    #project_config{id = Id, name = Name, databases = Databases}.

-spec dashboard_data_to_json(dashboard_data()) -> igor_json:json_object().

dashboard_data_to_json(Record) ->
    #dashboard_data{params = Params, widgets = Widgets} = Record,
    ?assert(Params =/= undefined),
    ?assert(Widgets =/= undefined),
    #{
        <<"params">> => igor_json:pack(Params, {list, {custom, fun card_protocol:card_query_param_to_json/1}}),
        <<"widgets">> => igor_json:pack(Widgets, {list, {custom, fun card_protocol:card_widget_to_json/1}})
    }.

-spec dashboard_data_from_json(igor_json:json_object()) -> dashboard_data().

dashboard_data_from_json(Json) ->
    Params = igor_json:parse(Json, <<"params">>, {list, {custom, fun card_protocol:card_query_param_from_json/1}}),
    Widgets = igor_json:parse(Json, <<"widgets">>, {list, {custom, fun card_protocol:card_widget_from_json/1}}),
    #dashboard_data{params = Params, widgets = Widgets}.

-spec analytics_data_to_json(analytics_data()) -> igor_json:json_object().

analytics_data_to_json(Record) ->
    #analytics_data{
        metrics = Metrics,
        maps = Maps,
        params = Params,
        queries = Queries
    } = Record,
    ?assert(Metrics =/= undefined),
    ?assert(Maps =/= undefined),
    ?assert(Params =/= undefined),
    ?assert(Queries =/= undefined),
    #{
        <<"metrics">> => igor_json:pack(Metrics, {list, {custom, fun card_protocol:card_metric_to_json/1}}),
        <<"maps">> => igor_json:pack(Maps, {list, {custom, fun card_protocol:card_map_to_json/1}}),
        <<"params">> => igor_json:pack(Params, {list, {custom, fun card_protocol:card_query_param_to_json/1}}),
        <<"queries">> => igor_json:pack(Queries, {list, {custom, fun card_protocol:card_query_to_json/1}})
    }.

-spec analytics_data_from_json(igor_json:json_object()) -> analytics_data().

analytics_data_from_json(Json) ->
    Metrics = igor_json:parse(Json, <<"metrics">>, {list, {custom, fun card_protocol:card_metric_from_json/1}}),
    Maps = igor_json:parse(Json, <<"maps">>, {list, {custom, fun card_protocol:card_map_from_json/1}}),
    Params = igor_json:parse(Json, <<"params">>, {list, {custom, fun card_protocol:card_query_param_from_json/1}}),
    Queries = igor_json:parse(Json, <<"queries">>, {list, {custom, fun card_protocol:card_query_from_json/1}}),
    #analytics_data{
        metrics = Metrics,
        maps = Maps,
        params = Params,
        queries = Queries
    }.

-spec event_data_to_json(event_data()) -> igor_json:json_object().

event_data_to_json(Record) ->
    #event_data{super_fields = SuperFields, events = Events, groups = Groups} = Record,
    ?assert(SuperFields =/= undefined),
    ?assert(Events =/= undefined),
    ?assert(Groups =/= undefined),
    #{
        <<"super_fields">> => igor_json:pack(SuperFields, {list, string}),
        <<"events">> => igor_json:pack(Events, {list, {custom, fun card_protocol:card_event_to_json/1}}),
        <<"groups">> => igor_json:pack(Groups, {list, {custom, fun card_protocol:card_event_group_to_json/1}})
    }.

-spec event_data_from_json(igor_json:json_object()) -> event_data().

event_data_from_json(Json) ->
    SuperFields = igor_json:parse(Json, <<"super_fields">>, {list, string}),
    Events = igor_json:parse(Json, <<"events">>, {list, {custom, fun card_protocol:card_event_from_json/1}}),
    Groups = igor_json:parse(Json, <<"groups">>, {list, {custom, fun card_protocol:card_event_group_from_json/1}}),
    #event_data{super_fields = SuperFields, events = Events, groups = Groups}.

