%% Author: Igor compiler
%% Compiler version: igorc 2.1.4
%% DO NOT EDIT THIS FILE - it is machine generated

-record(collection, {
    items :: [_T]
}).

-record(collection_slice, {
    total :: igor_types:int(),
    items :: [_T]
}).

-record(int_value, {
    value :: igor_types:int()
}).

-record(numeric_point, {
    label :: binary(),
    value :: float()
}).

-record(box_plot_point, {
    label :: binary(),
    value :: [float()]
}).

-record(confidence_point, {
    label :: binary(),
    value :: float(),
    t_value :: float(),
    std_error :: float()
}).

-record(string_point, {
    label :: binary(),
    value :: binary()
}).

-record(date_point, {
    date :: iso8601:date(),
    count :: igor_types:int()
}).

-record(json_point, {
    label :: binary(),
    value :: igor_json:json()
}).

-record(point2_d, {
    x :: float(),
    y :: float()
}).

-record(point3_d, {
    x :: float(),
    y :: float(),
    z :: float()
}).

-record(kill_point, {
    killer_x :: float(),
    killer_y :: float(),
    killer_z = 0.0 :: float(),
    killer_team :: binary(),
    victim_x :: float(),
    victim_y :: float(),
    victim_z = 0.0 :: float(),
    victim_team :: binary(),
    death_reason :: binary(),
    match_time :: igor_types:int()
}).

-record(scatter_point, {
    x :: binary(),
    y :: binary(),
    value :: float()
}).

-record(numeric_value, {
    key :: binary() | 'undefined',
    data :: data_protocol:numeric_point()
}).

-record(box_plot_series, {
    key :: binary() | 'undefined',
    data :: [data_protocol:box_plot_point()]
}).

-record(numeric_series, {
    key :: binary() | 'undefined',
    data :: [data_protocol:numeric_point()]
}).

-record(date_series, {
    key :: binary() | 'undefined',
    data :: [data_protocol:date_point()]
}).

-record(heatmap_series, {
    key :: binary() | 'undefined',
    maps = [] :: [binary()],
    data :: [data_protocol:point2_d()]
}).

-record(killmap_series, {
    key :: binary() | 'undefined',
    map :: binary(),
    data :: [data_protocol:kill_point()]
}).

-record(scatter_series, {
    key :: binary() | 'undefined',
    data :: [data_protocol:scatter_point()]
}).

-record(confidence_series, {
    key :: binary() | 'undefined',
    data :: [data_protocol:confidence_point()]
}).

-record(raw_series, {
    key :: binary() | 'undefined',
    data :: [igor_json:json()]
}).

-record(query_node, {
    input_sql :: binary(),
    output :: visualization_protocol:visualization()
}).

