%% Author: Igor compiler
%% Compiler version: igorc 2.1.4
%% DO NOT EDIT THIS FILE - it is machine generated

-record(simple_serie, {
    name :: binary() | 'undefined',
    key :: binary() | 'undefined'
}).

-record(chart_serie, {
    name :: binary() | 'undefined',
    key :: binary() | 'undefined',
    group_index :: igor_types:int() | 'undefined',
    color :: binary() | 'undefined',
    chart_type :: visualization_protocol:chart_type(),
    y_axis = primary :: visualization_protocol:axis_kind_y(),
    show_values = true :: boolean()
}).

-record(scatter_serie, {
    name :: binary() | 'undefined',
    key :: binary() | 'undefined',
    color :: binary() | 'undefined',
    radius :: float() | 'undefined'
}).

-record(visualization_indicator, {
    name :: binary(),
    subtitle :: binary() | 'undefined',
    description :: binary(),
    label :: binary()
}).

-record(visualization_common_plot, {
    name :: binary(),
    subtitle :: binary() | 'undefined',
    description :: binary(),
    series :: [visualization_protocol:chart_serie()],
    show_x_axis = true :: boolean(),
    show_y_axis = true :: boolean(),
    show_x_grid_line = true :: boolean(),
    show_y_grid_line = true :: boolean(),
    x_axis_type :: visualization_protocol:axis_value_type(),
    y_axis_type :: visualization_protocol:axis_value_type(),
    x_axis_title = <<"">> :: binary(),
    y_axis_title = <<"">> :: binary(),
    secondary_y_axis_title :: binary() | 'undefined',
    secondary_y_axis_type :: visualization_protocol:axis_value_type() | 'undefined',
    show_timeline = false :: boolean(),
    show_legend = true :: boolean(),
    show_estimate = false :: boolean()
}).

-record(visualization_synchronized_plot, {
    name :: binary(),
    subtitle :: binary() | 'undefined',
    description :: binary(),
    series :: [visualization_protocol:chart_serie()],
    show_x_axis = true :: boolean(),
    show_y_axis = true :: boolean(),
    show_x_grid_line = true :: boolean(),
    show_y_grid_line = true :: boolean(),
    x_axis_type :: visualization_protocol:axis_value_type(),
    y_axis_type :: visualization_protocol:axis_value_type(),
    x_axis_title = <<"">> :: binary(),
    y_axis_title = <<"">> :: binary(),
    secondary_y_axis_title :: binary() | 'undefined',
    secondary_y_axis_type :: visualization_protocol:axis_value_type() | 'undefined',
    show_timeline = false :: boolean(),
    show_legend = true :: boolean()
}).

-record(visualization_horizontal_bars, {
    name :: binary(),
    subtitle :: binary() | 'undefined',
    description :: binary(),
    series :: [visualization_protocol:simple_serie()],
    show_x_axis = true :: boolean(),
    show_y_axis = true :: boolean(),
    show_x_grid_line = true :: boolean(),
    show_y_grid_line = true :: boolean(),
    x_axis_title = <<"">> :: binary(),
    y_axis_title = <<"">> :: binary(),
    show_legend = true :: boolean()
}).

-record(visualization_funnel, {
    name :: binary(),
    subtitle :: binary() | 'undefined',
    description :: binary(),
    series :: [visualization_protocol:simple_serie()]
}).

-record(visualization_heatmap, {
    name :: binary(),
    subtitle :: binary() | 'undefined',
    description :: binary(),
    invert_x_axis = false :: boolean(),
    invert_y_axis = false :: boolean(),
    zoom_outside_map = false :: boolean()
}).

-record(visualization_killmap, {
    name :: binary(),
    subtitle :: binary() | 'undefined',
    description :: binary(),
    invert_x_axis = false :: boolean(),
    invert_y_axis = false :: boolean(),
    zoom_outside_map = false :: boolean(),
    team_colors :: igor_types:dict(binary(), binary()) | 'undefined',
    radius :: float() | 'undefined'
}).

-record(visualization_scatter, {
    name :: binary(),
    subtitle :: binary() | 'undefined',
    description :: binary(),
    series :: [visualization_protocol:scatter_serie()],
    show_x_axis = true :: boolean(),
    show_y_axis = true :: boolean(),
    show_x_grid_line = true :: boolean(),
    show_y_grid_line = true :: boolean(),
    x_axis_type :: visualization_protocol:axis_value_type(),
    y_axis_type :: visualization_protocol:axis_value_type(),
    x_axis_title = <<"">> :: binary(),
    y_axis_title = <<"">> :: binary(),
    show_legend = true :: boolean(),
    invert_x_axis = false :: boolean(),
    invert_y_axis = false :: boolean()
}).

-record(visualization_box_plot, {
    name :: binary(),
    subtitle :: binary() | 'undefined',
    description :: binary(),
    show_x_axis = true :: boolean(),
    show_y_axis = true :: boolean(),
    show_x_grid_line = true :: boolean(),
    show_y_grid_line = true :: boolean(),
    x_axis_type :: visualization_protocol:axis_value_type(),
    y_axis_type :: visualization_protocol:axis_value_type(),
    x_axis_title = <<"">> :: binary(),
    y_axis_title = <<"">> :: binary(),
    show_legend = true :: boolean()
}).

-record(visualization_raw, {
    name :: binary(),
    subtitle :: binary() | 'undefined',
    description :: binary()
}).

