%% Author: Igor compiler
%% Compiler version: igorc 2.1.4
%% DO NOT EDIT THIS FILE - it is machine generated

-record(generic_response, {
    result :: boolean()
}).

-record(personnel_status_response, {
    logged_in :: boolean(),
    user_id :: igor_types:long() | 'undefined',
    email :: binary() | 'undefined',
    username :: binary() | 'undefined'
}).

-record(personnel_login_request, {
    username :: binary(),
    password :: binary()
}).

-record(personnel_login_response, {
    result :: boolean(),
    error :: web_protocol:personnel_login_error() | 'undefined',
    session_id :: binary() | 'undefined',
    user_id :: igor_types:long() | 'undefined',
    email :: binary() | 'undefined',
    username :: binary() | 'undefined'
}).

-record(personnel_account, {
    id :: igor_types:long(),
    rev :: igor_types:int(),
    username :: binary(),
    name :: binary() | 'undefined',
    email :: binary() | 'undefined',
    phone :: binary() | 'undefined',
    is_blocked :: boolean(),
    is_deleted :: boolean(),
    is_superadmin :: boolean(),
    created_at :: iso8601:datetimems(),
    updated_at :: iso8601:datetimems()
}).

-record(personnel_account_profile, {
    id :: igor_types:long(),
    rev :: igor_types:int(),
    username :: binary(),
    name :: binary() | 'undefined',
    email :: binary() | 'undefined',
    phone :: binary() | 'undefined',
    is_blocked :: boolean(),
    is_deleted :: boolean(),
    is_project_manager :: boolean(),
    is_superadmin :: boolean(),
    created_at :: iso8601:datetimems(),
    updated_at :: iso8601:datetimems()
}).

-record(personnel_group, {
    id :: igor_types:long(),
    rev :: igor_types:int(),
    name :: binary(),
    description :: binary() | 'undefined',
    is_deleted :: boolean(),
    members :: [binary()],
    member_count :: igor_types:int(),
    is_superadmin :: boolean(),
    created_at :: iso8601:datetimems(),
    updated_at :: iso8601:datetimems()
}).

-record(personnel_account_role, {
    personnel_id :: igor_types:long(),
    username :: binary(),
    project_id :: binary(),
    project_title :: binary(),
    project_dbs :: igor_json:json(),
    group_roles :: igor_json:json() | 'undefined',
    user_role :: web_protocol:access_role() | 'undefined',
    is_global :: boolean() | 'undefined',
    dbs :: [binary()] | 'undefined'
}).

-record(personnel_group_role, {
    group_id :: igor_types:long(),
    group_name :: binary(),
    project_id :: binary(),
    project_title :: binary(),
    project_dbs :: igor_json:json(),
    group_role :: web_protocol:access_role() | 'undefined',
    is_global :: boolean() | 'undefined',
    dbs :: [binary()] | 'undefined'
}).

-record(access_role_update_request, {
    role :: web_protocol:access_role(),
    is_global :: boolean() | 'undefined',
    dbs :: [binary()] | 'undefined'
}).

-record(settings, {
    personnel_session_duration :: igor_types:int()
}).

-record(settings_update_request, {
    personnel_session_duration :: igor_types:int() | 'undefined'
}).

-record(analytics_query_node_result, {
    result :: [data_protocol:series() | 'undefined']
}).

-record(analytics_query_result, {
    query :: binary(),
    result :: [web_protocol:analytics_query_node_result()]
}).

-record(widget_query_result, {
    query :: binary(),
    result :: web_protocol:analytics_query_node_result()
}).

-record(project_config, {
    id :: binary(),
    name :: binary(),
    databases :: [binary()]
}).

-record(dashboard_data, {
    params :: [card_protocol:card_query_param()],
    widgets :: [card_protocol:card_widget()]
}).

-record(analytics_data, {
    metrics :: [card_protocol:card_metric()],
    maps :: [card_protocol:card_map()],
    params :: [card_protocol:card_query_param()],
    queries :: [card_protocol:card_query()]
}).

-record(event_data, {
    super_fields :: [binary()],
    events :: [card_protocol:card_event()],
    groups :: [card_protocol:card_event_group()]
}).

