%% @author Igor compiler
%% @doc Compiler version: igorc 2.1.4
%% DO NOT EDIT THIS FILE - it is machine generated

-module(clickhouse_api).

-export([
    send_query/4
]).

send_query(BaseUrl, Database, SqlQuery, BasicAuth) ->
    Query = igor_http:compose_query([{"database", Database, {option, string}}, {"query", SqlQuery, string}]),
    Url = lists:flatten(io_lib:format("~s/?~s", [BaseUrl, Query])),
    Request = {Url, [{"Authorization", [BasicAuth]}, {"TE", "trailers"}, {"X-ClickHouse-Format", "JSON"}]},
    case httpc:request(get, Request, [], [{body_format, binary}]) of
        {ok, {{_HttpVersion, 200, _ReasonPhrase}, _Headers, Body}} ->
            clickhouse_protocol:query_result_from_json(jsx:decode(Body, [return_maps]));
        {ok, {{_HttpVersion, 400, _ReasonPhrase}, _Headers, Body}} ->
            throw(Body);
        {ok, {{_HttpVersion, 403, _ReasonPhrase}, _Headers, Body}} ->
            throw(Body);
        {ok, {{_HttpVersion, 404, _ReasonPhrase}, _Headers, Body}} ->
            throw(Body);
        {ok, {{_HttpVersion, 500, _ReasonPhrase}, _Headers, Body}} ->
            throw(Body);
        {ok, {{_HttpVersion, StatusCode, _ReasonPhrase}, _Headers, Body}} ->
            error({http_error, StatusCode, Body});
        {error, Reason} ->
            error(Reason)
    end.

